### ISSUE TITLE
[Mutator] Crazy!

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1001]
Looks like the author is  wost

The mutator gives everyone a Redeemer - simple as that - doesn't say if it replaces all other weapons.  The ammo is invisible which perhaps limits its usefulness?

---
URL: https://unrealarchive.org/mutators/unreal-tournament/C/crazy_0759f5c6.html
Hash: 0759f5c67fbd459895f452db87e8d87201ac65dc
Current name: Crazy!

**Comment by shrimpza** [comment]
Updated and added description "gives everyone a Redeemer"
