### ISSUE TITLE
[Mutator] CTFAlive

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1002]
According to the info with the mutator, the author is Patrick Freeman 
He's also known as "Mental"  and has I think appeared as Patrick "Mental" Freeman

His description of the mutator is "This mutator for CTF games lowers a players strength after they are killed. Strength is restored after a flag capture, or after a timer runs out, whichever comes first."

---
URL: https://unrealarchive.org/mutators/unreal-tournament/C/ctfalive_ef969cc5.html
Hash: ef969cc57712456e57fa74235d3b7be62abc97e9
Current name: CTFAlive

**Comment by shrimpza** [comment]
Updated
