### ISSUE TITLE
[Mutator] Cw V2 0 Skinpack Umod

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1003]
This is more a skinpack than anything else - perhaps it should be under Skins if it isn't already or a link from Skins to this package?

Looks like the author is  K_St_theJunior

---
URL: https://unrealarchive.org/mutators/unreal-tournament/C/cw-v2-0-skinpack-umod_993265ab.html
Hash: 993265abc4aeac2127c1faab3ffe75803a0b3d40
Current name: Cw V2 0 Skinpack Umod

**Comment by NeonKnightOA** [comment]
I've edited the author, the rest should be done by someone else.
