### ISSUE TITLE
[Mutator] CTFDoTheRightThing

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1004]
According to the readme, the author is  *Bubba

The author's description of the mutator is "adds a new message and a scoring bonus when a player kills someone whom is aiming at his or her team's flag carrier"

---
URL: https://unrealarchive.org/mutators/unreal-tournament/C/ctfdotherightthing_e2b5a38e.html
Hash: e2b5a38efd0095be7590e1b6af88cf23c3d398c7
Current name: CTFDoTheRightThing

**Comment by shrimpza** [comment]
Updated
