### ISSUE TITLE
[Mutator] CUTeamplay

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1006]
According to the documentation the author is  kloc13
He has other names that are noted in other recent 'issues'

I suppose it is obvious but this is designed for use with Cosmic Unreal v200

---
URL: https://unrealarchive.org/mutators/unreal-tournament/C/cuteamplay_cbbd26f5.html
Hash: cbbd26f5da9b0ddc1f76809ce33ba0d2da43942d
Current name: CUTeamplay

**Comment by shrimpza** [comment]
Updated
