### ISSUE TITLE
[Mutator] DamageBubble

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1007]
According to a note in the code, the author is  {oToD}Dentures

---
URL: https://unrealarchive.org/mutators/unreal-tournament/D/damagebubble_47dfa69f.html
Hash: 47dfa69f65bfd7f5bb31ad93834cbfdd1a6541f8
Current name: DamageBubble

**Comment by shrimpza** [comment]
Updated
