### ISSUE TITLE
[Mutator] DamageMutators

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1009]
The author is Wizard

The mutators are just called LessDamage and MoreDamage - should probably remove the "by Wizard" which may give slightly the wroing impression to potential users?

---
URL: https://unrealarchive.org/mutators/unreal-tournament/D/damagemutators_d0fd998c.html
Hash: d0fd998c328861924cd1c743977a72c393f8c8de
Current name: DamageMutators

**Comment by shrimpza** [comment]
Updated author, but leaving the "by Wizard" bit as that's part of the Mutator name which will show up in-game too.
