### ISSUE TITLE
[Mutator] Yard Sale!

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1011]
According to a note in the code, the authors are gopostal and TheManNo1{HoF}
Credit is also given to |404|shiftre, the creator of Pinata on which this mutator is based.

From the readme, the Description could be "a mod that drops all weapons and pickups you are carrying when you are killed by a monster (only!)"
Bascially the mutator is designed to work with MH

---
URL: https://unrealarchive.org/mutators/unreal-tournament/Y/yard-sale_9f48e402.html
Hash: 9f48e40271eee93753b0fba108b2d7e8e1a4f932
Current name: Yard Sale!

**Comment by shrimpza** [comment]
Updated
