### ISSUE TITLE
[Model] PostalDude

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1016]
The author is trevor0402 
At least that's the user name on UT99.org - see this thread https://ut99.org/viewtopic.php?f=13&t=11516&p=89016&hilit=postal#p88429
Creation date around May 2016, not Jan 2022

---
URL: https://unrealarchive.org/models/unreal-tournament/P/postaldude_b6e1029a.html
Hash: b6e1029aba644572c512d95346175692542f158b
Current name: PostalDude

**Comment by shrimpza** [comment]
Updated
