### ISSUE TITLE
[Skin] IronMan

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1017]
This is an interesting one - the skin is virtually identical to skins in SoldierSkins_Irnb by Owen Oliver.

LineARC has copied the readme though there are some omissions from the original - the layout is also identical.  It's copied to the extent that the bright spark has forgotten to take out the references to team colours and 5 faces - LineArc's skin has no team colours and only one face! (Your parser has obviously taken the info from the .int but what's in the .int doesn't match what's in the .utx). 

The .int is identical to the original even though LineArc's utx has a different name !!!  That means that the skin won't work in the sense it won't show up in the Player or Bot selection windows - it will work if the details are added manually in the relevant place (User.ini). 

So a botched job but also one that relies very heavily on, but does not credit, the original.

---
URL: https://unrealarchive.org/skins/unreal-tournament/I/ironman_29251d01.html
Hash: 29251d0199cedaf29e2e4b545e3ee574d972af36
Current name: IronMan

**Comment by shrimpza** [comment]
I've just flagged it as deleted, since it's broken and seems ripped off.
