### ISSUE TITLE
[Model] yodastar

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1022]
No really problems but 
1) The release date is the date I posted that model to UT99.org rather than the date it was originally released.  Of course it may have never been released before - I found it in an old map zip file - sometimes one does find the odd model, VP or weapons mutator in old zips from around c1999 - 2003  - perhaps they were meant to be bonus conent as it were. Given that it doesn't seem to have surfaced elsewhere then it may not have 'officially' released.

2) The image for the model does indeed show Yoda - however it is not accurate representation of what the model looks like - for that see the screenshot in this thread https://ut99.org/viewtopic.php?f=3&t=13765

---
URL: https://unrealarchive.org/models/unreal-tournament/Y/yodastar_35e1b953.html
Hash: 35e1b953f9e5882fa1cb170578288c8b34c53997
Current name: yodastar

**Comment by OjitroC** [comment]
Just looked at the code - this is a Half Life model by heulers olivier
Looks like it was converted to UT by meltdown

There's a date 2000 in the comments at the top of the code for the bot - the info above is from the comments at the top of the code for the player model

**Comment by shrimpza** [comment]
updated release and author
