### ISSUE TITLE
[Mutator] ManHack

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1027]
According to the readme, the author's name is  Johannes '[A|K]Leviathan' Sievert

---
URL: https://unrealarchive.org/mutators/unreal-tournament-2004/M/manhack_1fdbb40d.html
Hash: 1fdbb40dcbe56ca1298c54f51eea2cad874ef0ec
Current name: ManHack

**Comment by shrimpza** [comment]
updated
