### ISSUE TITLE
[Map] dm-quorll 01.029

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1034]
There's only one PlayerStart in the map - according to the readme it was an early version of the map - it's not playable as a DM as, apart from the single start, there are no pickups of any kind nor any lighting - just the basic textured layout - it's really more ot a Test map than anything else.

---
URL: https://unrealarchive.org/maps/unreal-tournament/deathmatch/Q/dm-quorll-01029_998b47a9.html
Hash: 998b47a9e32428bc3ef134a9cf08bd479a0a36bb
Current name: dm-quorll 01.029

**Comment by shrimpza** [comment]
updated
