### ISSUE TITLE
[Map] DM-Dust

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1039]
Despite the DM prefix, this is a CTF map - one of the screenshots shows a flag; the gametype in the levelinfo is Botpack.CTF; there are two flagbases in the map; there is an alternative route (navigation points) and there are defencepoints which are also associated with CTF. 

---
URL: https://unrealarchive.org/maps/unreal-tournament/deathmatch/D/dm-dust_f0a6095d.html
Hash: f0a6095d48b9be46cf084bbb3fdc167430a6f6ff
Current name: DM-Dust

**Comment by shrimpza** [comment]
updated
