### ISSUE TITLE
[Map] MH-HiSpeed

### ISSUE THREAD

**Issue by SeriousBuggie** [unreal-archive/unreal-archive-data#1041]
Your description here

Duplicate of https://unrealarchive.org/maps/unreal-tournament/monster-hunt/H/mh-hispeed_a7dd5b1e.html
---
URL: https://unrealarchive.org/maps/unreal-tournament/monster-hunt/H/mh-hispeed_721c98a0.html
Hash: 721c98a0bef3e0f2f218f6de19c192492a934660
Current name: MH-HiSpeed

**Comment by shrimpza** [comment]
updated
