### ISSUE TITLE
[Model] terminator

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1046]
The author of the original model (for Quake 2) is James Edwards (Gwot)

It was converted to UT by  thefreeman

thefreeman is also known as heulers.olivier (or should that be the other way around? that's taken from the email address) - converted a lot of models from Half Life and Quake versions to UT 

Infor from the readme.

---
URL: https://unrealarchive.org/models/unreal-tournament/T/terminator_3d1584e2.html
Hash: 3d1584e24c866c2e73dd7e26317251abca628d5b
Current name: terminator

**Comment by shrimpza** [comment]
updated
