### ISSUE TITLE
[Model] terminator

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1047]
The author of the original model (for Half-Life) is Lourens "ZERO" van Jaarsveld

It was converted to UT by thefreeman

Info from the readme
---
URL: https://unrealarchive.org/models/unreal-tournament/T/terminator_3b78430a.html
Hash: 3b78430a5fc56a34ffb6a782cc3ba8ce95e2ca52
Current name: terminator

**Comment by shrimpza** [comment]
updated
