### ISSUE TITLE
[Map] AS-olympics-solo

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1061]
Despite the AS prefix, this is not an AS map.  There is no AssaultInfo actor and no gametype set in the LevelInfo - in consequence the map starts as a DM map.  There are fortstandard actors but these don't show up in game.  There are five PlayerStarts.

The map consists, in part, of 'bits' of other maps (like Overlord).  It's hard to tell what it's purpose was - an unfinished AS map perhaps but one needs the translocator to move around cetain parts of it and the translocator is not available in AS.  So no idea really ... but it is not a functioning AS map, that much is certain. 

---
URL: https://unrealarchive.org/maps/unreal-tournament/assault/O/as-olympics-solo_8e3a4dd9.html
Hash: 8e3a4dd95502a5c4509a777173b10c0677bba19d
Current name: AS-olympics-solo

**Comment by NeonKnightOA** [comment]
We may need a category for Unfinished maps...

**Comment by OjitroC** [comment]
I have previously suggested that this 'type' of map is categorised as Test/Demo - not that bothered BUT ... (there's always a but) Unfinished is more difficult to define - what exactly does it mean?  To some people, quite a few maps out there could be described as unfinished. Personally, I would not be inclined to create too many categories overall and in particular where it is unclear what criteria are used to define them.

**Comment by NeonKnightOA** [comment]
Then I'll add it to Tests and Demos.

**Comment by NeonKnightOA** [comment]
There. I've moved it to Tests and Demos.
