### ISSUE TITLE
[Map] AS-SkaarjAttack!MSU

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1062]
This is a curious one - it is certainly set up as an AS map with Assault set as the gametype and an AssaultInfo actor included.  The assault is on a Skaarj ship containing over 100 Skaarj and assorted allies - the objective is to kill them all basically.  There is only attack, no provision is made for Players to act in defence (moreover if one changes team to Blue, one gets killed by the 'monsters') - so it is practically a MH map rather than an AS map - it is certainly not a fully functioning AS map. 

---
URL: https://unrealarchive.org/maps/unreal-tournament/assault/S/as-skaarjattackmsu_27c944e5.html
Hash: 27c944e58f8d37cc7427a80be1301a1156ee5702
Current name: AS-SkaarjAttack!MSU

**Comment by UnrealGGecko** [comment]
According to the readme, found in the other version here:
https://unrealarchive.org/maps/unreal-tournament/assault/S/as-skaarjattackmsu_d90dd6f7.html
This map was made for the Make Something Unreal contest in the early 2000s, so its understandable why the map isnt an MH map.Dont think MH was a thing back then.

**Comment by OjitroC** [comment]
That's interesting - wondered what MSU stood for - should have thought of the Make Something Unreal contest!!  

As an aside, often the alternative version(s) of a map are more complete in terms of required files or readmes for example

**Comment by NeonKnightOA** [comment]
Yep, most of the time MSU is short for Make Something Unreal Contest.

It may have been for that edition, however it clearly didn't made the cut: https://unreal.fandom.com/wiki/Make_Something_Unreal_Contest/2000

**Comment by NeonKnightOA** [comment]
I'm moving it to Tests and Demos by the moment.
