### ISSUE TITLE
[Map Pack] PHXMissionPack1

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1103]
This is a Single Player campaign (made up of three linked missions). Works in Unreal and UT99.

---
URL: https://unrealarchive.org/mappacks/unreal-tournament/mixed/P/phxmissionpack1_0e29334d.html
Hash: 0e29334dc875412691cd63de5e8453b095046ef6
Current name: PHXMissionPack1

**Comment by shrimpza** [comment]
Fixed
