### ISSUE TITLE
[Skin] Aqua

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1104]
The archive listed as a variation is something completely different and is not a variation on the Aqua Rumiko skin - rather it is a male Soldier skin (Soldier_Aqua.utx). So it should have its own separate page.

---
URL: https://unrealarchive.org/skins/unreal-tournament/A/aqua_25cb1bb2.html
Hash: 25cb1bb2facc86e195abee41716312245c76712f
Current name: Aqua

**Comment by OjitroC** [comment]
... and the screenshot of that skin should be removed from the top (underneath the Rumikos).

**Comment by shrimpza** [comment]
Removed variation, and fixed authors on both as well.
