### ISSUE TITLE
[Map] MH-[SP]TheWall

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1116]
This is an Unreal map and not UT - the presence of SP packages suggests as much and trying to summon some of the weapons from those packs in a UT map confirms this (they won't load, as they have the bool property bWeaponTossedOut which is missing in UT - a sure sign that the package only works in Unreal). 

There is an UT version of this map from Rubie on UA already (MH-[RTU]TheWall).

---
URL: https://unrealarchive.org/maps/unreal-tournament/monster-hunt/S/mh-spthewall_583e0780.html
Hash: 583e078018fd5caf2c022f2a56fdd50069f5c345
Current name: MH-[SP]TheWall

**Comment by shrimpza** [comment]
Updated
