### ISSUE TITLE
[Map Pack] EXU1 Repack

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1120]
This is a Single Player campaign for UT99, not Unreal - it requires ExcessiveUT and is best run with OldSkool.  Superceded by the EXU2 campaigns. 

---
URL: https://unrealarchive.org/mappacks/unreal/unknown/E/exu1-repack_cd36a64b.html
Hash: cd36a64bc0b9609c4a9b41ec8452a75893f322ef
Current name: EXU1 Repack

**Comment by shrimpza** [comment]
Updated. Also updated some other EXU campaigns to SP.
