### ISSUE TITLE
[Voice] James Bond Voice

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1126]
The author of this VP is not, perhaps unsurprisingly, s Previous Work but 
Steven King

He indicates he is known online as Undertaker.

The current name comes from this line in the readme - "Authors Previous Work" a heading of the section where the other VPs made by Steven King are listed. 

---
URL: https://unrealarchive.org/voices/unreal-tournament/J/james-bond-voice_da69fb69.html
Hash: da69fb69fd0af87f99fabd2cfa95f99d0fe5de0c
Current name: James Bond Voice

**Comment by shrimpza** [comment]
Updated
