### ISSUE TITLE
[Map] CTF-SkaarjFace

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1139]
Release Date: May 14, 2005
Source = Readme

---
URL: https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/S/ctf-skaarjface_3c884709.html
Hash: 3c884709935eca9ec515a70f8d06fb7ba5e4cc29
Current name: CTF-SkaarjFace

**Comment by NeonKnightOA** [comment]
Is the issue solved?
