### ISSUE TITLE
[Map] CTF-UPbg-SeriousScrabble

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1140]
Release Date: 09-07-07

Source = Readme

---
URL: https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/U/ctf-upbg-seriousscrabble_8a9b9925.html
Hash: 8a9b9925febb00e1540b0dfae524c81d50a3de1e
Current name: CTF-UPbg-SeriousScrabble

**Comment by NeonKnightOA** [comment]
Is the issue solved?

**Comment by OjitroC** [comment]
The date should be July 2007 - going by the readmes for other maps in UP's UPBG mapping contest.

**Comment by NeonKnightOA** [comment]
Ow, crap...

**Comment by NeonKnightOA** [comment]
Just for the record, the UA's internal files use the format yyyy-mm-dd.

**Comment by shrimpza** [comment]
Dates are fun :D
