### ISSUE TITLE
[Mutator] Monster Madness

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1141]
The author of this mod is  Meltdown

Source = Readme

---
URL: https://unrealarchive.org/mutators/unreal-tournament/M/monster-madness_9ef48479.html
Hash: 9ef4847972ce0a3f95d94984b6db9bf7a1aff93b
Current name: Monster Madness

**Comment by NeonKnightOA** [comment]
Is the issue solved?
