### ISSUE TITLE
[Mutator] SwapTool

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1143]
Interesting issue here - is it the release date or the creation date that is important?

In the code (the commented out heading) for the SwapTool mutator is the date 2/3/2005 - which would seem to be the creation date?

The Author of the mutator is Matt Miller a.k.a. T-Bone
Source = code for the mutator (in the commented out heading)

---
URL: https://unrealarchive.org/mutators/unreal-tournament-2004/S/swaptool_105ccd98.html
Hash: 105ccd98f9e1c4f9781c13a26f033841e1782bcb
Current name: SwapTool

**Comment by NeonKnightOA** [comment]
Is the issue solved?
