### ISSUE TITLE
Broken mirror URLs

### ISSUE THREAD

**Issue by shrimpza** [unreal-archive/unreal-archive-data#13]
Most mirror URLs are broken.

In particular, too much URL encoding has happened, breaking URLs containing ampersands and square brackets.

Example map: https://unrealarchive.org/maps/unreal-tournament/deathmatch/W/1/dm-whitedwarf_6aeb34f9.html

Original report at https://ut99.org/viewtopic.php?f=3&t=13189&start=45#p112466

**Comment by NeonKnightOA** [comment]
What about converting the problematic characters into their HTML equivalents when sanitizing the filenames?

For example, `]` would be `%5B` and `[` would be `%5D`.

**Comment by shrimpza** [comment]
Resolved. Seems I had stored most URLs already URL encoded, and when being displayed, it URL encoded them again, so they were double-encoded.

The fix involved actually encoding only my B2 URLs, and removing the additional encoding call when rendering pages, as well as a change to the `B2Store` which stores data and returns the stored URLs.

The fix applied to images as well, they seem to be fine.
