### ISSUE TITLE
[Mutator] Mutator Toolbox

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1333]
This is for UT99.

Author = Forsaken
Source = Readme

Odd that the game couldn't be detected?

---
URL: https://unrealarchive.org/mutators/unknown/M/mutator-toolbox_a67a6aa1.html
Hash: a67a6aa1449d11b0b4de4f1c9f6cf8057a9228c3
Current name: Mutator Toolbox

**Comment by NeonKnightOA** [comment]
Fixed in #1344
