### ISSUE TITLE
[Map] DM-XV-monsters-Brikby

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1374]
Doesn't there need to be some kind of separator in the author names - Moron EvilGrins looks awful and in fact the map was map by Moron and edited by EG

---
URL: https://unrealarchive.org/maps/unreal-tournament/xvehicles/D/dm-xv-monsters-brikby_f1dac569.html
Hash: f1dac56947cc47d13b82e6e3a573f0d544f6717b
Current name: DM-XV-monsters-Brikby

**Comment by NeonKnightOA** [comment]
As a matter of fact, this was the code.
```
name: "DM-XV-monsters-Brikby"
author: "Moron made · edited by EvilGrins"
```

Looks like that middle dot screws everything. The same happens with another maps. I'm sending a PR which fixes this.
