### ISSUE TITLE
[Model] Cobra

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1381]
I don't think Buggie was a joint author of this model? 

---
URL: https://unrealarchive.org/models/unreal-tournament/C/cobra_b42a69b4.html
Hash: b42a69b4ad0e38d4c38421400e8ff6240816327b
Current name: Cobra

**Comment by NeonKnightOA** [comment]
Weird, in the file I have it's properly credited to Dufusyte and not to Buggie.
