### ISSUE TITLE
[Model] Thrashball Locust

### ISSUE THREAD

**Issue by SoupGod** [unreal-archive/unreal-archive-data#1403]
Your description here
Skin doest work in game for me, model doesn't show up

---
URL: https://unrealarchive.org/models/unreal-tournament-2004/T/thrashball-locust_e4f3540e.html
Hash: e4f3540eb647dd026d4e48e595f3620f3c41ba98
Current name: Thrashball Locust

**Comment by shrimpza** [comment]
Cannot tech support content
