### ISSUE TITLE
[Map] VCTF-HangingGardens-Nightfall

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1427]
The authors of this map are  Andrew Czarnietzki and Nathaniel Rossol (_N_)
Source = Readme

---
URL: https://unrealarchive.org/maps/unreal-tournament-3/vehicle-ctf/H/vctf-hanginggardens-nightfall_16ff7c2f.html
Hash: 16ff7c2f23b5f6b94c111a5283b0bca268d5b195
Current name: VCTF-HangingGardens-Nightfall

**Comment by shrimpza** [comment]
Fixed
