### ISSUE TITLE
[Map Pack] WhiteWitchComplex

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1428]
The author of these maps is given as Various
however they are all by the same person - the only difference in the author name is that  "Jesse_The_Body" has underscores whilst  "Jesse The Body" does not.

Odd that the map pack or campaign does not contain the map with the title of the pack/campaign WhiteWitchComplex - my copy of this does.

---
URL: https://unrealarchive.org/mappacks/unreal-tournament/single-player/W/whitewitchcomplex_10b789fd.html
Hash: 10b789fda9e88186f20e9adda769087ac9568d59
Current name: WhiteWitchComplex

**Comment by shrimpza** [comment]
Author updated, can't do much about the missing content.

Also seems to miss a lot of required textures and other assets.
