### ISSUE TITLE
[Map] jwGrapple

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1429]
This is a Test/Demo map for a grapple (the jwGrapple).

The author is Jered Windsheimer (jwindy)
Source = Readme
---
URL: https://unrealarchive.org/maps/unreal/unknown/J/jwgrapple_ce32d07f.html
Hash: ce32d07f40c2653671d8be775a75e3cba6cb95c4
Current name: jwGrapple

**Comment by shrimpza** [comment]
Fixed
