### ISSUE TITLE
[Mutator] Adds music to XMP games. Change which tracks play by editing [XMPMusic.XMPMusic] entries in your U2XMP.ini file.

### ISSUE THREAD

**Issue by richardsondev** [unreal-archive/unreal-archive-data#1430]
The current name would be better suited as a description due to its length.
Would `XMPMusic` be a better fit for the name?

From the `XMPMusic.int` file `XMPMusic.XMPMusic` is used for the name:
```
[Public]
Object=(Class=Class,MetaClass=Engine.Mutator,Name=XMPMusic.XMPMusic,Description="Adds music to XMP games. Change which tracks play by editing [XMPMusic.XMPMusic] entries in your U2XMP.ini file.")
```

---
URL: https://unrealarchive.org/mutators/unreal-tournament-2004/A/adds-music-to-xmp-games-change-which-tracks-play-by-editing-xmpmusicxmpmusic-entries-in-your-u2xmpini-file_39d096f5.html
Hash: 39d096f55fa347ea9ca5b48024d512bc6c7266d7
Current name: Adds music to XMP games. Change which tracks play by editing [XMPMusic.XMPMusic] entries in your U2XMP.ini file.

**Comment by shrimpza** [comment]
Indeed, fixed. Also moved it to Unreal 2 section.

:+1:
