### ISSUE TITLE
[Map] War-TombOfAmunrah

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1437]
Player Count = 12-24
Source = Readme

The authors are not 's Notes (surprise!) but Simion (Oldskool0482) Korbra & Cryspy
Source = Readme

[As an aside, Cryspy is Bryan Crisp in the credits section of the readme]

---
URL: https://unrealarchive.org/maps/unreal-tournament-3/warfare/T/war-tombofamunrah_13e6ef87.html
Hash: 13e6ef87050c58ffdf5289bcc343d295dabad8c3
Current name: War-TombOfAmunrah

**Comment by shrimpza** [comment]
Fixed
