### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by yarow12** [unreal-archive/unreal-archive-data#1484]
I've attempted various words (e.g.: Chronos, DM, CTF, maps, voice) on the [search](https://unrealarchive.org/search/index.html) page and got no results. 
![Screenshot 2022-07-31 at 10-38-09 Search](https://user-images.githubusercontent.com/66401444/182036433-65f5a4e0-0498-4023-ae93-1fd93ecfb2da.png)

**Comment by shrimpza** [comment]
Search fixed
