### ISSUE TITLE
[Map] DM-{hPCM}-RatRace

### ISSUE THREAD

**Issue by UnrealGGecko** [unreal-archive/unreal-archive-data#1545]
all the new ut3 maps with the {hPCM} prefix are by Raphael "HardPCM" Couturier
https://unrealarchive.org/authors/raphael-_hardpcm_-couturier.html
source: readme and map descriptions

---
URL: https://unrealarchive.org/maps/unreal-tournament-3/deathmatch/H/dm-hpcm-ratrace_467f52a8.html
Hash: 467f52a816c49b50b1bff8cd8d90eea55d4b232c
Current name: DM-{hPCM}-RatRace

**Comment by shrimpza** [comment]
All updated
