### ISSUE TITLE
[Map] CTF-LP-Hostility

### ISSUE THREAD

**Issue by SeriousBuggie** [unreal-archive/unreal-archive-data#1546]
Duplicate of https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/L/ctf-lp-hostility_0e149979.html

---
URL: https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/L/ctf-lp-hostility_333578cf.html
Hash: 333578cf775b78d2ecb18c0b3ecbdbd34ade8a3d
Current name: CTF-LP-Hostility

**Comment by shrimpza** [comment]
Fixed
