### ISSUE TITLE
[Map] CTF-SpoondogBME

### ISSUE THREAD

**Issue by SeriousBuggie** [unreal-archive/unreal-archive-data#1548]
If click on author:
https://unrealarchive.org/authors/cory-spooner-_thespoondog_.html
Then map CTF-SpoondogBME not appear in list.

---
URL: https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/S/ctf-spoondogbme_6bc6ac3a.html
Hash: 6bc6ac3a09e403338ba6dca63043dd646324e698
Current name: CTF-SpoondogBME

**Comment by shrimpza** [comment]
Fixed, his Author page should include more stuff now: https://unrealarchive.org/authors/cory-spooner-_thespoondog_.html
