### ISSUE TITLE
[Map] DM-EgyptianArena[remix]

### ISSUE THREAD

**Issue by danarchitect** [unreal-archive/unreal-archive-data#1550]
Dear Sir/Madam,

I am Danilo Di Mascio and this is not one of my old levels. Could you please delete the file or change the author's name?

Thank you for your kind attention.

Kind regards,
Danilo

---
URL: https://unrealarchive.org/maps/unreal-tournament/deathmatch/E/dm-egyptianarenaremix_b890f66b.html
Hash: b890f66b21e74b521a3c7708a208f5634224bc32
Current name: DM-EgyptianArena[remix]

**Comment by shrimpza** [comment]
Fixed
