### ISSUE TITLE
[Map] CTF-Crater

### ISSUE THREAD

**Issue by danarchitect** [unreal-archive/unreal-archive-data#1551]
Dear Sir/Madam,

I am Danilo Di Mascio and this is not one of my old levels. Could you please delete the file or change the author's name?

Thank you for your kind attention.

Kind regards,
Danilo

---
URL: https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/C/ctf-crater_cb373e1b.html
Hash: cb373e1b727c2d9d6acbee3b0bd38d3bfd916f09
Current name: CTF-Crater

**Comment by shrimpza** [comment]
Fixed
