### ISSUE TITLE
[Map] DM-EgyptianArena

### ISSUE THREAD

**Issue by danarchitect** [unreal-archive/unreal-archive-data#1552]
Dear Sir/Madam,

I am Danilo Di Mascio and this is not one of my old levels. Could you please delete the file or change the author's name?

Thank you for your kind attention.

Kind regards,
Danilo

---
URL: https://unrealarchive.org/maps/unreal-tournament/deathmatch/E/dm-egyptianarena_c34a0c2b.html
Hash: c34a0c2b53d49780e1560977861c10765824246d
Current name: DM-EgyptianArena

**Comment by shrimpza** [comment]
Fixed
