### ISSUE TITLE
[Map] DM-HugeBedroom

### ISSUE THREAD

**Issue by danarchitect** [unreal-archive/unreal-archive-data#1554]
Dear Sir/Madam,

I am Danilo Di Mascio and this is not one of my old levels. Could you please delete the file or change the author's name?

Thank you for your kind attention.

Kind regards,
Danilo

---
URL: https://unrealarchive.org/maps/unreal-tournament/deathmatch/H/dm-hugebedroom_acb6f277.html
Hash: acb6f27731baf84164a7f28699eacdc10eb9787a
Current name: DM-HugeBedroom

**Comment by UnrealGGecko** [comment]
Yea the author in the map file is just called "Dan", so it might've auto labeled as one of yours. Doesn't seem like it's because of this: https://github.com/unreal-archive/unreal-archive-data/tree/master/authors

**Comment by shrimpza** [comment]
Yes, it's been auto labelled incorrectly, and is not actually related to you.

It took your author name, "Danilo 'Dan' Di Mascio" and automatically assumed maps by "Dan" were also you.

So the problem is not with the maps but with the auto-aliasing implementation. I will correct this.

**Comment by danarchitect** [comment]
Thank you for your support.

Kind regards,
Danilo

**Comment by shrimpza** [comment]
These should all now be corrected.

Dan's maps: https://unrealarchive.org/authors/dan.html

Danilo 'Dan' Di Mascio's maps: https://unrealarchive.org/authors/danilo-_dan_-di-mascio.html

These are all credited to Dan, and not Danilo 'Dan' Di Mascio:

- https://unrealarchive.org/maps/unreal-tournament/deathmatch/E/dm-egyptianarenaremix_b890f66b.html
- https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/C/ctf-crater_cb373e1b.html
- https://unrealarchive.org/maps/unreal-tournament/deathmatch/E/dm-egyptianarena_c34a0c2b.html
- https://unrealarchive.org/maps/unreal-tournament/deathmatch/T/dm-thematrix_feb6e0d3.html
- https://unrealarchive.org/maps/unreal-tournament/deathmatch/H/dm-hugebedroom_acb6f277.html
