### ISSUE TITLE
[Author] putting the edited readme

### ISSUE THREAD

**Issue by UnrealGGecko** [unreal-archive/unreal-archive-data#1561]
Not sure where it's getting this as the author: https://unrealarchive.org/authors/putting-the-edited-readme.html

Real author list: 

DM-Dualistic by Scott 'Pudd' Fowler  https://unrealarchive.org/maps/unreal-tournament/deathmatch/D/dm-dualistic_049f8836.html 
DM-lucifixpitt by Terry 'lucifix' Miller https://unrealarchive.org/maps/unreal-tournament/deathmatch/L/dm-lucifixpitt_bf2d363f.html
DM-lucifixsatlantisfinal by Terry 'lucifix' Miller https://unrealarchive.org/maps/unreal-tournament/deathmatch/L/dm-lucifixsatlantisfinal_48beeeca.html
DM-outworld by Terry 'lucifix' Miller https://unrealarchive.org/maps/unreal-tournament/deathmatch/O/dm-outworld_958af9d1.html
DM-shotinthedark by Terry 'lucifix' Miller https://unrealarchive.org/maps/unreal-tournament/deathmatch/S/dm-shotinthedark_4ead6beb.html
DM-skyzone by Mike 'chaosz23' really don't want to give my last name https://unrealarchive.org/maps/unreal-tournament/deathmatch/S/dm-skyzone_04753e11.html (also can change release date, according to readme, to September 27, 2001)
DM-toberus by John 'Rukee' https://unrealarchive.org/maps/unreal-tournament/deathmatch/T/dm-toberus_09a69588.html

Source: readme's.
---

**Comment by shrimpza** [comment]
Great thanks. All updated.
