### ISSUE TITLE
[Map] DM-Checkmate_v-=CoN=-

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1568]
The download link from http://ut99maps.gamezoo.org  resolves to the website and NOT to the file/zip.

---
URL: https://unrealarchive.org/maps/unreal-tournament/deathmatch/C/dm-checkmate_v-con-_f332ff85.html
Hash: f332ff850ec745483a85f88e94823fbd6ec679be
Current name: DM-Checkmate_v-=CoN=-

**Comment by NeonKnightOA** [comment]
It's also a dead site link. Removing.
