### ISSUE TITLE
[Map] DM-(ASC)Checkmate

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1569]
There isn't really any Bot/AI support in this map - there are no pathnodes - there are, of course, paths between InventorySpots but that's all.  As the author says in the Readme, it's a snipers map with the implication that it is intended only for humans.

---
URL: https://unrealarchive.org/maps/unreal-tournament/deathmatch/A/dm-asccheckmate_707ce3d9.html
Hash: 707ce3d9eaf73c92f6fa96217a9b1cf32a2ef024
Current name: DM-(ASC)Checkmate

**Comment by shrimpza** [comment]
Updated
