### ISSUE TITLE
[Map Pack] Cwl Maptestingpack Wk98

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1720]
This isn't an Unreal Map Pack - all of the maps are for UT99.

---
URL: https://unrealarchive.org/mappacks/unreal/mixed/C/cwl-maptestingpack-wk98_f471fc54.html
Hash: f471fc5487f76100428fbdde353f99815cda6bdb
Current name: Cwl Maptestingpack Wk98

**Comment by shrimpza** [comment]
Fixed
