### ISSUE TITLE
[Map] ons-BareBones

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1721]
Not an Unreal map - the map file type is .ut2.

---
URL: https://unrealarchive.org/maps/unreal/onslaught/B/ons-barebones_68cd6e2d.html
Hash: 68cd6e2d9bcad438c6219dc5689bd2187fd0a9f4
Current name: ons-BareBones

**Comment by shrimpza** [comment]
>  Release (est): January 1980 

:joy: 

It thought based on age it could only be Unreal :).

Thanks, fixed.
