### ISSUE TITLE
[Map] DM-Mapname

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#1731]
No idea what exactly happened here, but seems like system failed to recognize map info.

---
URL: https://unrealarchive.org/maps/unreal-tournament-3/vehicle-ctf/D/dm-mapname_fe155bbf.html
Hash: fe155bbfad937717299af58207fa88e748c6e2fc
Current name: DM-Mapname

**Comment by shrimpza** [comment]
According to the included map info:

```
[VCTF-COD UTUIDataProvider_MapInfo]
MapName=DM-Mapname
FriendlyName=Mapname
```

But I changed it to VCTF-COD manually.
