### ISSUE TITLE
[Model] Ubersoldat

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#1732]
Despite sharing a similar name, those two models are not variations of each-other and have been ported from completely different games (Return to Castle Wolfenstein and Wolfnestein The New Order).

---
URL: https://unrealarchive.org/models/unreal-tournament-2004/U/ubersoldat_4785bfd3.html
Hash: 4785bfd3d5c5678c3fa53e45e730b7052163c73f
Current name: Ubersoldat

**Comment by shrimpza** [comment]
Unset variation
