### ISSUE TITLE
[Map] DM-Awoken

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#1741]
The author of this map is Zanieon. More info about the map can be found on it's [ModDB page](https://www.moddb.com/games/unreal-tournament-3/addons/awoken)

---
URL: https://unrealarchive.org/maps/unreal-tournament-3/deathmatch/A/dm-awoken_7cce285e.html
Hash: 7cce285ee5a902332a5b38084f408c15ac04f3a1
Current name: DM-Awoken

**Comment by shrimpza** [comment]
Updated author and added the ModDB link
