### ISSUE TITLE
[Map] DM-HellsGate

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#1791]
I want to ask to unset variations of this map. One is modded, while the other is the original. There should be enough differences between the two, think of them as 1.0 and SE versions, like some other UT maps have.

---
URL: https://unrealarchive.org/maps/unreal-tournament-3/deathmatch/H/dm-hellsgate_906fe98f.html
Hash: 906fe98f1a83bc9a4d501468de95f6f7b70284ac
Current name: DM-HellsGate

**Comment by shrimpza** [comment]
Done
