### ISSUE TITLE
[Map Pack] 3dbuzz Osld Top5

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#1812]
System doubled the amount of maps in the pack, listing them twice (most likely due to each individual map being in a separate archive). There are only 5 maps total, as evident by the name.

---
URL: https://unrealarchive.org/mappacks/unreal-tournament-3/deathmatch/0/3dbuzz-osld-top5_49c17dd0.html
Hash: 49c17dd0e238c21c851ea55c5f4d20a1aabe1a71
Current name: 3dbuzz Osld Top5

**Comment by shrimpza** [comment]
Fixed
