### ISSUE TITLE
[Map] DM-Liandri-Classic

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#1832]
I want to ask to unset variations of this map. One is made to replicate the classic look and feel of it's UT99 version (hence the "Classic" suffix), while the other is made to be in line with UT3 more modern maps.

---
URL: https://unrealarchive.org/maps/unreal-tournament-3/deathmatch/L/dm-liandri-classic_c5f76c72.html
Hash: c5f76c72b396765c50e4d4ed64b33358f6326544
Current name: DM-Liandri-Classic

**Comment by shrimpza** [comment]
makes sense, unset variation
