### ISSUE TITLE
[Map Pack] Ut 2004 Ctf Jap Corepack

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#1833]
Like with 3dbuzz Osld Top5 UT3 map pack previously, system doubled the amount of arenas in the pack, listing them twice. Seems like it's an overarching problem with all archives within archives with maps. There are only 3 levels total.

---
URL: https://unrealarchive.org/mappacks/unreal-tournament-2004/capture-the-flag/U/ut-2004-ctf-jap-corepack_f8eefed1.html
Hash: f8eefed11555f86adcdf4ed9faf103a8a623d399
Current name: Ut 2004 Ctf Jap Corepack

**Comment by shrimpza** [comment]
Fixed map, not yet fixed bug.
