### ISSUE TITLE
[Skin] (G)Nercris

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#1870]
The author is Michael Toomey a.k.a (G)DarkPsycho
Age : 14
Source : Readme

---
URL: https://unrealarchive.org/skins/unreal-tournament/G/gnercris_efb25a2e.html
Hash: efb25a2e553115f3a38758bf06b4abf82ffbe10f
Current name: (G)Nercris

**Comment by shrimpza** [comment]
Fixed
