### ISSUE TITLE
[Model] jason_cecrle_bitterpill

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#1908]
Name of this model should be changed to Jagoreth. Current one is taken from the archive, which is author's name (Jason Cecrle BitterPill).

---
URL: https://unrealarchive.org/models/unreal-tournament-3/J/jason_cecrle_bitterpill_82485c7f.html
Hash: 82485c7fb1f1d6e9d5589118847bd18bb9f78d7b
Current name: jason_cecrle_bitterpill

**Comment by shrimpza** [comment]
Fixed
