### ISSUE TITLE
[Model] pcgrannysnake

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#1910]
Name of the model should be changed to it's in-game name (Old Snake). The author of this model is genZ.

---
URL: https://unrealarchive.org/models/unreal-tournament-3/P/pcgrannysnake_7058159e.html
Hash: 7058159e8948e1c4e74e93fb87ffc4663f21db79
Current name: pcgrannysnake

**Comment by shrimpza** [comment]
Fixed
