### ISSUE TITLE
Vohzd mirror appears down

### ISSUE THREAD

**Issue by richardsondev** [unreal-archive/unreal-archive-data#1940]
For the last week or so the vohzd mirror has been returning 404s with a "Nothing here yet" page
Example:
https://unrealarchive.org/skins/unreal-tournament-2004/B/battlewarrior_8d0b676d.html

**Comment by vohzd** [comment]
Hallo, thanks for reminding me about this! My server had a broken SSD recently, and I simply forgot to put the mirror back online!

I'll bring it all back online in a couple of days.

Thanks for bearing with!

**Comment by shrimpza** [comment]
Looks like the mirror's back, thanks @vohzd :+1:
