### ISSUE TITLE
[Mutator] MultiDodgeJump

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2010]
I want to ask to unset those two mutators. They serve different movement functions: one aims to bring back UT2004-esque dodge-jump technique and the other is to allow players to chain multiple wall dodges.

---
URL: https://unrealarchive.org/mutators/unreal-tournament-3/M/multidodgejump_5c9b7aca.html
Hash: 5c9b7aca3feabe9726b20e8423149f0a80cae28a
Current name: MultiDodgeJump

**Comment by shrimpza** [comment]
Fixed
