### ISSUE TITLE
Best way to provide mirror URLs?

### ISSUE THREAD

**Issue by vohzd** [unreal-archive/unreal-archive-data#205]
Hello, love the project!

Came across this whilst trying to find a reliable source of UT files.

I have a crapton of space available on my Wasabi.com account, and would like to help mirror the entire content.

I'm curious if you have any tips on how I can bulk edit the yaml files to add my mirrored URLs in a pull request?

I don't mind doing manually, but might take some time!

Cheers,
Ben

**Comment by shrimpza** [comment]
Hey, thanks for the interest and offer :). 

Unfortunately, there's no common or friendly way to set up an actual mirror and update all the data with that new mirror at the moment (and to keep it up to date).

The only option right now is for you to clone the data repo, load up the YAML data and download the files, upload them to your storage, and write a new entry into the `download` list of each (being careful to not disrupt the existing data :joy:). Then open a PR with all the changes.

Depends how adventurous you're feeling.

However, I see that Wasabi uses the AWS S3 API, and the S3 API is probably a storage backend which should be supported anyway, so I'm going to implement that into the `unreal-archive` binary so we can more easily sync files to mirrors on that API and manage updating all the YAML etc.

**Comment by shrimpza** [comment]
Tracking work on this in unreal-archive/unreal-archive#34 and unreal-archive/unreal-archive#35.

**Comment by vohzd** [comment]
Ace! Thank you for working on this, look forward to testing it out !

**Comment by shrimpza** [comment]
@vohzd Hopefully a working solution is now in place. See Mirroring section of the README: https://github.com/unreal-archive/unreal-archive#mirroring

I hope it makes sense.

You can download the latest binary from here: https://code.shrimpworks.za.net/artefacts/unreal-archive/latest/ (the one without an extension can just be made executable and invoked directly). Requires Java 11.

For Wasabi, the following parameters should be used:

```
./unreal-archve mirror \
  --store=s3 \
  --s3-bucket=bucket-name \
  --s3-key=YOURKEY \
  --s3-secret=YOURSECRET \
  --s3-endpoint=https://s3.BUCKET-REGION.wasabisys.com/ \
  --s3-url=https://s3.BUCKET-REGION.wasabisys.com/__BUCKET__/__NAME__
```

It won't download to intermediate files on your machine, so you don't need to make sure you have > 200gb of local space.

When it's all mirrored, just create a PR from your fork of the data repo and everything should be cool.

**Comment by vohzd** [comment]
Hello @shrimpza Thanks & fantastic work on this. 

All installed fine, and the sync is chucking along without issues.

I expect it to take a while before I raise a PR, but will give you a shout when complete.

From spot checking a few and re-downloading them, they seem to be publicly accessible and uncorrupted.

Will give a more thorough test soon.

Cheers!

**Comment by vohzd** [comment]
@shrimpza I've created a PR for this here:
https://github.com/unreal-archive/unreal-archive-data/pull/211

**Comment by shrimpza** [comment]
That's awesome! Thanks!

Before I merge it and it goes public, just wondering if you want me to add a hostname mapping to some sort of site name or something, or if it's cool as-is. For example, by default your links will appear as follows:

![image](https://user-images.githubusercontent.com/6191747/78915749-b04bf700-7a8c-11ea-8d79-d631bf209c8b.png)

Can be "Vohzd's Mirror" or anything, or we can leave it.

**Comment by vohzd** [comment]
Interesting question, I got into UT under the name 'Sabre', but prefer 'Vohzd' as that what I'll be putting new stuff out under... so to answer your question... put it under 'Sabre' as that's what everyone will remember me as!

You're doing a grand service dude, thank you very much for building this!

**Comment by shrimpza** [comment]
Done!

Mirror name remapped, and the mirror is now listed on the downloads.

Thank you for contributing to keeping all this old stuff available for a bit longer :).

I'm going to also add a `--since=2020-04-01` type syntax to the mirror command, so if you or anyone else ever feels the urge to sync up new stuff, the option will be available.

**Comment by shrimpza** [comment]
New option was added per above (see readme), so mirroring new content should be easy too.

Closing this issue as hopefully mirroring is now resolved (aside from new storage implementations which might need to be added later).

:+1:
