### ISSUE TITLE
[Model] Claire Redfield

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2055]
Website failed to detect the rest of the models in this pack (Chris, Jill, Leon). Author of the pack is tidel, here's the original EGF thread for reference:  https://forums.epicgames.com/unreal-tournament-2003-2004/user-maps-mods/beta-releases/270941-model-resident-evil-beta1

---
URL: https://unrealarchive.org/models/unreal-tournament-2004/C/claire-redfield_9623533e.html
Hash: 9623533e2b72cc1be305199fe6a59ac40fae6682
Current name: Claire Redfield

**Comment by shrimpza** [comment]
Updated models, author, and renamed.
