### ISSUE TITLE
[Map] VCTF-TheGate_HED

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2116]
This map was made for the Greed gamemode only. Author states so in the readme file, that can be found in map's archive.

---
URL: https://unrealarchive.org/maps/unreal-tournament-3/vehicle-ctf/T/vctf-thegate_hed_fed09fb1.html
Hash: fed09fb18561df6f020dd81a0ab06f84b0181a8e
Current name: VCTF-TheGate_HED

**Comment by shrimpza** [comment]
Updated
