### ISSUE TITLE
[Map] CTF-GRD_Observatory

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2135]
This map is for the Greed gamemode and should be moved to the appropriate section.

---
URL: https://unrealarchive.org/maps/unreal-tournament-3/capture-the-flag/G/ctf-grd_observatory_bf4f567d.html
Hash: bf4f567d1aa3c8dbff889afb924c9a445670293d
Current name: CTF-GRD_Observatory

**Comment by shrimpza** [comment]
Updated, and changed GRD- detection to just GRD.
