### ISSUE TITLE
[Model] Kitty

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2148]
I want to ask to unset variations of this model. They have the same name, but models themselves are completely different: the main one is a furry, and the other is human (an old female spy model by Warbeast).

---
URL: https://unrealarchive.org/models/unreal-tournament-2004/K/kitty_b3304063.html
Hash: b3304063ae383ce28245cd7a7f7ca7ed54085f4c
Current name: Kitty

**Comment by shrimpza** [comment]
Unset variation
