### ISSUE TITLE
[Model] Alien

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2149]
I want to ask to unset variations of this model. One is iconic Xenomorph with it's own faction and the other is (supposedly) original by the name of Space Alien Hunter that gets added to Ironguard.

---
URL: https://unrealarchive.org/models/unreal-tournament-3/A/alien_d1cc19ec.html
Hash: d1cc19ec8937083c0b8522f7fd85cd676b214889
Current name: Alien

**Comment by shrimpza** [comment]
Unset variation
