### ISSUE TITLE
[Model] Unreal Male 1: Kurgan

### ISSUE THREAD

**Issue by Aldarith2** [unreal-archive/unreal-archive-data#2159]
Miscategorized / incorrectly flagged

"Unreal 1 Characters Pack" is probably a more appropriate name?

---
URL: https://unrealarchive.org/models/unreal-tournament/N/new-nali_36fe473b.html
Hash: 36fe473bb12e78db03548b3296210795f2c94735
Current name: New Nali

**Comment by shrimpza** [comment]
Renamed, although the actual name is "BDSM Cows" according to the readme, by author "HOT_BEEF_INJECTION aka BEEF_JERKY".

The other images seem to be due to bad packaging, it's not supposed to be an Unreal character pack.
