### ISSUE TITLE
[Model] Male-EcoTerrorist

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2180]
The author is BurntKona

Source = Screenshot

---
URL: https://unrealarchive.org/models/unreal-tournament/M/male-ecoterrorist_d2fda6c4.html
Hash: d2fda6c452ca92013ce0597170c9d3e60e743e07
Current name: Male-EcoTerrorist

**Comment by shrimpza** [comment]
Fixed
