### ISSUE TITLE
[Mutator] DSP_Mutator

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2187]
The author of this mutator (sadly no longer with us and much missed as a prolific and humourous contributor on UT99.org) is  MrLoathsome

Source : the mutator Readme

---
URL: https://unrealarchive.org/mutators/unreal-tournament/D/dsp_mutator_b2a16881.html
Hash: b2a16881aa3fb0e89ad28a6089b8507f59048700
Current name: DSP_Mutator

**Comment by shrimpza** [comment]
:cry: 

Fixed
