### ISSUE TITLE
[Model] Conni

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2188]
This is miscategorised as a single model - in fact it is a model and skin pack with loads of models .

I doubt the stated author is actually the author of any of the models (cetainly of the ones I am familiar with which is most/all of them) though possibly of a skin or two.

---
URL: https://unrealarchive.org/models/unreal-tournament/C/conni_cea5d71d.html
Hash: cea5d71dcf1d36195bb88fc0851001fa754168e6
Current name: Conni

**Comment by shrimpza** [comment]
Judging by an image included, along with the filename, it seems to be the "Skincity Best of UT Model Pack".

https://unrealarchive.org/file/unreal-archive-images/Unreal%20Tournament/Models/C/Conni_shot_8.png

Renamed and change author to "Various" which is in line with map packs.
