### ISSUE TITLE
Missing Unreal Archive EU mirrors for UT3 The Haunted maps

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2192]
Newly added [maps for The Haunted UT3 mod](https://unrealarchive.org/maps/unreal-tournament-3/the-haunted/index.html) lack Unreal Archive EU mirrors, while other UT3 maps uploaded around the same time have them.

**Comment by PootisKorn** [comment]
It's been quite a while, so I should probably specify that only the following maps have no Unreal Archive EU mirrors:

[TH-FacingWorlds](https://unrealarchive.org/maps/unreal-tournament-3/the-haunted/F/th-facingworlds_ee43ccc2.html)
[TH-Bayou](https://unrealarchive.org/maps/unreal-tournament-3/the-haunted/B/th-bayou_ecaeb419.html)
[TH-LightHouse](https://unrealarchive.org/maps/unreal-tournament-3/the-haunted/L/th-lighthouse_a626f755.html)

**Comment by shrimpza** [comment]
All fixed :)
