### ISSUE TITLE
[Map] DM-KTSN-AirPurificationComplex

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2205]
For some reason the meshes included in the zip are not being detected and are listed as missing.

That seems to be the case with all 3 of the DM-KTSN maps from Rikia.  

I've downloaded, installed and played all 3 and there are certainly no missing files - I can't be sure that each zip contains all the required files but certainly installing all three ensures one has all the required files.  In none of the Required FIles lists for these maps do the meshes (*.usm) appear.

---
URL: https://unrealarchive.org/maps/unreal/deathmatch/K/dm-ktsn-airpurificationcomplex_b036f3d0.html
Hash: b036f3d026c058ddd25b0646e81476d9db6e4416
Current name: DM-KTSN-AirPurificationComplex

**Comment by shrimpza** [comment]
Interesting, I haven't seen USM files before, where do they come from, is it a OldUnreal patch feature?

**Comment by shrimpza** [comment]
OK, I found that `.usm` files are indeed a thing added to Unreal 227(g?).

Added support to those in dependency resolution and file listings.
