### ISSUE TITLE
[Map] DM-LoTrapTest

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2210]
The main attraction of this file is LoTrap Gun mutator, that mimics Portal Gun from Valve's famous game. The map is just a testing playground. I recommend reindexing this archive.

---
URL: https://unrealarchive.org/maps/unreal-tournament-3/deathmatch/L/dm-lotraptest_d8af2788.html
Hash: d8af27885d010e841427ed83ef2ee2470b59c650
Current name: DM-LoTrapTest

**Comment by NeonKnightOA** [comment]
Reassigning this to the Tests and Demos section.
