### ISSUE TITLE
[Map Pack] RumpleMiniPack

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2228]
A familiar bug happened to this map pack, that doubled displayed amount of content due to .zip files inside a .zip file.

---
URL: https://unrealarchive.org/mappacks/unreal-tournament-2004/vehicle-ctf/R/rumpleminipack_0b2e17c8.html
Hash: 0b2e17c8261aa7dfe13c444299b37a4ed4700156
Current name: RumpleMiniPack

**Comment by shrimpza** [comment]
Fixed
