### ISSUE TITLE
[Map] MH-Back-Alley

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2253]
This one is a bit odd.  

A mapper with 20 years experience should know better than to produce a texture file called MyLevel.utx??!!!

It seems that the only way to play the map is with a key code obtainable from the mapper - to do that one has to send an email - is that appropriate?  Should one have to give one's email address to someone else when one may not want to or know what they might do with it?? I have never come across that before - why does the mapper not want the map to be freely available??

---
URL: https://unrealarchive.org/maps/unreal-tournament/monster-hunt/B/mh-back-alley_7b46d1d5.html
Hash: 7b46d1d5f458c887ba9e1ff37ca1a8569ca29cfe
Current name: MH-Back-Alley

**Comment by shrimpza** [comment]
Agreed, it's very odd. Almost seems not worth hosting/archiving if it's intentionally gimped by some ill-conceived attempt at "licencing" or "DRM".

**Comment by OjitroC** [comment]
Actually the so-called KeyCode (which is an assault rifle) is now available in one of this person's other MH maps so this map is now playable (well up to a point).

It seems to me the only reason XVehicles are in the map is so the ScriptedPawns can use the projectiles from the tanks - Brutes with 5K health firing the projectile from the large tank which does 3.8k damage and this in narrow passageways with the map shaking from the impact of the projectiles is but one example!!
