### ISSUE TITLE
[Mutator] Unreal Tournament 2341

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2256]
[Unreal Tournament 2341](https://unrealarchive.org/mutators/unreal-tournament-2004/U/unreal-tournament-2341_adde358c.html), [UT2341 Beta2](https://unrealarchive.org/mutators/unreal-tournament-2004/U/ut2341-beta2_7b78b88a.html) and [UT2341 BETA3](https://unrealarchive.org/mutators/unreal-tournament-2004/U/ut2341-beta3_6536b1ec.html) should all be merged, with Beta 3 being the main variation. [Here is ModDB link](https://www.moddb.com/mods/ut2341-hd-arsenal) for reference.

---
URL: https://unrealarchive.org/mutators/unreal-tournament-2004/U/unreal-tournament-2341_adde358c.html
Hash: adde358c4e5d3b182256ac73b9910ddb10c45b70
Current name: Unreal Tournament 2341

**Comment by shrimpza** [comment]
Updated variations and names, added ModDB link
