### ISSUE TITLE
Broken Unreal Archive EU mirrors

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2257]
Mirrors since [2022-12-05 on 2022-12-25](https://github.com/unreal-archive/unreal-archive-data/commit/e081ebf31dade67db4097d7754f2728d3f18d7ff) for some files are busted. XML error, but only for some. [An example](https://unrealarchive.org/models/unreal-tournament-2004/U/unreal-ii-heavy-skaarj_ed31bc98.html).

**Comment by shrimpza** [comment]
Thanks for the report, please try again, I think its fixed now.

**Comment by PootisKorn** [comment]
Yup, seems all good now.
