### ISSUE TITLE
[Model] Genestealer

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2276]
The author of the original model is Slightly Twisted
(yes, that's a name - joke!) 
It was animated for Slightly Twisted by OmegaLE - model made for Half Life

Converted to UT by X3M

Source : Readme.

---
URL: https://unrealarchive.org/models/unreal-tournament/G/genestealer_b419d117.html
Hash: b419d1174cf1886976e4b65a35e2b4a59e650bb7
Current name: Genestealer

**Comment by shrimpza** [comment]
Updated. Maybe not ideal but credits the people: "Slightly Twisted, OmegaLE, conversion by X3M"
