### ISSUE TITLE
CTF-Narrow-by-Jihan   (content-bug)

### ISSUE THREAD

**Issue by osminogig** [unreal-archive/unreal-archive-data#2278]
**Four files have the same hash.**

https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/N/ctf-narrow-by-jihan_222c03ca.html

**Comment by shrimpza** [comment]
Unfortunately, this seems to be an error on the part of the author, as they have duplicated the same file multiple times for some reason:

![image](https://user-images.githubusercontent.com/6191747/212312334-390934fc-044e-4773-89af-5e226dc1c374.png)
