### ISSUE TITLE
CTF-Spiralwar_by_Jihan  (content-bug)

### ISSUE THREAD

**Issue by osminogig** [unreal-archive/unreal-archive-data#2279]
Two files have the same hash.
.unr file ok!
---
URL: https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/S/ctf-spiralwar_by_jihan_3485304e.html
Hash: 3485304eeaa35a72173d5e0720de06eb1645c2e1
Current name: CTF-Spiralwar_by_Jihan

**Comment by osminogig** [comment]
Another joke, searches on unrealarchive.org return no results for Spiralwar !)

**Comment by shrimpza** [comment]
As with #2278 , seems the author duplicated and renamed the same file twice for some reason:

![image](https://user-images.githubusercontent.com/6191747/212313167-dcacea3a-dc15-4bef-b3fc-f4e56c3b01c0.png)
