### ISSUE TITLE
[Voice] Halo 4

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2281]
Not a VP per se but an Announcer - should be under Mutators perhaps? 

---
URL: https://unrealarchive.org/voices/unreal-tournament-2004/H/halo-4_a8c39676.html
Hash: a8c3967653e01ac5543c110de15a379c1a289de8
Current name: Halo 4

**Comment by shrimpza** [comment]
Hmm. I left it under Voices for the moment, but renamed to proper "Halo 4 Announcer", and set the author.
