### ISSUE TITLE
[Map] DM-SUPERNOVA

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2298]
The author of this map is  STEPHAN BELZILE    <NECRONOMACON>
Source : Readme (plus the map description/title)

---
URL: https://unrealarchive.org/maps/unreal-tournament/deathmatch/S/dm-supernova_2e26f8d4.html
Hash: 2e26f8d4f4398860b31e4d11798b91b3ebcb66b8
Current name: DM-SUPERNOVA

**Comment by OjitroC** [comment]
That's odd - the author name I put in has been truncated - it was NECRONOMACON enclosed by < >

**Comment by shrimpza** [comment]
Updated to `STEPHAN BELZILE <NECRONOMACON>`
