### ISSUE TITLE
Mapper name on a few missing one

### ISSUE THREAD

**Issue by NBKNiX** [unreal-archive/unreal-archive-data#230]
Mapper: -]NBK[-^NiX* on the following maps:
DM-]NBK[-HastesBasement
DM-]NBK[-ImmortalsTown
DM-{ESG}RoomInSniperTown
DM-{ESG}Seyne
DM-{ESG}SeyneV2
DM-{ESG}SniperHouseV2
DM-{ESG}Warehouse
DM-{ESG}Chernobyl(Final)
DM-{ESG}CondoRMX
DM-{ESG}CyberCUP2015
DM-{ESG}CyberCUP2015(remix)
DM-{ESG}HasteCamp-]NBK[-CUP2017
DM-[LAGG]MountainCity

---
Hash: 121ce4f29f5fa892a6793399d62a519c5207c624
Current name: DM-]NBK[-HastesBasement

**Comment by shrimpza** [comment]
@NBKNiX Did you also submit these, and are they also supposed to be attributed to you?

https://github.com/unreal-archive/unreal-archive-data/pull/231

They've all come through with no author information, screenshots or player count information. I'll update them before I add them.

For future maps remember to fill out the level properties with the author, that's where Unreal Archive gets them from.

**Comment by NBKNiX** [comment]
Yes i also uploaded my new maps to your site with a read my file tells all the maps made by me. Never really added the author informations in the editor. Also linked my website in the read me file where i uploaded all my maps i made

Az iOS Outlook<https://aka.ms/o0ukef> letöltése
________________________________
Feladó: Kenneth Watson <notifications@github.com>
Elküldve: Wednesday, July 15, 2020 6:24:35 PM
Címzett: unreal-archive/unreal-archive-data <unreal-archive-data@noreply.github.com>
Másolatot kap: NBKNiX <trance.9292@hotmail.com>; Mention <mention@noreply.github.com>
Tárgy: Re: [unreal-archive/unreal-archive-data] Mapper name on a few missing one (#230)


@NBKNiX<https://github.com/NBKNiX> Did you also submit these, and are they also supposed to be attributed to you?

#231<https://github.com/unreal-archive/unreal-archive-data/pull/231>

They've all come through with no author information, screenshots or player count information. I'll update them before I add them.

For future maps remember to fill out the level properties with the author, that's where Unreal Archive gets them from.

**Comment by shrimpza** [comment]
The above maps have been fixed.
