### ISSUE TITLE
[Map] DM-JB-Chud

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2300]
Release date is actually  09/12/2002
Source : Readme
No idea if that is 9 of December or 12 of September.

---
URL: https://unrealarchive.org/maps/unreal-tournament/deathmatch/J/dm-jb-chud_4980e5f1.html
Hash: 4980e5f1f03cbd1de618241c49eddf8c9fe2194c
Current name: DM-JB-Chud

**Comment by shrimpza** [comment]
Fixed. Went with December based on the UK email address :)
