### ISSUE TITLE
[Wrong game class] Greed 2004

### ISSUE THREAD

**Issue by NeonKnightOA** [unreal-archive/unreal-archive-data#2310]
https://unrealarchive.org/mappacks/unreal-tournament-2004/deathmatch/G/greed2004nout4mod_1eee2e99.html

It's classified as a mappack when it's actually the original UT2004 Greed gametype upon which [the Greed gamemode of UT3](https://unreal.fandom.com/wiki/Greed) is based on (even created by the same author and everything). The confusion may arise from the example map included with the mod.

Can it be possible to rewrite the page as a gametype rather than a mappack?

**Comment by shrimpza** [comment]
Removed the map, and replaced with a gametype in the gametypes secion.
