### ISSUE TITLE
[Mutator] DC Ammo 436

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2474]
Is there any point in this? It's just another copy of https://unrealarchive.org/mutators/unreal-tournament/D/de-mutator-v1_946fc066.html with a different (and less informative/accurate) zip name.  

"What's DC Ammo 436?" I thought, only to find it was the well-know de.u bunch of mutators that came with one of the Bonus Packs. 

---
URL: https://unrealarchive.org/mutators/unreal-tournament/D/dc-ammo-436_9877d281.html
Hash: 9877d2816e5af03c884df565aaab47c18799f95d
Current name: DC Ammo 436

**Comment by shrimpza** [comment]
Thanks. Removed. I'm not sure what's up with a lot of the recent submissions, it looks a bit hit and miss, but there's too much to go over each in the detail they deserve, so they're going in and we'll do cleanup as needed.
