### ISSUE TITLE
[Maps] All the BP4 maps were uploaded separately!

### ISSUE THREAD

**Issue by NeonKnightOA** [unreal-archive/unreal-archive-data#2476]
https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/B/ctf-beatitude_b34040d5.html - CTF-Beatitude
https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/E/ctf-epicboy_8713c081.html - CTF-EpicBoy
https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/F/ctf-face-se_82ccc1be.html - CTF-Face-SE
https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/R/ctf-ratchet_eb5079e7.html - CTF-Ratchet
https://unrealarchive.org/maps/unreal-tournament/deathmatch/B/dm-bishop_9c674d2b.html - DM-Bishop
https://unrealarchive.org/maps/unreal-tournament/deathmatch/C/dm-closer_c0d61fef.html - DM-Closer
https://unrealarchive.org/maps/unreal-tournament/deathmatch/G/dm-grit-tourney_4be8d790.html - DM-Grit_TOURNEY
https://unrealarchive.org/maps/unreal-tournament/deathmatch/V/dm-viridian-tourney_9c11f157.html - DM-Viridian_TOURNEY
https://unrealarchive.org/maps/unreal-tournament/domination/B/dom-bullet_08eecad4.html - DOM-Bullet
https://unrealarchive.org/maps/unreal-tournament/domination/C/dom-cidom_ecbd9ec7.html - DOM-CiDom
https://unrealarchive.org/maps/unreal-tournament/domination/L/dom-lament_228962cf.html - DOM-Lament][
https://unrealarchive.org/maps/unreal-tournament/domination/W/dom-wolfsbay_e10c976b.html - DOM-WolfsBay

What's the point of uploading all the BP4 maps separately?

EDIT: There's also this one:

https://unrealarchive.org/mappacks/unreal/capture-the-flag/U/ut-goty-maps_d1b0bb48.html - CTF-HallOfGiants and CTF-Orbital from the DE Bonus Pack, which is included in the GOTY Edition.

**Comment by shrimpza** [comment]
Yup, some of this is not great. Looks like a weird bunch of dumps was uploaded. I see other things containing CTF-Tutorial and CTF-Face][ in the queue too. Already had to dismiss a few obvious ones, but there have been so many huge submissions in the last ~3 days it's hard to spot issues.

I'll remove the ones you've flagged.

**Comment by shrimpza** [comment]
They're removed now. Cached versions still exist as direct links but they should be gone from listings.

**Comment by shrimpza** [comment]
It's a pity because now there are submissions like this one, which seem to include new maps, but also a bunch of repackaged stock maps.

https://github.com/unreal-archive/unreal-archive-data/pull/2391

This is really quite terrible.

**Comment by shrimpza** [comment]
What the hell:

https://github.com/unreal-archive/unreal-archive-data/pull/2393

**Comment by NeonKnightOA** [comment]
What about a stock map detector?
It checks against a list of stock maps, if detected, it doesn't upload them.

**Comment by shrimpza** [comment]
Yup, that was my thought as well.

**Comment by NeonKnightOA** [comment]
I'm keeping track of the maps I can find on #2546
