### ISSUE TITLE
[Map] DM-Crate

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2477]
The main attraction of this archive are a set of mutators (The Mutator Weeks). DM-Crate not only should be unset (it has nothing to do with DM-CraterIsland), but probably reindexed too, since it's just a test map.

---
URL: https://unrealarchive.org/maps/unreal-tournament-3/deathmatch/C/dm-crate_498fd57a.html
Hash: 498fd57abaabce4db8d33670f5d6190b7d65399f
Current name: DM-Crate

**Comment by NeonKnightOA** [comment]
I'm sending it to Tests and Demos.
