### ISSUE TITLE
Following author aliases should be excluded from autodetect

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2518]
Following author aliases should be excluded from autodetect/label system: ['s Notes](https://unrealarchive.org/authors/_s-notes.html) and [s Notes](https://unrealarchive.org/authors/s-notes.html). In case it's not obvious, those are text strings from "Author's Notes" content addendum and not actual aliases. All the content currently assigned to those aliases should also be reindexed.

**Comment by NeonKnightOA** [comment]
I've fixed most of those entries in #2545 . As for the latter there was only one map, and there's no associated Readme so for the moment I gave it the "Unknown" author.
