### ISSUE TITLE
[Model] Flora

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2522]
Odd that this is named Flora when both the model and the zip file are named Beatrice - it appears to be no different to the 2 other packages for this model except that one of them is a ut2mod.

---
URL: https://unrealarchive.org/models/unreal-tournament-2004/F/flora_0d06c042.html
Hash: 0d06c042f9e0db3a07aa03237c4f98d4081dfa1f
Current name: Flora

**Comment by shrimpza** [comment]
That is weird.

Also flagged as variation of the other one.
