### ISSUE TITLE
[Map Pack] Nali Chronicles

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2524]
This is for UT 99. 

---
URL: https://unrealarchive.org/mappacks/unreal/single-player/N/nali-chronicles_4b50f51b.html
Hash: 4b50f51b41a5b4d4324ced27928f67e70d28d294
Current name: Nali Chronicles

**Comment by NeonKnightOA** [comment]
For the moment I'm sending it to UT99.
