### ISSUE TITLE
[Map Pack] Fury Part 1 and 2

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2526]
This is for UT99.

---
URL: https://unrealarchive.org/mappacks/unreal/single-player/F/fury-part-1-and-2_2a35b462.html
Hash: 2a35b46217df4e3cc24731385ce005ae7b4a60f2
Current name: Fury Part 1 and 2

**Comment by shrimpza** [comment]
Updated
