### ISSUE TITLE
[Map Pack] Redeem Your Space UT 451b English

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2528]
Um ... this is a real mess.

It has the 7 Bullets campaign and default UT maps mixed in with RyS (plus odd default UT files like Engine.u, etc).  Not sure what else to say beyond that. 

---
URL: https://unrealarchive.org/mappacks/unreal-tournament/single-player/R/redeem-your-space-ut-451b-english_aa48ba75.html
Hash: aa48ba75f481168d36027508c149cba3165c96e5
Current name: Redeem Your Space UT 451b English

**Comment by Semfry** [comment]
I see this was already brought up. I guess this can be removed since there's already an working 227 version anyway

**Comment by shrimpza** [comment]
Hmm, I see it contains BP4 and a bunch of stuff too.

Removing. If anyone wants to try to sort out what the actual pack is supposed to contain, feel free to resubmit.
