### ISSUE TITLE
[Map] Assault on Outpost Seven

### ISSUE THREAD

**Issue by Semfry** [unreal-archive/unreal-archive-data#2529]
"Official" name for this set is "Falcon Outpost"

---
URL: https://unrealarchive.org/maps/unreal-tournament/single-player/A/assault-on-outpost-seven_773d800b.html
Hash: 773d800b09942a15288f2a699bfda15b2529ebd1
Current name: Assault on Outpost Seven

**Comment by shrimpza** [comment]
Updated
