### ISSUE TITLE
[Map Pack] Operation Na Pali 130

### ISSUE THREAD

**Issue by Semfry** [unreal-archive/unreal-archive-data#2533]
This can be removed as ONP is already uploaded to the archive as a game type

---
URL: https://unrealarchive.org/mappacks/unreal-tournament/single-player/O/operation-na-pali-130_db7b9ff0.html
Hash: db7b9ff07d33cde7356834decfa152982dcce8a4
Current name: Operation Na Pali 130

**Comment by shrimpza** [comment]
When I saw it come through I thought it looked familiar. Removed.
