### ISSUE TITLE
[Map Pack] DeadStarMap Pack

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2539]
This SP campaign is for Unreal according to the readme.  The map I tried didn't run in UT with an error related to UnrealShare. 

---
URL: https://unrealarchive.org/mappacks/unreal-tournament/single-player/D/deadstarmap-pack_f7c88396.html
Hash: f7c883960a1a408c81dff38a305d15518051b211
Current name: DeadStarMap Pack

**Comment by shrimpza** [comment]
Updated
