### ISSUE TITLE
[Map] DMZeitkind

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2544]
Probably a map pack as it contains 3 maps -> Zeitknd, Zeitkind_Pro and ZeitkindNPali

---
URL: https://unrealarchive.org/maps/unreal/deathmatch/Z/dmzeitkind_9c5554ba.html
Hash: 9c5554ba8d4bbc4ba85cc6367bb391a66763b824
Current name: DMZeitkind

**Comment by shrimpza** [comment]
Fixed :)
