### ISSUE TITLE
Stock map reporting

### ISSUE THREAD

**Issue by NeonKnightOA** [unreal-archive/unreal-archive-data#2546]
We aren't supposed to have these in the archive, so I'll be leaving here anything I can find:

* Unreal - DmAriza: https://unrealarchive.org/maps/unreal/deathmatch/A/dm-ariza_13a52d77.html
* Unreal - DmDeathFan: https://unrealarchive.org/maps/unreal/deathmatch/D/dmdeathfan_f9fd3f24.html 
  * Dubious example in need to check: https://unrealarchive.org/maps/unreal-tournament/deathmatch/D/dm-deathfan_4bfbab79.html
* Unreal - DmDeck16: https://unrealarchive.org/maps/unreal/deathmatch/D/dmdeck16_e414ab75.html
  * Dubious example in need to check: https://unrealarchive.org/maps/unreal/deathmatch/U/dm-unreal_deck16_e7ec847d.html
* Unreal - DmElSinore: https://unrealarchive.org/maps/unreal/deathmatch/E/dmelsinore_2aaa522e.html
  * Dubious example in need to check: https://unrealarchive.org/maps/unreal-tournament/deathmatch/E/dm-elsinore_d9f539a1.html
* Unreal - DMfith: https://unrealarchive.org/maps/unreal/deathmatch/F/dmfith_b7112d0b.html
* Unreal - DmHealPod: https://unrealarchive.org/maps/unreal/deathmatch/H/dmhealpod_2d519898.html
* Unreal (OEM Version) - DmBayC: https://unrealarchive.org/maps/unreal/deathmatch/B/dmbayc_66363923.html
* Unreal (OEM Version) - DmCreek: https://unrealarchive.org/maps/unreal/deathmatch/C/dmcreek_ec67efca.html
* Unreal Return to Na Pali - DmAthena: https://unrealarchive.org/maps/unreal/deathmatch/A/dmathena_543da8b6.html
* Unreal (Fusion Map Pack) - DM-Cybrosis: https://unrealarchive.org/maps/unreal/deathmatch/C/dm-cybrosis_69f61491.html
* Unreal Tournament - DM-Curse][: https://unrealarchive.org/maps/unreal-tournament/deathmatch/C/dm-curse_2bdbcdac.html
* Unreal Tournament - DM-Deck16][: https://unrealarchive.org/maps/unreal-tournament/deathmatch/D/dm-deck16_6ab22d76.html
* Unreal Tournament (Epic Bonus Pack) - CTF-Cybrosis][: https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/C/ctf-cybrosis_991b593f.html
* Unreal Tournament (Epic Bonus Pack) - DM-HealPod][: https://unrealarchive.org/maps/unreal-tournament/deathmatch/H/dm-healpod_b229d247.html
  * Dubious example in need to check: https://unrealarchive.org/maps/unreal/deathmatch/S/dmsphealpod2000_5f1d41b6.html
* #645 also contains a stock map from the OldUnreal patches: https://unrealarchive.org/maps/unreal-tournament/deathmatch/E/dmexar_b70d1c1e.html

**Comment by NeonKnightOA** [comment]
From https://unrealarchive.org/authors/alan-_talisman_-willard.html:

* DM-Cybrosis (Unreal FMP): https://unrealarchive.org/maps/unreal/deathmatch/C/dm-cybrosis_69f61491.html
* DM-Stalwart (UT99): https://unrealarchive.org/maps/unreal-tournament/deathmatch/S/dm-stalwart_156f0277.html
* DM-Zeto (UT99): https://unrealarchive.org/maps/unreal-tournament/deathmatch/Z/dm-zeto_edbb1c58.html
* CTF-Coret (UT99): https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/C/ctf-coret_c0412e07.html
* CTF-Darji16 (UT99 Epic Bonus Pack): https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/D/ctf-darji16_b7aa985e.html
* CTF-Niven (UT99): https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/N/ctf-niven_dee49cb4.html

**Comment by shrimpza** [comment]
Took a while, but whacked these, thanks!
