### ISSUE TITLE
Spatial Fear Gametype Submission

### ISSUE THREAD

**Issue by Semfry** [unreal-archive/unreal-archive-data#2552]
Continued from this pull: https://github.com/unreal-archive/unreal-archive-data/pull/2536

**Download links:**

ModDB: 
[spatial-fear-12-setup](https://www.moddb.com/mods/spatial-fear/downloads/spatial-fear-12-setup) (exe file that doesn't seem to work on newer Windows versions)
[spatial-fear-12-zip](https://www.moddb.com/mods/spatial-fear/downloads/spatial-fear-12-zip) (non-exe version)

KlanKAOS
[199-SpartialFear1.2_Setup.exe](http://www.klankaos.com/USP/199-SpartialFear1.2_Setup.exe) (exe version)

**Mod Links:**

[ModDB](https://www.moddb.com/mods/spatial-fear)

[Website (archive) ](https://web.archive.org/web/20040814222711/http://dynamic5.gamespy.com/%7Ele/sf/)

Screenshots:

[Several here](https://www.moddb.com/mods/spatial-fear/images)

**Credits:**

Producers 	 
 Alex Hammond 	Project Lead
 Doug Blask 	Second Project Lead
  	 
Programming 	 
 Markus Nuebel 	Lead Programmer
 Jacek Jagrodzki 	Programmer
 Chris Rogers 	Programmer
  	 
Level Design 	 
 Ivan Tanzuira 	Lead Artist
 Chris Rogers 	Lead Level Designer
 Abram Andis 	Level Designer
 Jim Russell 	Level Designer
 Rachel Cordone 	Level Designer
  	 
Art Crew 	 
 Ivan Tanzuira 	Lead Artist
 Jim Russell 	2D Artist
 Mike Gilmour 	2D Artist
 Brandon Baker 	2D Artist
 Tim Brooks 	3D Artist
 Dean Stamp 	3D Artist
  	 
Audio 	 
 Stephen Inglis 	Musician
 Andrey Kogtev 	Musician
 Chris Rogers 	Lead Level Designer
 Ivan Tanzuira 	Lead Artist

Audio 	 
 Edgen 	Musician

Further Thanks To...
Alan Dennis
Josh Frost
Caylo Gypsyblood
Matt Parkin
Eric Poggel
Jack Reacher
Simon Rolphus
Jeff Snow
Scott Sutherland
Kris Thaler
Hayden Wilkinson
Lode Vandavenne
Mike Wilburforce

Title image is attached:

![SFTitle](https://user-images.githubusercontent.com/80732340/221412957-bcc8ab51-1362-4fe6-8028-d19af1869c7c.png)

**Comment by shrimpza** [comment]
Hey @Semfry, sorry it took so long; but thank you for gathering this information like this, it was a great help. The mod has now been added :).
