### ISSUE TITLE
[Model] Anubis

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2557]
Those two model (packs) should be unset. One is an original model, the other are models ported from 2012 version of MOBA called Smite.

---
URL: https://unrealarchive.org/models/unreal-tournament-3/A/anubis_1e898128.html
Hash: 1e89812830385edb2e6627152ce1830fd6e71e55
Current name: Anubis

**Comment by shrimpza** [comment]
fixed
