### ISSUE TITLE
[Model] Shrub Patrol

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2558]
Those two model packs should be unset. One is just a Shrub Patrol pack, the other contains other models. Name of the more recent publication should also be changed to "TheRalfZer0 PACK".

---
URL: https://unrealarchive.org/models/unreal-tournament-3/S/shrub-patrol_dd12de7e.html
Hash: dd12de7e6452a753343a63926d7c48327cbc8d06
Current name: Shrub Patrol

**Comment by shrimpza** [comment]
Done on both
