### ISSUE TITLE
[Map] Hard Crash: The Outer Limits

### ISSUE THREAD

**Issue by Semfry** [unreal-archive/unreal-archive-data#2562]
This seems to be identical to this upload: https://unrealarchive.org/mappacks/unreal/single-player/H/hard-crash_6ac81dcb.html

Except slightly bigger (seemingly just due to compression differences) and classified wrong.

---
URL: https://unrealarchive.org/maps/unreal/single-player/H/hard-crash-the-outer-limits_b9b41ab9.html
Hash: b9b41ab982f051c0859cf544950fa0f5e31a42ce
Current name: Hard Crash: The Outer Limits

**Comment by shrimpza** [comment]
Updated
