### ISSUE TITLE
[Mutator] DE

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2570]
According to the readme for the Digital Extremes' Mutators
1) the release date is 4 January 2000
2) Steve Sinclair is the author of the Team Beacon and Volatiile Weapon mutators
3) Adriano Bertucci is the author of the Volatile Ammo mutator

There seem to be at least 4 versions of this mutator package on UA - all with different release dates.  If I recall correctly, the De.u package was released with one of the Bonus Packs?

---
URL: https://unrealarchive.org/mutators/unreal-tournament/D/de_37474f27.html
Hash: 37474f270364ab10be2989fbf3ea6a6ada3b167e
Current name: DE

**Comment by shrimpza** [comment]
I replaced these with BP2: https://unrealarchive.org/patches-updates/unreal-tournament/bonus-packs/bonus-pack-2/index.html
