### ISSUE TITLE
[Map] EdenBay

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2624]
According to the Readme
1 The map name is DMEdenBay
2 The gametype is DeathMatch

John is also known as Angelheart

---
URL: https://unrealarchive.org/maps/unreal/unknown/E/edenbay_d6689ca6.html
Hash: d6689ca6de4c23f4fb7f50084ff610801911a51f
Current name: EdenBay

**Comment by shrimpza** [comment]
fixed
