### ISSUE TITLE
[Map] CTF-Devastation-SCE

### ISSUE THREAD

**Issue by SeriousBuggie** [unreal-archive/unreal-archive-data#2638]
I enter in search "Devastation", but not found this map.

---
URL: https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/D/ctf-devastation-sce_96d5f233.html
Hash: 96d5f233632efb6dddd3612e546843075d8431d6
Current name: CTF-Devastation-SCE

**Comment by shrimpza** [comment]
Since revising the search, this now works: https://unrealarchive.org/search/index.html?kind=content&q=Devastation
