### ISSUE TITLE
[Map] Hayden Wilkinson, J.R.B.77

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2641]
Somehow, author names are used for the title instead of an actual map name, which is DM-FFM-Constructor, as can be seen in the packaged files.

---
URL: https://unrealarchive.org/maps/unreal-tournament-3/deathmatch/H/hayden-wilkinson-jrb77_f3df44f8.html
Hash: f3df44f85c5ed06387b93170ba6f8dafd6b66b0f
Current name: Hayden Wilkinson, J.R.B.77

**Comment by shrimpza** [comment]
Looks like it got fixed: https://unrealarchive.org/maps/unreal-tournament-3/deathmatch/F/dm-ffm-constructor_f3df44f8.html#
