### ISSUE TITLE
[Map] Matrix-ServerReset

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2642]
This isn't a Monster Arena map, but some kind of transitional arena for voting purposes (I assume). Here's how it's author describes it (via readme):

> Just a simple map I made for my server and any server admins.  It's a hallway with a kill volume, everyone dies, and then a new map can be voted into play.

Should be moved elsewhere. Afaik, there is no Monster Arena gamemode in UT2004 at all.

---
URL: https://unrealarchive.org/maps/unreal-tournament-2004/monster-arena/T/matrix-serverreset_f0f07703.html
Hash: f0f07703ff1646e5153cc75ff400b29e5db71836
Current name: Matrix-ServerReset

**Comment by shrimpza** [comment]
I've moved this to unknown.
