### ISSUE TITLE
[Map] DM-AnimMapPreview

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2645]
This is not a playable map. Here's what the readme says:

> Example map for the UnrealEd4 tutorial "Creating an Animated Map Preview for a UT3 map"

Should probably be moved to [Test and Demos](https://unrealarchive.org/maps/unreal-tournament-3/tests-and-demos/index.html). Map author is Dennis Grass.

---
URL: https://unrealarchive.org/maps/unreal-tournament-3/deathmatch/A/dm-animmappreview_95ac8ff1.html
Hash: 95ac8ff186e4fd54e741db59c8bf08c2aca703b3
Current name: DM-AnimMapPreview

**Comment by shrimpza** [comment]
done
