### ISSUE TITLE
[Map] cs_machinima_memory

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2646]
This is a machinima/cinematic map and could use an "Entries and Intros" section, same as [this one](https://github.com/unreal-archive/unreal-archive-data/issues/2643).

---
URL: https://unrealarchive.org/maps/unreal-tournament-2004/unknown/C/cs_machinima_memory_be77c59b.html
Hash: be77c59b50c4c3792539f0ffde4eb11a088854b0
Current name: cs_machinima_memory

**Comment by shrimpza** [comment]
Fixed
