### ISSUE TITLE
[Map] DM-NBK-Masterbath-25-UT-Dx

### ISSUE THREAD

**Issue by DxTrEm3Fx** [unreal-archive/unreal-archive-data#2653]
Your description here
Why is my name showing up incorrectly in the author setting? Am I assuming the special characters?  Can we get it corrected please to Michael<(DxTrEm3Fx)>Lalla

---
URL: https://unrealarchive.org/maps/unreal-tournament/deathmatch/N/dm-nbk-masterbath-25-ut-dx_8202ff8b.html
Hash: 8202ff8b0cfc1258d9f992ceaccd1d1aca76b24d
Current name: DM-NBK-Masterbath-25-UT-Dx

**Comment by shrimpza** [comment]
Fixed.

There was an alias which had DxTrEm3Fx as higher preference, replaced it with Michael<(DxTrEm3Fx)>Lalla.

**Comment by DxTrEm3Fx** [comment]
This must be an old request? Otherwise I'm not sure what you are talking about. Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Kenneth Watson ***@***.***> Date: 11/10/23  8:11 PM  (GMT-07:00) To: unreal-archive/unreal-archive-data ***@***.***> Cc: DxTrEm3Fx ***@***.***>, Author ***@***.***> Subject: Re: [unreal-archive/unreal-archive-data] [Map] DM-NBK-Masterbath-25-UT-Dx (Issue #2653) 
Fixed.
There was an alias which had DxTrEm3Fx as higher preference, replaced it with Michael<(DxTrEm3Fx)>Lalla.
