### ISSUE TITLE
http link to medor

### ISSUE THREAD

**Issue by SeriousBuggie** [unreal-archive/unreal-archive-data#2658]
Chrome not allow download from http links if it placed on https website.

So for medor better use middle http page for this.

For example instead of url
`http://medor.no-ip.org/index.php?dir=Maps/CTF&file=ctf-thorns206.zip`
use
`http://medor.no-ip.org/index.php?dir=&search_mode=f&search=ctf-thorns206.zip`
This lead to http page (not download), which allowed in Chrome. So users can lately click on file and download it.

**Comment by shrimpza** [comment]
Done per your suggestion; although a better solution would be for Medor to switch to HTTPS, before his site drops off the internet entirely due to browsers refusing outright to download stuff from there.

**Comment by SeriousBuggie** [comment]
Confirmed. Now work in Chrome. Thanks.

About wipe from internet - highly doubt about that. Some sites never migrate.
