### ISSUE TITLE
[Map] DM-NBK-Masterbath-25-UT-Dx

### ISSUE THREAD

**Issue by DxTrEm3Fx** [unreal-archive/unreal-archive-data#2659]
Unreal Archive Contact
Who do I contact to have a few of my maps removed? I made errors, and they need to be replaced. Is there someone I can reach out to? I would like to have all 3 of my last submissions removed. 
DM-NBK-Masterbath-25-UT-Dx.unr
DM-NBK-Masterbath-25-UT-NLG-Dx.unr
DM-NBK-Masterbath-25-UT-Dx-2023.unr
Sorry for the inconvience this will cause. 

Thank you,
MIchael Lalla
mlalla42@gmail.com

---
URL: https://unrealarchive.org/maps/unreal-tournament/deathmatch/N/dm-nbk-masterbath-25-ut-dx_b84b194f.html
Hash: b84b194f7431b6ce91c971bb36291cc224d2743e
Current name: DM-NBK-Masterbath-25-UT-Dx

**Comment by shrimpza** [comment]
I will remove them

**Comment by DxTrEm3Fx** [comment]
Thank you,

Michael Lalla

**Comment by DxTrEm3Fx** [comment]
Hello Kenneth,
So, I’m trying to re-upload my finalized maps, and nothing is happening. Not sure if the map names were blocked or what’s going on. This is all I see when I try to upload the new maps. It never goes any further than what the image shows, and I’m not getting any completion status.

Any help would be appreciated.

Thank you,

Michael Lalla

 

From: ***@***.*** ***@***.***> 
Sent: Saturday, April 22, 2023 7:59 AM
To: 'unreal-archive/unreal-archive-data' ***@***.***>; 'unreal-archive/unreal-archive-data' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [unreal-archive/unreal-archive-data] [Map] DM-NBK-Masterbath-25-UT-Dx (Issue #2659)

 

Thank you,

Michael Lalla
