### ISSUE TITLE
[Map] AS-Redemption][

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [unreal-archive/unreal-archive-data#2662]
It seems that the website has two different versions of the same map but they are named the same.
One of them has version 1.0 and the second one version is unknown. Probably, it was a preview. That preview also does not have additional resources like textures, etc in the archive.
AS-Redemption][.unr size 6.329 vs 6.273.

**Comment by shrimpza** [comment]
I've removed the broken one, it was the same map but missing the associated files.

https://unrealarchive.org/maps/unreal-tournament/assault/R/as-redemption_7c2cc727.html is now the proper one.
