### ISSUE TITLE
[Map] DM-Portfolio

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2680]
With only one PlayerStart in the map - not a DeathMatch map.  I would suggest that the name of the map points to its purpose - it appears to showcase a number of works of art, presumably by the maker of the map.  Best placed under Tests/Demos perhaps but certainly not a DM map. 

---
URL: https://unrealarchive.org/maps/unreal-tournament/deathmatch/P/dm-portfolio_6c5cfc85.html
Hash: 6c5cfc854fb0681cad5857dd65de1feca0d3a4e0
Current name: DM-Portfolio

**Comment by shrimpza** [comment]
Moved
