### ISSUE TITLE
Cannot upload a map - pipeline does not start (502 server error)

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [unreal-archive/unreal-archive-data#2791]
When I try to submit a map to https://unrealarchive.org/, the `Processing Status` just does not start and the map does not appear in pull requests no matter how long you wait. This happened lately. Tried in several browsers.

```
Failed to load resource: the server responded with a status of 502 ()
index.html:268 Uncaught TypeError: Cannot read properties of null (reading 'toString')
    at XMLHttpRequest.<anonymous> (index.html:268:69)
```

**Comment by UnrealGGecko** [comment]
Yea not letting me upload anything for a while, finishes the bar and then nothing happens in my end.

**Comment by shrimpza** [comment]
I disable uploads to slow the role of one "Moloch" who spammed literally hundreds of their maps, many of which are duplicates and variations of themselves, since they decided to upload every single one individually rather than as a simple batch.

Apologies, but it's taking a while to get through all the approvals.

**Comment by YevheniiPokhvalii** [comment]
> I disabled uploads to slow the roll of one "Moloch" who spammed literally hundreds of their maps, many of which are duplicates and variations of themselves, since they decided to upload every single one individually rather than as a simple batch.
> 
> Apologies, but it's taking a while to get through all the approvals and cleanup.
> 
> I'll probably open uploads again once I've added some max uploads per day restriction or something.

Moloch is an outstanding artist. He did a lot of maps for UT 3. Some of them are pretty unique especially his later works. I'd say they are not about gameplay they are more of art. Right now it's almost impossible to find them online. I hope you merge them.
