### ISSUE TITLE
Add Bunny Trails map section for UT 3

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [unreal-archive/unreal-archive-data#2793]
There was a Bunny Trails mod for UT 3 (Similar to UT99 BT).

Map names started with `BT` like in `BT-6-Iceworld`.

I think I have almost all maps released for this mod and can share them along with the mod.

**Comment by shrimpza** [comment]
Hello @YevheniiPokhvalii 

Do you have somewhere you could upload/share the release files for this mod please?

**Comment by YevheniiPokhvalii** [comment]
> Hello @YevheniiPokhvalii
> 
> Do you have somewhere you could upload/share the release files for this mod please? I'll configure it as a gametype download and index the maps.

Sure, here is the link: https://drive.google.com/drive/folders/1BIuPmyDG1r8aRPXjH3IqGIcQUugu5Zyr?usp=sharing

Now I've realised that I have two versions of the mod. The last version now cannot even be found online anymore.
v20100201 was kind of a stable release.
And I think v20101008 was presumably the last beta but with new features and fixes.

**Comment by shrimpza** [comment]
I've added all the stuff you sent, the gametype itself as well as the maps and map pack. 

Thanks!
