### ISSUE TITLE
[GameType] Spatial Fear release 1.2

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2795]
The list of Packaged Files does not include the 14 maps which are the core of this mod - these maps have the suffix .sfp which possibly is the reason they have not been parsed.

I thought it was odd that there were no maps in the list so downloaded the zip and, sure enough, they are included in the zip.

---
URL: https://unrealarchive.org/gametypes/unreal-tournament/S/spatial-fear/12/index.html
Hash: None
Current name: Spatial Fear

**Comment by shrimpza** [comment]
Why do people make it hard. 

Damn we thought we were cool back in the day, with our custom map extensions and custom launchers and custom EXEs that break as soon as UT gets patched... :sweat_smile:

**Comment by shrimpza** [comment]
Indexed them
