### ISSUE TITLE
[Mutator] Sentinel

### ISSUE THREAD

**Issue by schery2023** [unreal-archive/unreal-archive-data#2796]
Hello

This Sentinel Muatator is NOT listed in the mutator list of UT3 as you may see here there is no "Sentinel" entrance (only a "Sentine Gear" sentrance, which is a an add-on to "Sentinel" and requieres "Sentinel") : https://unrealarchive.org/mutators/unreal-tournament-3/  

My request:

Please list the Sentinel mutator https://unrealarchive.org/mutators/unreal-tournament-3/S/sentinel_f62f959a.html in the mutator list, that will make it a lot easier to find for anybody.

Thank you very much.
And also many thanks that you run this unreal-archive. (!!)

Greetings
Schery

P.S. I'd love to get a short feedback from you

---
URL: https://unrealarchive.org/mutators/unreal-tournament-3/S/sentinel_f62f959a.html
Hash: f62f959ac6521b0386d84957dd3b7cbc867dc4c0
Current name: Sentinel

**Comment by shrimpza** [comment]
This should now be fixed, thanks.

**Comment by schery2023** [comment]
Thank you very much

Are you running this archive?

It's an amazing collection. I play every day some hours UT3 since it came out. Steam counts 12'000 hours of playtime and most of the time I wasn't playing it with Steam.

**Comment by schery2023** [comment]
well, actually it's 13'000 hours now in steam https://steamcommunity.com/id/doctorhollywood/

all in all I am near 30'000 hours
