### ISSUE TITLE
[Map] DM-RJ-SFX-PICKUP

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2798]
Not a DM map - quoting from the readme "Not a map for playing...just a means of enabling people to download and use my SFX pack :)

Sound pack made by

_  |ØØ)     |  _
Ø  |ØØ\  |__|  Ø 

End of quote.

Best placed under Tests/Demos? 

---
URL: https://unrealarchive.org/maps/unreal-tournament/deathmatch/R/dm-rj-sfx-pickup_a64d4008.html
Hash: a64d40083ee4aadcaa3f84f44947246c96991ea0
Current name: DM-RJ-SFX-PICKUP

**Comment by shrimpza** [comment]
Updated gametype.

I dunno what do do with the author though.
