### ISSUE TITLE
[Model] Knuckles 

### ISSUE THREAD

**Issue by Mafoo343** [unreal-archive/unreal-archive-data#2799]
Just as an FYI, this version of the model pack is the slightly outdated beta 3.  The last version from the original author is beta 4.  While I couldn't track down the original archive the files came in, I do have the files that were in them.  For reference, I'll attach the beta 4 files I pulled from my UT2004 installation, including the original readme from the author dated 8/4/2012.  If you can, I would recommend updating this pack to the latest version, or at the very least making the beta 4 available as a separate download.

-Edit

After digging a little harder, the original author reuploaded the beta 4 on mediafire last year, here's the link:
https://www.mediafire.com/file/14vhsq5d1nfmhht/KnucklesChaotixUT2004beta4.rar/file

---
URL: https://unrealarchive.org/models/unreal-tournament-2004/K/knuckles-chaotix_00c57693.html
Hash: 00c5769383b01db5fe881beb8ed9d323c0cc495c
[KnucklesUT2004beta4.zip](https://github.com/unreal-archive/unreal-archive-data/files/11711460/KnucklesUT2004beta4.zip)

Current name: Knuckles

**Comment by shrimpza** [comment]
thanks, updated with the beta 4 release file.

new version:
-  https://unrealarchive.org/models/unreal-tournament-2004/K/knuckles-chaotix_4b5ade8b.html
