### ISSUE TITLE
Unreal Archive mirror issues for UT3 Bunny Trials maps

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2811]
Unreal Archive US mirrors for [BT-5-RoutesOfTrain_Beta7](https://unrealarchive.org/maps/unreal-tournament-3/bunny-trails/B/bt-5-routesoftrain_beta7_3c555ce8.html), [BT-2-CroftManor_B1](https://unrealarchive.org/maps/unreal-tournament-3/bunny-trails/B/bt-2-croftmanor_b1_0079f41f.html) and [BT-4-Indiana_beta2v6](https://unrealarchive.org/maps/unreal-tournament-3/bunny-trails/B/bt-4-indiana_beta2v6_5a6cb077.html) are doubled. [BT-7-Meteormoonbase_beta](https://unrealarchive.org/maps/unreal-tournament-3/bunny-trails/B/bt-7-meteormoonbase_beta_9590a90e.html) doesn't have Unreal Archive EU mirror.

**Comment by PootisKorn** [comment]
I cannot download [BT-7-Meteormoonbase_beta](https://unrealarchive.org/maps/unreal-tournament-3/bunny-trails/B/bt-7-meteormoonbase_beta_9590a90e.html) at all, XML error.

**Comment by shrimpza** [comment]
Thanks for the report, I believe these are now all corrected.

**Comment by YevheniiPokhvalii** [comment]
@PootisKorn Just in case, additional maps can be grabbed here: https://unrealarchive.org/mappacks/unreal-tournament-3/bunny-trails/B/bunny-trails-mappack-2010_57270dc6.html
