### ISSUE TITLE
[Mutator] Titan

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2840]
This mutator should be unset from [TitanRPG 1.71 BETA](https://unrealarchive.org/mutators/unreal-tournament-2004/T/titanrpg-171-beta_a4464b77.html). Former is a custom combo, that imitates Titan mechanic from UT3, latter is a full blown RPG mutator.

---
URL: https://unrealarchive.org/mutators/unreal-tournament-2004/T/titan_6ebce764.html
Hash: 6ebce76491d1e3ecd5110f19fcfb2efdd34a88d8
Current name: Titan

**Comment by PootisKorn** [comment]
The following is unrelated to this issue, but I have nowhere else to post this: it would be really great, if the issues I reported earlier would be given attention. Some of them go way back to February.

**Comment by shrimpza** [comment]
Fixed.

I fix things as and when I have time.
