### ISSUE TITLE
[Map] VCTF-KlinikaResemblance

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2903]
[VCTF-KlinikaResemblance](https://unrealarchive.org/maps/unreal-tournament-3/vehicle-ctf/K/vctf-klinikaresemblance_b7bfdbba.html) and [CTF-KlinikaResemblance](https://unrealarchive.org/maps/unreal-tournament-3/capture-the-flag/K/ctf-klinikaresemblance_484c59b0.html) should be unset. These maps are similar, but they are for very different gamemodes.

---
URL: https://unrealarchive.org/maps/unreal-tournament-3/vehicle-ctf/K/vctf-klinikaresemblance_b7bfdbba.html
Hash: b7bfdbba99f595fc1c5e4028e0f417bdd257eb14
Current name: VCTF-KlinikaResemblance

**Comment by shrimpza** [comment]
fixed
