### ISSUE TITLE
[Map] CTF-Greed-Acropolis

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2923]
As evident by the name, this map should be moved to the [Greed](https://unrealarchive.org/maps/unreal-tournament-3/greed/index.html) section.

---
URL: https://unrealarchive.org/maps/unreal-tournament-3/capture-the-flag/G/ctf-greed-acropolis_e7d0ec92.html
Hash: e7d0ec9287473734ad3963a347c0e805ad2de796
Current name: CTF-Greed-Acropolis

**Comment by shrimpza** [comment]
fixed
