### ISSUE TITLE
Incomplete UT3 map packs info recognition

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2925]
Unreal Archive tends to leave some data out of UT3 map packs that is otherwise picked up in single UT3 map submissions. An example can be seen [here](https://unrealarchive.org/mappacks/unreal-tournament-3/deathmatch/D/dm-noiz_c259ed56.html) or [here](https://unrealarchive.org/mappacks/unreal-tournament-3/deathmatch/U/ut3-custommap-pack_6f67aee9.html). Both map packs have screenshots inside archives that website failed to add.

There's also an issue with zips in zip (another one). If there are maps for different gamemodes, Unreal Archive picks up only the first one. [An example](https://unrealarchive.org/mappacks/unreal-tournament-3/capture-the-flag/F/fa2k-ut3-doppelpackmaps-dm-ctf_e4ee69ee.html).

**Comment by shrimpza** [comment]
The problem with "Fa2k UT3 Doppelpackmaps Dm Ctf" seems to be that the sub-archive (the DM one) contains a corrupted file - Light_dm_2.jpg.

Aside from that I see why the screenshots are not included in sub-archived mappacks, and will correct the issue.

**Comment by shrimpza** [comment]
Fixed. 

The new Url for the FA2k one is https://unrealarchive.org/mappacks/unreal-tournament-3/mixed/F/fa2k-ut3-doppelpackmaps-dm-ctf_e4ee69ee.html

I will try to re-index and fix historical stuff too.
