### ISSUE TITLE
[Map] DM-Kenchoji

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2930]
XML error when trying to download, also no EU mirror. I imagine a couple of other submissions from the past 10 days might also have this issue.

---
URL: https://unrealarchive.org/maps/unreal-tournament-3/deathmatch/K/dm-kenchoji_09ce3a13.html
Hash: 09ce3a135ec4932ca9256874eef7f55bb7192c24
Current name: DM-Kenchoji

**Comment by shrimpza** [comment]
Fixed, had to re-upload from a copy I found elsewhere: https://unrealarchive.org/maps/unreal-tournament-3/deathmatch/K/dm-kenchoji_e822ba3a.html

I believe this was a bug in a previous version of the submitter, which has hopefully been fixed.

I spot checked a bunch of other files from around this time, and they seemed fine.
