### ISSUE TITLE
[Map] DM-Messestadt_West

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2936]
This map is a university art project that isn't intended for normal gameplay (map lacks weapons, health pickups and bothpaths, only somewhat playable in Instagib). More info on [MapRaider](https://www.mapraider.com/maps/search/Messestadt_West/5526/DM-Messestadt_West). Should probably be moved to [Tests and Demos](https://unrealarchive.org/maps/unreal-tournament-3/tests-and-demos/index.html).

---
URL: https://unrealarchive.org/maps/unreal-tournament-3/deathmatch/M/dm-messestadt_west_50434bd4.html
Hash: 50434bd4edec2d85fc0cbb3fd4b1a34a75570f29
Current name: DM-Messestadt_West

**Comment by shrimpza** [comment]
Done
