### ISSUE TITLE
Possibility to switch between light and dark themes at unrealarchive.org

### ISSUE THREAD

**Issue by t3r6** [unreal-archive/unreal-archive-data#2954]
I can see that there were some changes on the website https://unrealarchive.org/.
It's nice to have a dark theme nowadays but is it possible to restore the light theme as well and make an option to switch between themes?
Some people, including myself, do not perceive letters that well when there is a dark background. It's hard to concentrate and read.

**Comment by shrimpza** [comment]
Hey, thanks for the report, I hadn't realised it could be an issue for some people.

I've enabled a light mode - if your OS or browser has a light theme, the website should be in light mode too. 

Can you confirm?

**Comment by t3r6** [comment]
Yes, it works. Thanks!

**Comment by shrimpza** [comment]
Great :tada:

**Comment by PootisKorn** [comment]
Text descriptions for custom gamemodes are now unreadable, because they have black text on a black background. [An example](https://unrealarchive.org/maps/unreal-tournament-3/the-haunted/index.html).

**Comment by shrimpza** [comment]
@t3r6 You may notice it go back to dark by default now, but there's a "Theme" option that will make it light.

This works better since it allows people to change independent of their browser/OS settings.

@PootisKorn Should be improved.

**Comment by t3r6** [comment]
> @t3r6 You may notice it go back to dark by default now, but there's a "Theme" option that will make it light.
> 
> This works better since it allows people to change independent of their browser/OS settings.
> 
> @PootisKorn Should be improved.

Just a trivial thing. I noticed that some websites also offer `use browser default` theme. Like 3 options: dark, light, use browser default.
