### ISSUE TITLE
Highlight `no recognisable content found in file`

### ISSUE THREAD

**Issue by t3r6** [unreal-archive/unreal-archive-data#2956]
When you upload maps in bulk, you may get messages like `No new content found in file` and `No recognisable content found in file` in the same color. And it makes an impression that the map with `No recognisable content found in file` is already on the server and it's fine.

In reality, the message `No new content found in file` is actually fine but the `No recognisable content found in file` message means that a map was not accepted. So the latter is basically an error.

I think the `No recognisable content found in file` message should be highlighted with a different color to distinguish the error visually.

**Comment by shrimpza** [comment]
I have updated the styling to make the "No recognisable content found" lines red
