### ISSUE TITLE
Unreal Archive sometimes fails to index mutators

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#2961]
Website recognizes mutator, but fails to index files even when I try to force the file type. This happens regardless of the game. Here's a [link to one such mutator](https://www.mediafire.com/download/evypvu6pev3m73q/ThunderstormRifle.rar) for UT99 as an example.

**Comment by shrimpza** [comment]
Thanks I did not know this was a problem.

Seems to be for mutators with weapons without a description, where the description is under a `WeaponDescription` in a section named after the weapon class.

This has been fixed, per the MR https://github.com/unreal-archive/unreal-archive-data/pull/2963

https://unrealarchive.org/mutators/unreal-tournament/T/thunderstormrifle_62f3eeec.html
