### ISSUE TITLE
[Map] CTF-DMU-ClusterFkk

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2967]
This conversion is by FraGnBraG

Source = Readme

Faceless made the original DM map

---
URL: https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/D/ctf-dmu-clusterfkk_c426b730.html
Hash: c426b730db3a287a73c4dfe646b93a5bd5affd74
Current name: CTF-DMU-ClusterFkk

**Comment by shrimpza** [comment]
fixed
