### ISSUE TITLE
[Map] DM-Gore

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2975]
Odd that this has been parsed as an Unreal Tournament map, given the map suffix of .run and all the missing dependencies - it looks like a Rune map and, indeed, another copy of it is already in the Archive.

---
URL: https://unrealarchive.org/maps/unreal-tournament/deathmatch/G/dm-gore_e0c87852.html
Hash: e0c8785237dc233a5f9ddbc76db6ad3002a965fe
Current name: DM-Gore

**Comment by shrimpza** [comment]
Thanks. I think this happened before as well. I see the other map is dated July this one is August.

This looks newer. Will fix game and flag variant.
