### ISSUE TITLE
[Model] Neptunia Model Pack

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#2983]
The download for this doesn't work - not for me anyway - I just get a 4Kg 7z file!

---
URL: https://unrealarchive.org/models/unreal-tournament-2004/N/neptunia-model-pack_38887eba.html
Hash: 38887eba6c9fca033745d253944820e10c808a0f
Current name: Neptunia Model Pack

**Comment by shrimpza** [comment]
that's pretty heavy...

Bugger. Second time this has happened. Will take a look, thanks.

**Comment by shrimpza** [comment]
Fixed:

https://unrealarchive.org/models/unreal-tournament-2004/H/hyperdimension-neptunia-ultimate-model-pack_38887eba.html
