### ISSUE TITLE
[Map Pack] Assaultbonuspack

### ISSUE THREAD

**Issue by Ohcmon** [unreal-archive/unreal-archive-data#3015]
Your description here

 Assaultbonuspack, and  Assaultbonuspack418 do not work for me. Umod clicking did nothing, I'd like to use them if possible, thanks.

**Comment by shrimpza** [comment]
Hello @Ohcmon 

You can convert UMOD files to normal ZIP files using this: https://unrealarchive.org/umod/

Just upload your file, wait for it to be finished, and then download the converted zip file.

**Comment by Ohcmon** [comment]
Thanks, I will check this out. I have used the assault packs in the past.

________________________________

**Comment by Ohcmon** [comment]
It worked good thanks !

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
