### ISSUE TITLE
Misceallenious Greed maps that should be moved to the appropriate section

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#3047]
Despite the lack of GRD prefix, following maps were made with the Greed gametype in mind and should be moved to the appropriate section:

[CTF-ArenaRelic](https://unrealarchive.org/maps/unreal-tournament-3/capture-the-flag/A/ctf-arenarelic_820df8e0.html)
[CTF-DarkMess](https://unrealarchive.org/maps/unreal-tournament-3/capture-the-flag/D/ctf-darkmess_89d6abd7.html)
[VCTF-FRAGASM!](https://unrealarchive.org/maps/unreal-tournament-3/vehicle-ctf/F/vctf-fragasm_28a99d28.html)

More info in [this BeyondUnreal thread](https://forums.beyondunreal.com/threads/greed-mini-map-pack-4-5-maps.186341).

**Comment by shrimpza** [comment]
Fixed
