### ISSUE TITLE
[Map] DM-Crate

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#3049]
No idea what happened here, but this map is present in both Tests and Demos and Deathmatch sections. It's also still listed as a variation of [DM-CraterIsland_Beta_2](https://unrealarchive.org/maps/unreal-tournament-3/deathmatch/C/dm-craterisland_beta_2_2c4de77f.html). [Previous issue topic](https://github.com/unreal-archive/unreal-archive-data/issues/2477) with this map for reference.

---
URL: https://unrealarchive.org/maps/unreal-tournament-3/tests-and-demos/D/dm-crate_498fd57a.html
Hash: 498fd57abaabce4db8d33670f5d6190b7d65399f
Current name: DM-Crate

**Comment by shrimpza** [comment]
When a map is reassigned from one gametype to another, the old version of the HTML page for it usually remains for a while - however there are no longer links to the old page/version in the listing pages etc, unless you fish out a link from the original issue reports.

I've fixed the variation however.
