### ISSUE TITLE
Virus scan failed.

### ISSUE THREAD

**Issue by UnrealGGecko** [unreal-archive/unreal-archive-data#3052]
Getting Virus scan failed errors when uploading pretty much any file lately. Assuming the scanner broke? Think it started last week or so.
![VirusScanFailed](https://github.com/unreal-archive/unreal-archive-data/assets/75163497/e1e520c5-51ef-4b70-857d-3f50001aabac)

**Comment by shrimpza** [comment]
Oh, thank you, I didn't know it had broken.

Restarted stuff, should be up again. I thought it was just a quiet time for submissions :joy:

**Comment by PootisKorn** [comment]
Still doesn't work on my end.

**Comment by PootisKorn** [comment]
> Still doesn't work on my end.

Seems like all good now.
