### ISSUE TITLE
[Map] DM-WhiteWiz

### ISSUE THREAD

**Issue by Mrwintr** [unreal-archive/unreal-archive-data#3054]
This download for this map is also missing the " CelesteTEX.utx " file. I searched around and found it but it is needed to make the map load.

---
URL: https://unrealarchive.org/maps/unreal-tournament-2004/deathmatch/W/dm-whitewiz_3a561ad0.html
Hash: 3a561ad08cf00187298945822ebee255164bdb23
Current name: DM-WhiteWiz

**Comment by shrimpza** [comment]
Yup, this is noted on the map page.
