### ISSUE TITLE
[Map] onp-Iceskaarjtrainingbase

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#3066]
This is a Single Player map. 

---
URL: https://unrealarchive.org/maps/unreal-tournament/unknown/O/onp-iceskaarjtrainingbase_dc131209.html
Hash: dc131209a45973b3bd893f98e7045e4a955693db
Current name: onp-Iceskaarjtrainingbase

**Comment by shrimpza** [comment]
Fixed. Thanks, I noticed it after merging and forgot to circle back to correct it.
