### ISSUE TITLE
Creator list: Warbeast / Soenke C. "Warby" Seidel

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#3076]
Not sure if this can be useful, but here's a list that aims to find all Unreal Tournament creations of [Warbeast](https://unrealarchive.org/authors/warbeast.html) aka [Soenke C. "Warby" Seidel](https://unrealarchive.org/authors/soenke-c__war_-seidel.html). While some stuff has been properly marked by the website, there are a bunch of mods that weren't recognized. Only his solo works are included in the list. If this list will be of some use, I might make more for other creators.

Characters:

Oscar (one is recognized, while the duplicate isn't):  https://unrealarchive.org/models/unreal-tournament-2004/O/oscar_e4e91663.html and https://unrealarchive.org/models/unreal-tournament-2004/O/oscar_e4c59586.html

Eightball (not indexed):  https://unrealarchive.org/models/unreal-tournament-2004/E/eightball_6c8903bf.html

Kitty (also not indexed):  https://unrealarchive.org/models/unreal-tournament-2004/K/kitty_2cedca95.html

Meryl (same as Oscar, duplicate wasn't recognized):  https://unrealarchive.org/models/unreal-tournament-2004/M/meryl_74_a3f19de7.html and https://unrealarchive.org/models/unreal-tournament-2004/M/meryl_74_966e187f.html

CE-Guard: This is a special case - I can't seem to find this model on Unreal Archive. If someone can (re)upload it, that would be great. Here's it's ArtStation page:  https://www.artstation.com/artwork/48aOY

UT2004 Maps:

BR-Biohazard (map's page lacks any meaningful images/screenshots):  https://unrealarchive.org/maps/unreal-tournament-2004/bombing-run/B/br-biohazard_f48cf49f.html

DM-Frozen (map's page lacks any images/screenshots):  https://unrealarchive.org/maps/unreal-tournament-2004/deathmatch/F/dm-frozen_e158c7c7.html

DM-Chimera:  https://unrealarchive.org/maps/unreal-tournament-2004/deathmatch/C/dm-chimera_26dab5ef.html

CTF-Skorbut :  https://unrealarchive.org/maps/unreal-tournament-2004/capture-the-flag/S/ctf-skorbut_4c5d1a36.html

DOM-Invasion:  https://unrealarchive.org/maps/unreal-tournament-2004/domination/I/dom-invasion_d9204ead.html

DM-CBP2-Koma: This map doesn't seem to have a standalone upload on Unreal Archive. Here's it's ArtStation page:   https://www.artstation.com/artwork/8emXO

ONS-CBP2-Yorda: Same as above - no standalone entry. Here's it's ArtStation page:  
https://www.artstation.com/artwork/GakNQ

UT3 Maps:

DM-Elevation (map is incorrectly indexed):  https://unrealarchive.org/maps/unreal-tournament-3/deathmatch/E/dm-elevation_1b19be3b.html

DM-Grand-Diablo (map is indexed under the Soenke C."War" Seidel name):  https://unrealarchive.org/maps/unreal-tournament-3/deathmatch/G/dm-grand-diablo_c9d7bb50.html

That should be all. Here's his ArtStation profile for reference, it includes his early UT works:  

https://www.artstation.com/warby

**Comment by shrimpza** [comment]
Thanks! Fixed authors and variations/duplicates where possible. Also made an alias for Warbeast/Soenke C."Warby" Seidel, so these will be grouped on the Warbeast author page.

In terms of the Artstation content, it seems that site does not contain downloads of any of his content, just screenshots, so I'm not sure we can do anything about that, unless someone can track down the actual files - in which case just use the submission feature to upload them.

Missing screenshots - if the author has not specified any in the map, or has somehow used an incompatible format (sometimes certain screenshots defined as shader materials cannot be automatically extracted), there will be none shown on the listing in the website.
