### ISSUE TITLE
[Map] TDK-NightOp

### ISSUE THREAD

**Issue by Ohcmon** [unreal-archive/unreal-archive-data#3122]
Your description here
'Extract the TDarkMatch.int file to your UT's "System" folder'. This step wasn't necessary, and created a new heading in game type. Cheers!

---
URL: https://unrealarchive.org/maps/unreal-tournament/darkmatch/N/tdk-nightop_2d6f19c0.html
Hash: 2d6f19c0e8a158e1521ab1b8b3b2f9b9e7e2c080
Current name: TDK-NightOp

**Comment by shrimpza** [comment]
Linked to issue with installation information.

Thanks :tada:
