### ISSUE TITLE
[Skin] Ironguard

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#3123]
This skin, as well as Thundercrash, is actually for Unreal - it's for Female1 and 2, Male1, 2 & 3.  It can, of course, be used in UT99 but it is intended for Unreal (as the Readme and installation guide make clear).

---
URL: https://unrealarchive.org/skins/unreal-tournament/I/ironguard_c3aaa03e.html
Hash: c3aaa03ebdd11b6c770a83dc690325dadefce7cd
Current name: Ironguard

**Comment by shrimpza** [comment]
Moved to Unreal
