### ISSUE TITLE
[Model] Marine

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#3124]
I think this should be categorised as a Skin rather than as a Model.

The original Marine model is the same as, and predates, the model in this archive and was not made by 2'Face.

2'Face is the author of the skin in this archive - the problem, though, is that the name of the .utx is the same as the name of the .utx with the original skin for the model - meaning that only one, rather than both, of the skins can be installed.

---
URL: https://unrealarchive.org/models/unreal-tournament/M/marine_002e93db.html
Hash: 002e93dbc5a5b761fde0b7669aaab097535ff780
Current name: Marine

**Comment by shrimpza** [comment]
Re-indexed as a skin.
