### ISSUE TITLE
[Author] Platinum's maps have been mislabeled as made by |KB|AIDS 

### ISSUE THREAD

**Issue by UnrealGGecko** [unreal-archive/unreal-archive-data#3133]
All the DM maps from here should instead have "Aaron "Platinum" Ingersoll" as author, dunno how it got changed. The CTF maps are by him (could also change his name to "|KB|Aids aka |KB|Platinum"

https://unrealarchive.org/authors/_kb_aids.html

But yea 2 different Platinums here LOL.

**Comment by shrimpza** [comment]
Should be fixed now: https://unrealarchive.org/authors/aaron-_platinum_-ingersoll.html

**Comment by UnrealGGecko** [comment]
The BT map is by KB|Aids| actually.
