### ISSUE TITLE
[Maps] new entries got labeled as a UT map when it's a Rune map

### ISSUE THREAD

**Issue by UnrealGGecko** [unreal-archive/unreal-archive-data#3145]
A few of the recent batch got labeled as UT maps when they were Rune maps.

https://unrealarchive.org/maps/unreal-tournament/deathmatch/A/dm-arena2p_84e7b8dc.html

https://unrealarchive.org/maps/unreal-tournament/deathmatch/F/dm-firebridge_27b77688.html

https://unrealarchive.org/maps/unreal-tournament/deathmatch/C/dm-ctt-deep_74a55cf9.html

https://unrealarchive.org/maps/unreal-tournament/deathmatch/G/dm-greathall_7e543776.html

**Comment by shrimpza** [comment]
Thanks, fixed.

I think they were maybe made with a newer version of UnrealEd so the package versions appeared more like UT.

Will update to give the .run file extension higher priority.
