### ISSUE TITLE
[Map] CTF-CybridAssault

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#3148]
This is FraGnBraG's Trekw00t - given a different name and different music - no other significant differences from FNB's original that I can see.

---
URL: https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/C/ctf-cybridassault_f9d0e97b.html
Hash: f9d0e97bd1ac7dfe824028ddb8c281ce46a8a446
Current name: CTF-CybridAssault

**Comment by UnrealGGecko** [comment]
https://ut.gamersmafia.com/descargas/6808

Only thing he says it's a remake of CTF-FNB-Trekw00t

**Comment by OjitroC** [comment]
I suppose it depends what one means by 'remake' - the differences are insignificant - nothing has been remade. I would describe it as an edit.

My issue really is with the absence of any explicit credit to the original author - the irony is that the copyright of Rob Burns appears in the map description!!!  Still at least that does indicate where the real credit for this map lies.

**Comment by shrimpza** [comment]
I've flagged this as a variation of Trekw00t, since that's very much what it seems to be.
