### ISSUE TITLE
[Map] CTF-Ephemeral / I am not a programmer, how to add images and descriptions for a map? Thank you

### ISSUE THREAD

**Issue by steph4real** [unreal-archive/unreal-archive-data#3160]
Hi, I am not a programmer, how to add images and descriptions for a map? Thank you

All file (screenshot, readMe) are in the .zip archiver. My map was previously submitted by someone else and I uploaded the latest version (3th place at the Make Something Unreal/CTF).

link:
content/Unreal Tournament 3/Maps/Capture The Flag/E/b/0/8f8bc6/ctf-ephemeral_[b08f8bc6].yml

author: "stephane.p"
description: "A minimalistic yet elegant map located on a monolithic alien temple"
attachments: screenshot
bots: true

**Comment by shrimpza** [comment]
Hello

Your upload should have worked, it looks like there was a bug that it failed to assign some data.

Fixed the bug and updated your map, it should all be here and correct with image:

https://unrealarchive.org/maps/unreal-tournament-3/capture-the-flag/E/ctf-ephemeral_b08f8bc6.html
