### ISSUE TITLE
[Mutator] Heal Link Gun

### ISSUE THREAD

**Issue by zeluisping** [unreal-archive/unreal-archive-data#3211]
I'm the author of this mutator, previously known as 100GPing100 (same author as UT3 Manta)

---
URL: https://unrealarchive.org/mutators/unreal-tournament-2004/H/heal-link-gun_a5b4d62f.html
Hash: a5b4d62f5be3d8c8a6b7e792db8a4986addef436
Current name: Heal Link Gun

**Comment by shrimpza** [comment]
Updated.

Do you want these under "100GPing100" or "zeluisping"?

**Comment by shrimpza** [comment]
Closing due to lack of response.
