### ISSUE TITLE
[Model] steg

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#3229]
This should be categorised under Skins.  Roger McManus is the author of the model; EvilGrins is the author of the skins in this archive.

---
URL: https://unrealarchive.org/models/unreal-tournament/S/steg_bda0368b.html
Hash: bda0368bfa550c11d37cfaee2c21b314771ef2b4
Current name: steg

**Comment by shrimpza** [comment]
Since it includes the original model and suitable .int file, just with additional skins added, I've left it under models, but changed the author to "Roger McManus (skins by EvilGrins)"
