### ISSUE TITLE
[Map-Pack] The Wall Series: labeled as UT when it's for U1

### ISSUE THREAD

**Issue by UnrealGGecko** [unreal-archive/unreal-archive-data#3245]
https://unrealarchive.org/mappacks/unreal-tournament/single-player/T/the-wall-series_8f84bce1.html

Any way to move it from UT to Unreal mappacks section?

**Comment by OjitroC** [comment]
Perhaps there needs to be a slightly more nuanced approach with an indication that maps will 
(1) run only in UnReal;
(2) run in both UnReal and UT;
(3) run only in UT.

There is the added complication with UnReal maps (that applies to the maps in this pack) that some will only run in specific versions - the maps in this pack won't run in 225 for example.

But, yes, you are right - this map pack is intended to run in UnReal as evidenced by the Readme - it is a 'bonus' that 3 of the 4 run in UT as well.

**Comment by shrimpza** [comment]
For simplicity, I've updated it to Unreal. Also closes #3244
