### ISSUE TITLE
[Map] AS-UTOceanFloorOld

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#3252]
Something very odd here - a lot of Leo's conversions of maps made for an early UT version to UT99 have been categorised as being for Unreal.  There are several clues that they are not for Unreal - in this case, for example, there is no Unreal Assault game type (true there is [SP]Assault but that would require the map to have the relevant actors from that game type).

There are 4 DOM maps and, again, there is no Unreal Domination gametype.

The UT prefix to the map names is another clue and the readmes that I have looked at indicate that the conversions are for UT as Unreal weapons have been replaced by UT weapons.

So possibly all the recent additions of maps with the UT prefix in the map or archive title need to be examined more closely?  There are too many for me to look at and raise an Issue on each one.

---
URL: https://unrealarchive.org/maps/unreal/assault/U/as-utoceanfloorold_8b739be8.html
Hash: 8b739be8fb8ee006bc9f3f9424b9550adbbfdea9
Current name: AS-UTOceanFloorOld

**Comment by shrimpza** [comment]
Hmm, interesting.

So I assume the "221 version" in the title of some of these refers to the "source" version - not the intended runtime version?

I changed them all to UT.

**Comment by UnrealGGecko** [comment]
Yes they are conversions from the UT v221, made compatible with current UT versions with their packages + other minor fixes iirc.
