### ISSUE TITLE
[Map Pack] StarGate Fixed Apr 08

### ISSUE THREAD

**Issue by Semfry** [unreal-archive/unreal-archive-data#3253]
This is listed as a Bombing Run set even though it's actually an Unreal 1 Singleplayer/Coop set

---
URL: https://unrealarchive.org/mappacks/unreal/bombing-run/S/stargate-fixed-apr-08_0dcaa757.html
Hash: 0dcaa757a0f039de6e8ffb15cb178387e390f6fb
Current name: StarGate Fixed Apr 08

**Comment by shrimpza** [comment]
fixed
