### ISSUE TITLE
[Map Pack] StargateTL

### ISSUE THREAD

**Issue by Semfry** [unreal-archive/unreal-archive-data#3254]
Like the other Stargate upload this is listed as a Bombing Run set even though it's actually an Unreal 1 Singleplayer/Coop set

---
URL: https://unrealarchive.org/mappacks/unreal/bombing-run/S/stargatetl_cd8787c9.html
Hash: cd8787c9a749e7ea56358e6e00032d44ceeeb766
Current name: StargateTL

**Comment by shrimpza** [comment]
fixed
