### ISSUE TITLE
[GameType] Operation Na Pali 1.30 patched

### ISSUE THREAD

**Issue by Semfry** [unreal-archive/unreal-archive-data#3267]
Unless I'm missing something, given how long this mod has been out it seems a little odd there isn't a fully patched 1.30 download on this site page and you instead need to manually update it, especially as both the Moddb and Unreal Archives links here provide a patched 1.30 version.

Of course I can provide a patched download if needed (as said though, alternative download links provided here already do).

---
URL: https://unrealarchive.org/gametypes/unreal-tournament/O/operation-na-pali/index.html
Hash: None
Current name: Operation Na Pali

**Comment by shrimpza** [comment]
Added the 1.30 repack.

**Comment by Semfry** [comment]
Thank you!
