### ISSUE TITLE
[Mutator] latest OLStats is 3.09

### ISSUE THREAD

**Issue by senneschall** [unreal-archive/unreal-archive-data#3274]
Only [v3.01](https://unrealarchive.org/mutators/unreal-tournament-2004/O/olstats_1148e317.html) can be found.

The latest version is 3.09 and it can be found here (along with all the versions between 3.01 und 3.09): 
https://www.dr-lex.be/software/olstats.html

Upload failed with a 'No new content found' error message, probably because 2 of the 3 .u files inside the archive are identical to 3.01, only `OLStats.u` was changed.

**Comment by shrimpza** [comment]
Added: https://unrealarchive.org/mutators/unreal-tournament-2004/O/olstats_d01c76ad.html
