### ISSUE TITLE
DM-2019 version seperation

### ISSUE THREAD

**Issue by UnrealGGecko** [unreal-archive/unreal-archive-data#3299]
Think the 2 versions of Angelheart's DM-2019 need a seperation. One is for UT99 and the other is for UT2004, they both are labeled as 2k4 right now. https://unrealarchive.org/maps/unreal-tournament/deathmatch/0/dm-2019_6ca9754e.html - UT99 version
https://unrealarchive.org/maps/unreal-tournament-2004/deathmatch/0/dm-2019_ed8ef389.html - UT2004

**Comment by shrimpza** [comment]
Whoops, that's an odd one, thanks!

Fixed.
