### ISSUE TITLE
Announcer section for UT2k4?

### ISSUE THREAD

**Issue by UnrealGGecko** [unreal-archive/unreal-archive-data#3303]
Not really an issue, but since installed announcers in UT2004 are easily selectable, any chance to add a category for them? If not where should be the best place to put them, as currently the system does not recognise them by default.

Some examples:
http://akbalder.free.fr/index.php?page=RandomAnnouncer
https://www.utzone.de/forum/downloads.php?do=file&id=1233_Mortal-Kombat
https://www.utzone.de/forum/downloads.php?do=file&id=4624_Mass-Effect-Aria-Announcer-VoicePack
https://www.utzone.de/forum/downloads.php?do=file&id=4621_Mass-Effect-Grunt-Announcer-VoicePack

**Comment by shrimpza** [comment]
Added: https://unrealarchive.org/announcers/index.html

:smile: 

I probably have a bunch I can batch index amongst the archives I have from various places, but I'm about to be away for a few weeks, so will only be able to try that when I get back.

In the mean time the submission process recognises them with the auto-recognise option, so you can upload whatever you have in the mean time :+1:

**Comment by PootisKorn** [comment]
> I probably have a bunch I can batch index amongst the archives

I'm curious to know if this is still planned.
