### ISSUE TITLE
[Map] MH-AlienQueen][

### ISSUE THREAD

**Issue by bstaghare** [unreal-archive/unreal-archive-data#3318]
"NoSuchKey" and "Key not found" error when attempting to download.  Four maps have this problem:

MH-AlienQueen][
MH-Chef]DS[F - https://unrealarchive.org/maps/unreal-tournament/monster-hunt/C/mh-chefdsfucker_67423c44.html
MH-Dragons][ - https://unrealarchive.org/maps/unreal-tournament/monster-hunt/D/mh-dragons_70e11209.html
MH-Raptors][ - https://unrealarchive.org/maps/unreal-tournament/monster-hunt/R/mh-raptors_823518c6.html

---
URL: https://unrealarchive.org/maps/unreal-tournament/monster-hunt/A/mh-alienqueen_d2ab9c6a.html
Hash: d2ab9c6ac699f5d7ddf52bf68c73d83666c2b99a
Current name: MH-AlienQueen][

**Comment by shrimpza** [comment]
Thanks for the report, that's pretty bad. I have had to delist these as the files seem to have gone missing somehow, during upload.

:cry:
