### ISSUE TITLE
[Map] CTF-Susurrous

### ISSUE THREAD

**Issue by SeriousBuggie** [unreal-archive/unreal-archive-data#3359]
Duplicate of https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/S/ctf-susurrous_4b8f9c7e.html

---
URL: https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/S/ctf-susurrous_62f98122.html
Hash: 62f98122da88f1842142516240d8f8561a6b7de4
Current name: CTF-Susurrous

**Comment by shrimpza** [comment]
Updated, marked as variation
