### ISSUE TITLE
[Map] DM_Northern_winds

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#3363]
This is an Unreal map - it will not run in UT99.

---
URL: https://unrealarchive.org/maps/unreal-tournament/deathmatch/N/dm_northern_winds_c700f568.html
Hash: c700f568c54811112d019ed5fae3e5d7240cd3cb
Current name: DM_Northern_winds

**Comment by shrimpza** [comment]
Thanks, my bad, I updated a couple of maps from a recent batch and missed these. Fixed.
