### ISSUE TITLE
[Map] DM_Gaea

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#3364]
This is an Unreal map - it will not run in UT99.

---
URL: https://unrealarchive.org/maps/unreal-tournament/deathmatch/G/dm_gaea_652c68c6.html
Hash: 652c68c61edaf6867f8b9beb4dfd45fa84ac44b9
Current name: DM_Gaea

**Comment by shrimpza** [comment]
Fixed
