### ISSUE TITLE
[Voice] Blade by Sergeant Todd

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#3372]
The author of this VP is Sergeant Todd.

---
URL: https://unrealarchive.org/voices/unreal-tournament/B/blade-by-sergeant-todd_0c9767ea.html
Hash: 0c9767eadf0b4f09e58dd01ef8ef3e4171b3d869
Current name: Blade by Sergeant Todd

**Comment by shrimpza** [comment]
Fixed
