### ISSUE TITLE
[Voice] Judge Frollo

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#3373]
There is a technical issue with this VP and with most (all?) of those made by this author - the wav files in the VP are in stereo - when using them, the worst case scenario is a game crash - more likely is the distortion of other sounds in the game such as weapon-firing sounds or ambient sounds.

Perhaps it is for other users to decide whether the benefits of using the VPs outweigh the potential downsides - I used to have all this author's VPs but no longer do so. I did contemplate extracting the wav files, converting them to mono and reimporting them but ultimately decided it was not worth the time and effort.

The broader issue for the presentation of 'items' in UA is whether some kind of flag or note is required to indicate known technical issues?

---
URL: https://unrealarchive.org/voices/unreal-tournament/J/judge-frollo_625398c1.html
Hash: 625398c1503a06d8475448706ad66183c19abcbb
Current name: Judge Frollo

**Comment by shrimpza** [comment]
I have added support for "Problem Reports", which will appear near the top of info pages, first one being this voice pack as an example.

These are just links that can link to reports like this, or potentially elsewhere if needed. There can be multiple per item.

I'll link to these reports, but then close them to keep the list of open issues manageable. 

Thanks :tada:
