### ISSUE TITLE
[Voice] Halflife by Sergeant Todd

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#3374]
The author of the VP is Sergeant Todd.

There are a lot of VPs with the file name 'xxxxxx by yyyyyyy' - see Oz, IronManOz, Syrex as well as Sergeant Todd for example - no idea if it is possible, when dealing with VPs, for the software to parse words after 'by' as the name of the author? 

---
URL: https://unrealarchive.org/voices/unreal-tournament/H/halflife-by-sergeant-todd_bbcb035b.html
Hash: bbcb035bd7983f788f38dbb5dc168e95750b26cf
Current name: Halflife by Sergeant Todd

**Comment by shrimpza** [comment]
Will try to support "<thing> by Someone", but for the moment, I've assigned all the things to Sergeant Todd.
