### ISSUE TITLE
[Model] American Psycho

### ISSUE THREAD

**Issue by teringjsntje** [unreal-archive/unreal-archive-data#3380]
this textures seem to contain the correct textures for American Psycho Patrick Batemen but the name of the package is wrong and uses the name of a Starwars character Obiwan. this will cause problems.
![batemen](https://github.com/unreal-archive/unreal-archive-data/assets/57369297/f5c32b06-fdb3-4ffb-bf5b-ee9050987a43)

---
URL: https://unrealarchive.org/models/unreal-tournament/A/american-psycho_01b8fa3a.html
Hash: 01b8fa3a763b95f6b09d7d8745fe43b99c9781cc
Current name: American Psycho

**Comment by shrimpza** [comment]
Linked technical issue.

Thanks :tada:
