### ISSUE TITLE
UT2004 Announcers in the Voices section

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#3411]
Since Unreal Archive now has a dedicated Announcer section, here are some VP's that should be moved there:

[UT3Announcers4UT2004](https://unrealarchive.org/voices/unreal-tournament-2004/U/ut3announcers4ut2004_c6ba1b14.html)
[ut2k6_dma](https://unrealarchive.org/voices/unreal-tournament-2004/U/ut2k6_dma_952787e2.html)
[Halo 4 Announcer](https://unrealarchive.org/voices/unreal-tournament-2004/H/halo-4-announcer_a8c39676.html)
[UC2_Announcer](https://unrealarchive.org/voices/unreal-tournament-2004/U/uc2_announcer_96465191.html)

**Comment by shrimpza** [comment]
Thanks, updated and they're now listed in the announcers section: https://unrealarchive.org/announcers/unreal-tournament-2004/index.html
