### ISSUE TITLE
[Announcer] Halo 4 Announcer

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#3412]
Authors of this Announcer are Hunterman and Tenma_1, not Paul Catalano. Info taken from ReadMe file.

---
URL: https://unrealarchive.org/announcers/unreal-tournament-2004/H/halo-4-announcer_a8c39676.html
Hash: a8c3967653e01ac5543c110de15a379c1a289de8
Current name: Halo 4 Announcer

**Comment by shrimpza** [comment]
Fixed
