### ISSUE TITLE
[Mutator] Damagepopup

### ISSUE THREAD

**Issue by aznlir88** [unreal-archive/unreal-archive-data#3437]
Not sure if that's only me but when I enable this mutator i see only white squares about player , no numbers. Linux amd64 version 3369.2.

Is there any solution to it? I want to add it to my server.
---
URL: https://unrealarchive.org/mutators/unreal-tournament-2004/D/damagepopup_c4e8811d.html
Hash: c4e8811d54183f7c3e099b095819a45f095903de
Current name: Damagepopup

**Comment by shrimpza** [comment]
Closing this as I cannot help resolve the problem, but tagged the mutator with a link to this issue so other people might find it and help.

**Comment by aznlir88** [comment]
Thank you, will test when i have chance. DamagePopup is all I need.
