### ISSUE TITLE
[Map] cDOM-DMP-Condemned

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#3441]
This map is for Classic Domination mod and should be moved [here](https://unrealarchive.org/maps/unreal-tournament-2004/classic-domination/index.html).

---
URL: https://unrealarchive.org/maps/unreal-tournament-2004/domination/D/cdom-dmp-condemned_c1e58770.html
Hash: c1e5877002ad21f3d3e191cd73883ed8d1c91ea2
Current name: cDOM-DMP-Condemned

**Comment by shrimpza** [comment]
Fixed
