### ISSUE TITLE
[Map Pack] JegesBase

### ISSUE THREAD

**Issue by Semfry** [unreal-archive/unreal-archive-data#3442]
The download link here seems to not work? Although maybe it's temporary.

---
URL: https://unrealarchive.org/mappacks/unreal/single-player/J/jegesbase_77533425.html
Hash: 775334258dfcafcf6e0f44e8ddb1f711a1fd1b26
Current name: JegesBase

**Comment by shrimpza** [comment]
Looks like the file there is missing unfortunately, I will remove the listing.

However, the pack is available here: https://unrealarchive.org/mappacks/unreal/single-player/S/sp-jeges-base-series_df5b46b8.html
