### ISSUE TITLE
Creator list: Hide

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#3483]
This is a list that aims to find all Unreal Tournament creations of [Hide](https://unrealarchive.org/authors/hide.html). While some stuff has been properly marked by the website, vast majority of his mods weren't recognized. Mostly his solo works are included in the list. Originally, I wanted to include SkinCity image previews as a bonus, but I have troubles accessing that website (SQL errors). Maybe next time.

UT2004 Models:

JagdTiger: https://unrealarchive.org/models/unreal-tournament-2004/J/jagdtiger_69d4ac0f.html

Marygold: https://unrealarchive.org/models/unreal-tournament-2004/M/marygold_9db3f613.html

Chameleons (indexed under a wrong name): https://unrealarchive.org/models/unreal-tournament-2004/M/mark2_b33093a8.html

LittleEris: https://unrealarchive.org/models/unreal-tournament-2004/L/littleeris_cfd3956c.html
Older variaton: https://unrealarchive.org/models/unreal-tournament-2004/L/littleeris_700286c4.html
UT2k3 variant: https://unrealarchive.org/models/unreal-tournament-2004/L/littleeris_c7593f5c.html

BunnyEris: https://unrealarchive.org/models/unreal-tournament-2004/B/bunnyeris_a9565ecc.html

NekoEris (indexed under a slightly wrong name): https://unrealarchive.org/models/unreal-tournament-2004/N/nekoerist1b_af1e9eef.html

KouRyuu: https://unrealarchive.org/models/unreal-tournament-2004/K/kouryuu_e3d5df70.html
Duplicate: https://unrealarchive.org/models/unreal-tournament-2004/K/kouryuu_a8f7ee85.html

Ageha: https://unrealarchive.org/models/unreal-tournament-2004/A/ageha_ff60e9c5.html

Skylla (indexed under a slightly wrong name): https://unrealarchive.org/models/unreal-tournament-2004/S/skyllaol_dc22b3e6.html

FireDrake: https://unrealarchive.org/models/unreal-tournament-2004/F/firedrake_8229dcf6.html
SkinCity preview: https://skincity.beyondunreal.com/sections/show_model.php?id=487

Calamity (indexed under a slightly wrong name): https://unrealarchive.org/models/unreal-tournament-2004/C/calamityol_0b930710.html

CalamityAngel: https://unrealarchive.org/models/unreal-tournament-2004/C/calamityangel_bea5dbd9.html

Abyss: https://unrealarchive.org/models/unreal-tournament-2004/A/abyss_57350f3a.html
Nude variation of this model is the main variation, which probably shouldn't be the case: https://unrealarchive.org/models/unreal-tournament-2004/A/abyss_7d924acf.html

Tyrant: https://unrealarchive.org/models/unreal-tournament-2004/T/tyrant_40a44b73.html
Repackaged duplicate: https://unrealarchive.org/models/unreal-tournament-2004/T/tyrant_dae1cc6e.html

Popo: https://unrealarchive.org/models/unreal-tournament-2004/P/popo_915d1b90.html

Vanity: https://unrealarchive.org/models/unreal-tournament-2004/V/vanity_41bf0519.html
Duplicate: https://unrealarchive.org/models/unreal-tournament-2004/V/vanity_a3ad2675.html

I've also added one missing model, it is already wrongly indexed: ShinRyuu: https://github.com/unreal-archive/unreal-archive-data/pull/3482/files

Bonus file by Hide and Eklipse - Cats Remix (inexed under a wrong name): https://unrealarchive.org/models/unreal-tournament-2004/F/femminanew_ced117d7.html

UT2004 Skins:

Black and White (indexed under a wrong name and attached to a wrong skin, should be unset): https://unrealarchive.org/skins/unreal-tournament-2004/G/ghost_db5c582b.html

Lion and Hyena (indexed under a wrong name): https://unrealarchive.org/skins/unreal-tournament-2004/L/lippy_bd6a5b82.html

Femmina:  https://unrealarchive.org/skins/unreal-tournament-2004/F/femmina_0241f4a4.html

KouRyuuB: https://unrealarchive.org/skins/unreal-tournament-2004/K/kouryuub_2634751c.html
Duplicate: https://unrealarchive.org/skins/unreal-tournament-2004/K/kouryuub_b38ce5fb.html

KouRyuuC: https://unrealarchive.org/skins/unreal-tournament-2004/K/kouryuuc_1c873e18.html

UT3 Models:

CAT: https://unrealarchive.org/models/unreal-tournament-3/C/cat_26d85e48.html

ShinRyuu: https://unrealarchive.org/models/unreal-tournament-3/S/shinryuu_6c71f54d.html

Already indexed files:

Elektra (this one was made together with Eklipse, he should probably be added to authors): https://unrealarchive.org/models/unreal-tournament-2004/E/elektra_e49ab9d3.html

LittleEris (inexed under a slightly wrong name): https://unrealarchive.org/models/unreal-tournament-2004/L/littleerist2_5bbd3fe2.html

That should be all. Info taken from SkinCity [here](https://skincity.beyondunreal.com/index.php?section=author&subaction=models&id=2) and [here](https://skincity.beyondunreal.com/index.php?section=author&subaction=skins&id=2).

**Comment by shrimpza** [comment]
Wow, nice, thanks.

The Hide page is now full of stuff: https://unrealarchive.org/authors/hide.html

I found some more working pictures on the SkinCity pages too, but FireDrake remains broken.

**Comment by shrimpza** [comment]
My bad, didn't even think of archove.org.

There you go: https://unrealarchive.org/models/unreal-tournament-2004/F/firedrake_8229dcf6.html
