### ISSUE TITLE
[Model] 1 - Angry

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#349]
Your description here

The model name is Tetsuo - 1-Angry is merely one of the skins.
---
Hash: 7cd740ab27becbc8680289c2246098aa3700aad5
Current name: 1 - Angry

**Comment by shrimpza** [comment]
[Fixed](https://unrealarchive.org/models/unreal-tournament/T/tetsuo_7cd740ab.html)
