### ISSUE TITLE
[Model] All Team Colors

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#350]
Your description here

---
Hash: 9366af7eb5bd2d7a58cfe8b2680a2f0360407de6
Current name: All Team Colors

The model is actually Ling (the package name) or more commonly Lingerie Babe (the descriptive name).  All Team Colors is the name of the first skin.  It would probably be better to call the model 'Lingerie Babe' as that makes it easier to find should people be looking for it.

**Comment by shrimpza** [comment]
[Fixed](https://unrealarchive.org/models/unreal-tournament/L/lingerie-babe_9366af7e.html)
