### ISSUE TITLE
[Model] Alpha Male

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#351]
Your description here

---
Hash: c6c09f84e975674b4a8e36b45641dc46c5c8367b
Current name: Alpha Male

The model name is Stick (the package name) or Stickfas (the descriptive name).  Alpha Male is the name of the skin.  Not a major issue but probably better to call it Stick, thus making it easier for people to find should they be looking for it.

**Comment by shrimpza** [comment]
[Fixed](https://unrealarchive.org/models/unreal-tournament/S/stikfas_c6c09f84.html)
