### ISSUE TITLE
UT3 character models section overhaul

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#3526]
This list aims to provide correct names and list authors for UT3 characters and models. Info taken from various readme's, surviving UT websites and a little bit from memory. Searching info became much harder after Epic Games Forums were shutdown.

PART 1:

- [x] Adam (https://unrealarchive.org/models/unreal-tournament-3/A/adam_16cdd566.html): Author - _Anderson Cascardi Pinheiro_
- [x] Alice Beta (https://unrealarchive.org/models/unreal-tournament-3/A/alice-beta_7f8efc89.html) : Author - _Michel "INVICTRA" Љpoljar_
- [x] Alien (https://unrealarchive.org/models/unreal-tournament-3/A/alien_f912135f.html): Name was incorrectly indexed, should be **Alien & Tribalien**
- [x] Alien (https://unrealarchive.org/models/unreal-tournament-3/A/alien_d1d97086.html): Name was incorrectly indexed, should be **AlienVsPredator Models Pack**
- [x] Anubis (https://unrealarchive.org/models/unreal-tournament-3/A/anubis_1e898128.html): Name was incorrectly indexed, should be **Smite Character Pack**
- [x] Balrog (https://unrealarchive.org/models/unreal-tournament-3/B/balrog_0da8555e.html): Name was incorrectly indexed, should be **Lord of the Rings Models pack**
- [x] BE Heavy (https://unrealarchive.org/models/unreal-tournament-3/B/be-heavy_55cf151c.html): Name was incorrectly indexed, should be **Tribes: Ascend Models Pack**
- [x] Bender (https://unrealarchive.org/models/unreal-tournament-3/B/bender_ab4a5286.html): Author - _Waz (Justin Wasilenko)_
- [x] BigSister (https://unrealarchive.org/models/unreal-tournament-3/B/bigsister_2db125bd.html): Name was incorrectly indexed, should be **BioShock Models Pack**
- [x] Blip (https://unrealarchive.org/models/unreal-tournament-3/B/blip_a630dcf5.html): Author - _Karl Peel_
- [x] BumbleBee (https://unrealarchive.org/models/unreal-tournament-3/B/bumblebee_2d06f469.html): Name was incorrectly indexed, should be **Transformers V2**
- [x] Rodents, Mice and Bunnys (https://unrealarchive.org/models/unreal-tournament-3/R/rodents-mice-and-bunnys_bb90784b.html): here's an incorrectly indexed older version, that should be a variation of the main file: https://unrealarchive.org/models/unreal-tournament-3/B/bunny_2f7012e4.html
- [x] Captain Juno (https://unrealarchive.org/models/unreal-tournament-3/C/captain-juno_9b1be55a.html): Name was incorrectly indexed, should be **Star Wars Models Pack V3**
- [x] CH_Abaddon_Model (https://unrealarchive.org/models/unreal-tournament-3/C/ch_abaddon_model_99f2e0f0.html): Name was incorrectly indexed, should be **Abaddon Head** (this is a character accessory)
- [x] CH_Alios_04 (https://unrealarchive.org/models/unreal-tournament-3/C/ch_alios_04_332b6313.html): Name was incorrectly indexed, should be **Alios**
- [x] Cheburashka (https://unrealarchive.org/models/unreal-tournament-3/C/cheburashka_f79a9fe4.html): Author - _SDX-LV_
- [x] Cloud_and_Zack__PC__V2 (https://unrealarchive.org/models/unreal-tournament-3/C/cloud_and_zack__pc__v2_340bfb3a.html): Name was incorrectly indexed, should be **Cloud & Zack**
- [x] Crusader (https://unrealarchive.org/models/unreal-tournament-3/C/crusader_2ff40c6f.html): Author - _RuneStorm_
- [x] Crysis (https://unrealarchive.org/models/unreal-tournament-3/C/crysis_2993ca17.html): Author - _EvilEngine_
- [x] damarus_ut3 (https://unrealarchive.org/models/unreal-tournament-3/D/damarus_ut3_33ffd895.html): Name was incorrectly indexed, should be **Damarus**. Author - _ChaZcaTriX_
- [x] EarthWorm Jim (https://unrealarchive.org/models/unreal-tournament-3/E/earthworm-jim_013f465c.html): Author - _TheAntiYou_
- [x] Faraleth_B (https://unrealarchive.org/models/unreal-tournament-3/F/faraleth_b_ba0a54f3.html): Name was incorrectly indexed, should be **Faraleth**. Author - _kobra_k88 (Khoa Nguyen)_
- [x] ForeverDuke (https://unrealarchive.org/models/unreal-tournament-3/F/foreverduke_cb382638.html): Name was incorrectly indexed, should be **Duke Nukem Models Pack**
- [x] Harly Elite (https://unrealarchive.org/models/unreal-tournament-3/H/harly-elite_39727c23.html): Name was incorrectly indexed, should be **Assassin's Creed Model Pack**
- [x] Hel (https://unrealarchive.org/models/unreal-tournament-3/H/hel_4b76b559.html): Author - _RuneStorm_
- [x] Homer (https://unrealarchive.org/models/unreal-tournament-3/H/homer_5ea3f766.html): Author - _Paul Mahoney_
- [x] Hulk (https://unrealarchive.org/models/unreal-tournament-3/H/hulk_ef69e3c9.html): Author - _Anderson Cascardi Pinheiro_
- [x] Hyora (https://unrealarchive.org/models/unreal-tournament-3/H/hyora_41c8c883.html): Author - _Chris Lee_
- [x] IK_BARNAKAS (https://unrealarchive.org/models/unreal-tournament-3/I/ik_barnakas_e5d6b97c.html): Name was incorrectly indexed, should be **IK-Beester-Skin-Pack**. Author - _Francis Briau_
- [x] Infiltrator (https://unrealarchive.org/models/unreal-tournament-3/I/infiltrator_5c91f799.html): Name was incorrectly indexed, should be **Terminator**
- [x] Ironman (https://unrealarchive.org/models/unreal-tournament-3/I/ironman_36b93bc4.html): Name was incorrectly indexed, should be **Avengers Model Pack v 2.0**
- [x] Jaca (https://unrealarchive.org/models/unreal-tournament-3/J/jaca_22ce5499.html): Name was incorrectly indexed, should be **Polar and Dumon Soldiers**. Auhtor - _Rodrigo Banzato_
- [x] Jack (https://unrealarchive.org/models/unreal-tournament-3/J/jack_3bd7cf80.html): Name was incorrectly indexed, should be **Jack Skellington**
- [x] JC Denton beta2 (https://unrealarchive.org/models/unreal-tournament-3/J/jc-denton-beta2_7aaa3d8b.html): Author - _SDX-LV_
- [x] July (https://unrealarchive.org/models/unreal-tournament-3/J/july_f46f7a04.html): Author - Aberiu. Repackaged duplicate: https://unrealarchive.org/models/unreal-tournament-3/J/july_65121dee.html
- [x] K-Rod_2k8_UT3 (https://unrealarchive.org/models/unreal-tournament-3/K/k-rod_2k8_ut3_3efaf136.html): Name was incorrectly indexed, should be **K-Rod**
- [x] KaT (https://unrealarchive.org/models/unreal-tournament-3/K/kat_4cf9c44d.html): Older version, that should be a varation: https://unrealarchive.org/models/unreal-tournament-3/K/kat_72f83d10.html
- [x] Kerrigan (https://unrealarchive.org/models/unreal-tournament-3/K/kerrigan_0bb476a2.html): Author - _Albatr0s_
- [x] Leksa (https://unrealarchive.org/models/unreal-tournament-3/L/leksa_333748a7.html): Author - _Matthew Hall (TortillaChips)_

_edited by @shrimpza to be a checklist_

**Comment by PootisKorn** [comment]
PART 2:

Linna (https://unrealarchive.org/models/unreal-tournament-3/L/linna_de4873b7.html): Name was incorrectly indexed, should be **BubbleGum Crisis Pack**. Author - _kobra_k88 (Khoa Nguyen)_

Lizard Warrior Brown (https://unrealarchive.org/models/unreal-tournament-3/L/lizard-warrior-brown_58e60536.html): Name was incorrectly indexed, should be **Vindictus Lizardman**

M Paladin (https://unrealarchive.org/models/unreal-tournament-3/M/m-paladin_6f191b09.html): Name was incorrectly indexed, should be **Knight Paladins**

Malcolm (https://unrealarchive.org/models/unreal-tournament-3/M/malcolm_774cc753.html): Incorrect author. Correct one - _Jochen "Slaughter" Bremer_ (or just _Slaughter_)

Miyuki (https://unrealarchive.org/models/unreal-tournament-3/M/miyuki_26c8df2f.html): Author - _Mel_Danes 2008_

Nova Terra (https://unrealarchive.org/models/unreal-tournament-3/N/nova-terra_d7ab8063.html): Author -  _urPackage_

nyota-ut3 (https://unrealarchive.org/models/unreal-tournament-3/N/nyota-ut3_25bf2867.html): Name was incorrectly indexed, should be **Nyota**. Author - _Apoptoid_

Orks (https://unrealarchive.org/models/unreal-tournament-3/O/orks_a7af0d4f.html): Authors - _Johannes "Fraeger" Boehm and MisterTrioxin_

Orthos (https://unrealarchive.org/models/unreal-tournament-3/O/orthos_3a19b210.html): Author - Apoptoid

Queen Myrrah (https://unrealarchive.org/models/unreal-tournament-3/Q/queen-myrrah_4b2cf20a.html): Name was incorrectly indexed, should be **GirlsofGears Models Pack V2**

Rankin (https://unrealarchive.org/models/unreal-tournament-3/R/rankin_bd684608.html): Author - _Chris Lee_

Rose (https://unrealarchive.org/models/unreal-tournament-3/R/rose_0d06de8d.html): Name was incorrectly indexed, should be **Rose Lotus**. Author - _Jusagi~_

RuneStorm Skeleton (https://unrealarchive.org/models/unreal-tournament-3/R/runestorm-skeleton_2d3d70de.html): Author - _RuneStorm_

RuneStorm Zombie (https://unrealarchive.org/models/unreal-tournament-3/R/runestorm-zombie_1607a38b.html): Author - _RuneStorm_

SC Camo (https://unrealarchive.org/models/unreal-tournament-3/S/sc-camo_d904881e.html): Name was incorrectly indexed, should be **StarCraft Marines**

selig_motig_remake_ut3_models (https://unrealarchive.org/models/unreal-tournament-3/S/selig_motig_remake_ut3_models_57a7ad3d.html): Name was incorrectly indexed, should be **Selig and Motig**. Author - _ChaZcaTriX_

Siegfried (https://unrealarchive.org/models/unreal-tournament-3/S/siegfried_5eb8845f.html): Author - _Albatr0s_

Sister of Battle (https://unrealarchive.org/models/unreal-tournament-3/S/sister-of-battle_06f3523d.html): Author -  _Ivan "iWaNN" Grudinin_ 

Skaarj (https://unrealarchive.org/models/unreal-tournament-3/S/skaarj_000b0f96.html): Name should probably be changed to UT3 Skaarj. Author - _EvilEngine_

Solkova (https://unrealarchive.org/models/unreal-tournament-3/S/solkova_dff05eda.html): Name was incorrectly indexed, should be **General Solkova**. Author - _Bartosz Danielak_

Spartan (https://unrealarchive.org/models/unreal-tournament-3/S/spartan_c893b0e7.html): Name was incorrectly indexed, should be **Halo Spartan**. Author - _EvilEngine_

Spawn (https://unrealarchive.org/models/unreal-tournament-3/S/spawn_f55abc6a.html): Author - _EvilEngine_

Starcraft 2 (https://unrealarchive.org/models/unreal-tournament-3/S/starcraft-2_59316cb9.html): Name was incorrectly indexed, should be **Starcraft Terran Marine**. Author - _Discmage_

Strapped_model01 (https://unrealarchive.org/models/unreal-tournament-3/S/strapped_model01_b9a5373b.html): Name was incorrectly indexed, should be **Strapped**

Sun Kralls (https://unrealarchive.org/models/unreal-tournament-3/S/sun-kralls_652066c6.html): Author - _Thomas "MacTom27" Veyrat_

Tarja (https://unrealarchive.org/models/unreal-tournament-3/T/tarja_04c994c7.html): Author - Andrй T. "erter" Johansen

Terminator_old (https://unrealarchive.org/models/unreal-tournament-3/T/terminator_old_684bf6b0.html): Name was incorrectly indexed, should be **T800 Terminator**. Author - _EvilEngine_

Tritigon (https://unrealarchive.org/models/unreal-tournament-3/T/tritigon_a9bc01b2.html): Author -  _Jason Cecrle_

U2 Skaarj (https://unrealarchive.org/models/unreal-tournament-3/U/u2-skaarj_8bc7fd74.html): Author - _EvilEngine_

Xan_model_EE_beta1.4-12.7 (https://unrealarchive.org/models/unreal-tournament-3/X/xan_model_ee_beta14-127_4391b95c.html): Name was incorrectly indexed, should be **Xan Kriegor**. Author - _EvilEngine_

Xenohuman (https://unrealarchive.org/models/unreal-tournament-3/X/xenohuman_64264dc8.html): Author - _EvilEngine_. Duplicate: https://unrealarchive.org/models/unreal-tournament-3/X/xenotype1_9cf9cb7c.html

**Comment by shrimpza** [comment]
All done.

Thanks for all that, the section should be looking a lot more coherent now :)
