### ISSUE TITLE
[Model] StarCraft Marines

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#3543]
This is RuneStorm Zombie and this model packs needs it's name back. The actual StarCraft Marines [are over here](https://unrealarchive.org/models/unreal-tournament-3/S/sc-camo_d904881e.html).

---
URL: https://unrealarchive.org/models/unreal-tournament-3/S/starcraft-marines_1607a38b.html
Hash: 1607a38b0ba5d8d70d2dba9665ec3d5ccd0269b4
Current name: StarCraft Marines

**Comment by shrimpza** [comment]
Whoops, thanks for that, seems I messed that one up.

Should be fixed now :+1: .
