### ISSUE TITLE
[Model] Athena

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#3552]
I missed this model pack when doing UT3 models section overhall, it's name should be _Borderlands Female Models Pack_.

---
URL: https://unrealarchive.org/models/unreal-tournament-3/A/athena_b1a5eaf6.html
Hash: b1a5eaf60a34295e30598ab4858f87039a50c6eb
Current name: Athena

**Comment by shrimpza** [comment]
Fixed
