### ISSUE TITLE
[Voice] Konoko

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#3654]
This is a duplicate of a VP that is already on UA - there are, in fact, 2 copies of the VP (one is a stand-alone VP and the other is bundled with the Konoko model).

The archive here contains Mac system files (because it was created on a Mac) - these are not required for the VP to work.  The stand-alone VP archive does not contain these.  

I would suggest that there is no point in keeping this duplicate partly because it is a duplicate and because the unnecessary files may cause confusion to users.

---
URL: https://unrealarchive.org/unreal-tournament/voices/K/konoko_960fd75e.html
Hash: 960fd75e19fc8762b789c19f19b51c2e0365b14b
Current name: Konoko

**Comment by shrimpza** [comment]
Awesome, thank you. Will clean this one up.

There have been a lot of duplicate submissions recently (already removed dozens), but they all have slightly different contents or author strings, so they show but differently. But checking some of the content hashes and sizes it's normally the same stuff with extra fluff repackaged :disappointed:

**Comment by shrimpza** [comment]
Only [this one remains](https://unrealarchive.org/unreal-tournament/voices/K/konoko_f251ac61.html)
