### ISSUE TITLE
[UT3] Entries and Intros map section

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#3700]
[Entries and Intros](https://unrealarchive.org/unreal-tournament-3/maps/entries-and-intros/index.html) section should be renamed to Movies, Machinimas and Entries, like it's [UT2004 counterpart](https://unrealarchive.org/unreal-tournament-2004/maps/movies-machinimas-and-entries/index.html).

**Comment by shrimpza** [comment]
Fixed
