### ISSUE TITLE
[Map] dm-The-Box-MSUC

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#3701]
This is an unplayable cinematic and should be moved [here](https://unrealarchive.org/unreal-tournament-3/maps/entries-and-intros/index.html).

---
URL: https://unrealarchive.org/unreal-tournament-3/maps/deathmatch/T/dm-the-box-msuc_b3669b70.html
Hash: b3669b70a1df127724f2f68a7fe3408b792633a4
Current name: dm-The-Box-MSUC

**Comment by PootisKorn** [comment]
This map may or may not need the [following files](https://www.mediafire.com/?jtfhlvbf29t18ne) for it's use.

**Comment by shrimpza** [comment]
Fixed and linked file
