### ISSUE TITLE
[Map] DM-RebirthCinematic

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#3702]
This is an unplayable cinematic and should be moved [here](https://unrealarchive.org/unreal-tournament-3/maps/entries-and-intros/index.html).

---
URL: https://unrealarchive.org/unreal-tournament-3/maps/deathmatch/R/dm-rebirthcinematic_cc1a8721.html
Hash: cc1a87213432c28696e6bee8848a8a713c0cf92d
Current name: DM-RebirthCinematic

**Comment by shrimpza** [comment]
Fixed
