### ISSUE TITLE
[Map] DM-Assault

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#3703]
This is an unplayable cinematic and should be moved [here](https://unrealarchive.org/unreal-tournament-3/maps/entries-and-intros/index.html).

---
URL: https://unrealarchive.org/unreal-tournament-3/maps/deathmatch/A/dm-assault_49f6205e.html
Hash: 49f6205e3254d8d759522797318dd5832f89ae69
Current name: DM-Assault

**Comment by shrimpza** [comment]
Fixed
