### ISSUE TITLE
[Map] DM-ThePlan-MSUC-final

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#3704]
This is an unplayable cinematic and should be moved [here](https://unrealarchive.org/unreal-tournament-3/maps/entries-and-intros/index.html).

---
URL: https://unrealarchive.org/unreal-tournament-3/maps/deathmatch/T/dm-theplan-msuc-final_6bad6719.html
Hash: 6bad67192ce6d8849d0fe3715a491628850b8c0a
Current name: DM-ThePlan-MSUC-final

**Comment by PootisKorn** [comment]
Also, map appears to be missing crucial files, which can be found [here](https://www.mediafire.com/?jtfhlvbf29t18ne).

**Comment by shrimpza** [comment]
Fixed.

I also added MOVIE TOYS as a "mutator" even though it's not, but at least captures the file and its packages for later use.
