### ISSUE TITLE
[Map] VTCF-LightMapTest

### ISSUE THREAD

**Issue by PootisKorn** [unreal-archive/unreal-archive-data#3705]
This map was created for testing purposes and should be moved [here](https://unrealarchive.org/unreal-tournament-2004/maps/tests-and-demos/index.html).

---
URL: https://unrealarchive.org/unreal-tournament-2004/maps/unknown/V/vtcf-lightmaptest_ad195ca5.html
Hash: ad195ca5ca187a806cc905ee9ded692a50e90755
Current name: VTCF-LightMapTest

**Comment by shrimpza** [comment]
Fixed
