### ISSUE TITLE
[Map Pack] Feuersturm's UT2004 2016 Mappack Vol 1

### ISSUE THREAD

**Issue by VirgileVILE** [unreal-archive/unreal-archive-data#3721]
"Unreal Archive US" doesn't seem to work, which is annoying since it's the only link:
```
try { Object.defineProperty(navigator, "globalPrivacyControl", { value: false, configurable: false, writable: false }); document.currentScript.parentElement.removeChild(document.currentScript); } catch(e) {};
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>Key not found</Message>
</Error>
```

---
URL: https://unrealarchive.org/unreal-tournament-2004/mappacks/mixed/F/feuersturms-ut2004-2016-mappack-vol-1_9e1f3be0.html

**Comment by shrimpza** [comment]
Oops, fixed.

**Comment by UnrealGGecko** [comment]
Was found from here:
https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa21YSWVIb0ktd2RIdXNteWNQWXh1aUcyX05zd3xBQ3Jtc0ttSC1ERzA4dmp1X1FUUE9ERGZpdXVBT3RGQWFrbE5CZS1DTDJsQTBOcEFzZElEanIwYm9pbFQ5SzFqdUlIRXFObTZGb3Juckx4ZU5mam5zRGtmWi1SNVMtZW53YkpfX2dkeEV0SnQ0LS1rUzFIaTk2cw&q=https%3A%2F%2Fdrive.google.com%2Ffile%2Fd%2F0B_UjgQmyIx_aYXl5M1piUnhoQ1k%2Fview%3Fusp%3Dsharing%26resourcekey%3D0-tj5eCv72HMPfnxqCnbp1GQ&v=zG3JSDGqVEQ

Links was from one of his videos descriptions, as he has showcase videos of many of his maps:
https://m.youtube.com/@UEMFeuersturm
