### ISSUE TITLE
[Voice] Sceptre

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#3730]
Is this 'VP' worth keeping?  The archive lacks the voice clips and so the voice pack is not a VP in any meaningful and practical way.

---
URL: https://unrealarchive.org/unreal-tournament/voices/S/sceptre_ec9ce7ad.html
Hash: ec9ce7adaf93c301ef500da80753f467f243b45e
Current name: Sceptre

**Comment by UnrealGGecko** [comment]
Found from here:
https://www.unrealsp.org/forums/viewtopic.php?f=6&t=4634

That's how it came in, mightve forgot the sound file or something.

**Comment by shrimpza** [comment]
Ive delisted it.

I see the file is listed as being 5kb on that page as well, so I guess it's broken out the gate.

I can't spot `ForsakenVoiceSound` anywhere else either, so perhaps its just old and broken.
