### ISSUE TITLE
[Skin] Project-Myhaen

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#3731]
This is actually for UT99 - stated in the Readme and clear from the format of the files.

Odd that it was parsed as Unreal Tournament 2004?

---
URL: https://unrealarchive.org/unreal-tournament-2004/skins/P/project-myhaen_a5f9285e.html
Hash: a5f9285e51b50a4ca9496472b5e9444f21960414
Current name: Project-Myhaen

**Comment by shrimpza** [comment]
It decided it's UT2004 based on the package version: which says it's 126. Usually the engine/package version is < ~68 for Unreal and < ~117 for UT. 

126 pushed it into UT2004 territory.

Fixed.
