### ISSUE TITLE
[Model] Pilot-Girl-A01

### ISSUE THREAD

**Issue by trkt91** [unreal-archive/unreal-archive-data#3768]
I am the submitter of this model, and unfortunately, I only realized after submitting that it relies on another file that is not packaged with it. So, it doesn't work properly.

I since then submitted this with the fixed files ( piloteris-1-1zip_45e27e32 #3761 ).

Can this one be removed? Thank you.

---
URL: https://unrealarchive.org/unreal-tournament-2004/models/P/pilot-girl-a01_9d38b76b.html
Hash: 9d38b76b6cdebed0e77098cd4a77e152203b1532
Current name: Pilot-Girl-A01

**Comment by shrimpza** [comment]
Done, removed (link still valid, but removed from listing etc). 

Replaced with the new submission.

https://unrealarchive.org/unreal-tournament-2004/models/P/pilot-eris_e95461c2.html
