### ISSUE TITLE
[Map] DM-(Mob)-Confinery-V1

### ISSUE THREAD

**Issue by jriv193** [unreal-archive/unreal-archive-data#3780]
I am the creator of this map. Should be categorized as Game Type Invasion
Thank you

---
URL: https://unrealarchive.org/unreal-tournament-2004/maps/deathmatch/M/dm-mob-confinery-v1_84a5aabc.html
Hash: 84a5aabcd549a4886472c754009a27ac4196ba4e
Current name: DM-(Mob)-Confinery-V1

**Comment by shrimpza** [comment]
Fixed
