### ISSUE TITLE
[Map Pack] Cxp Final U2xmp

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#379]
---
Hash: 2064170948b94f69bd33cfdfb0c8b9232b045f11
Current name: Cxp Final U2xmp

--------------------
This map pack and the other two XMP packs are not for Unreal Tournament but for Unreal 2 (XMP).

**Comment by shrimpza** [comment]
Thanks for the report, these are now listed under U2 XMP!
