### ISSUE TITLE
[Model] Visor

### ISSUE THREAD

**Issue by teringjsntje** [unreal-archive/unreal-archive-data#3816]
proper preview  mayby  i could try to make proper previews for the custom characters if you like. like this example. alot of models dont have one. (this is a quake 3 character ported to UT99 i think)
<img width="256" alt="visor" src="https://github.com/user-attachments/assets/0093842d-55d0-4182-85dd-9b6116185f17">

i made a few that where pictureless

https://ut99.org/ut99.org/viewtopic.php?t=16575
 https://www.mediafire.com/file/1i0q7zdl2xuevfk/VandW.7z/file

---
URL: https://unrealarchive.org/unreal-tournament/models/V/visor_49bfccd2.html
Hash: 49bfccd25062a2d5bb6aa83c63fbb2049a6be096
Current name: Visor

**Comment by shrimpza** [comment]
Thanks, these have been updated :)
