### ISSUE TITLE
[Map] DM-Hot Station

### ISSUE THREAD

**Issue by esnesi** [unreal-archive/unreal-archive-data#420]
Your description here
Filename contains a space, therefore not rightly send through redirect.
When manually removed, all works correctly.

---
Hash: 784b9c8efe1bc6383c2d878843663e84331a259d
Current name: DM-Hot Station

**Comment by shrimpza** [comment]
I cannot rename the source file, as that's the way it was released. Would be up to server admins to ensure this works properly on their setups with redirects...
