### ISSUE TITLE
[Model] soria

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#480]
Hash: 8bf57cbcc3d93de02fbf00fa679f664ff4106353
Current name: soria

According to the readme the author is Jason "Zieroth" Kim

Note : appears to be a collaboration as the readme says "Rigged and imported by Warbeast, UT2004 team colors, and finishing animation by Etienne".

**Comment by shrimpza** [comment]
Fixed with author as 'Jason "Zieroth" Kim'.

Need to consider some additional functionality to support "additional credits" and stuff.

**Comment by OjitroC** [comment]
"Need to consider some additional functionality to support "additional credits" and stuff."

That's going to difficult - for example, in deciding what kind of 'stuff' deserves a credit.  Looking through readmes, people credit others for a variety of things - just looked at ValAvatar and there are several people given thanks by the main author, including someone for suggesting part of the mutator's name. Personally I think it would introduce a good deal of complication - if people are interested they can get that information from readmes.
