### ISSUE TITLE
[Model] Kim

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#481]
Hash: 1a7cfb7a88135c9a87cb6444828c0ced4509728a
Current name: Kim

According to the readme, the author is William "Ok-Billy"

Everything in the readme refers to UT2003 so looks like it isn't a UT2k4 model.

**Comment by shrimpza** [comment]
Fixed.

UT2003 content is all grouped under UT2004 - there's no explicit UT2003 game on the system, it's bundled under UT2004 since it's usable under the newer game.
