### ISSUE TITLE
[Map] CTF-(ASS)-AGOURA_BURNER

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#490]
Hash: ae68d1db6fc5b51feb18e9e45d87deca257f4a9b
Current name: CTF-(ASS)-AGOURA_BURNER

According to the readme, the authors are (A.S.S)Agoura_Steve and (A.S.S)Banshee

Mostly the latter says a note in the readme.

**Comment by shrimpza** [comment]
Fixed
