### ISSUE TITLE
[Map] CTF-(ASS)-AGOURA_BURNER

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#491]
Hash: 048a8d0c92aaf0bb1bd239c383bd21a8dd47fa88
Current name: CTF-(ASS)-AGOURA_BURNER

As per the other identical map of this name, the authors are (A.S.S)Agoura_Steve and (A.S.S)Banshee.

**Comment by shrimpza** [comment]
Fixed
