### ISSUE TITLE
[Mutator] TheDanes ControlPoints

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#504]
Hash: 5424720ada034544312ddabef75b001efa4ed269
Current name: TheDanes ControlPoints

This mutator, along with all the others starting The Danes and Danes, was made by TheDane.

TheDane aka
The|CRAZY|Dane 
[DANISH]TheDane
(AMLP)TheDane
[AMLP]TheDane
.:THeDane:.
Remixed TheDane

**Comment by shrimpza** [comment]
Fixed, and added authors aliases, thanks :+1:.
