### ISSUE TITLE
[Mutator] goChristmasLights

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#505]
Hash: 2dd0e50f0cb8238e3e75ddc3de77d16e44a07682
Current name: goChristmasLights

Odd where the author name for this came from.  The readme is 'signed' Kelly with "gopostal" underneath.  The go prefix in the mutator name indeed suggests it was made by gopostal.

I would suggest the author should be gopostal and not Dane.

Dane is credited for some models and six or seven other people receive credits for various inputs.

As an aside, in unzipping the archive I got a warning that it was corrupt and most/all of the .wav files in the archive could not be decompressed - so it might be worth checking to see if this mod/mutator is actually fully useable.

Which raises the quesiton - should there be some indication on a item page that the hosted content is corrupt in some way or otherwise not wholly useable?

**Comment by shrimpza** [comment]
On the archive integrity - interesting. I just extracted this without an issue. File listings and integrity checks (using `7z`) all seem to check out... All the WAV files seem to have decompressed without a problem and spot-checking a couple of them seems like they're playable/valid.

Updated the author.

**Comment by OjitroC** [comment]
OK - I used my Mac's Unarchiver so it looks like it doesn't decompress everything correctly or, more specifically doesn't decompress .wav files correctly.  I have noticed that before on occasion but thought it was a problem with an archive - I now know to use 7z if it happens in future.  Thanks.
