### ISSUE TITLE
[Map] DM-(AMLP)Casino

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#513]
Hash: faba4185d03c9382a65fe06d02dd928184eb5572
Current name: DM-(AMLP)Casino

According to the readme, the author is StÈphanie ... aka ... [AMLP]Hanibal 

The screenshot says by  [AMLP]Hanibal

So probably best to have the latter as author and if there are maps by StÈphanie to put them under [AMLP]Hanibal

**Comment by shrimpza** [comment]
Updated and added alias
