### ISSUE TITLE
[Map] DM-ADAM

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#515]
Hash: f077f31c43298492b9956a8a99de0ca698169969
Current name: DM-ADAM

Looks like the author is adam sims
this is at the top of the readme

The author's email name is dioxidem_7 which may or may not be used as an author name as well (haven't checked for that)

**Comment by OjitroC** [comment]
This is the same author as Adam Sims aka Oblivion_Soldier
The email name and address are the same

**Comment by shrimpza** [comment]
Updated to Adam Sims aka Oblivion_Soldier
