### ISSUE TITLE
[Map Pack] DM FIFA2010

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#521]
Hash: f740f34c53403e6dc837d8cfe09d0d4daaadb6f7
Current name: DM FIFA2010

The author of this map pack normally and more commonly used the name Myth

[verified from the readme for this map pack and from readmes for maps by Myth - maxuser6000 being his email name.

So need an author alias for Myth
1 Myth
2 maxuser6000

**Comment by shrimpza** [comment]
Updated, and added alias.
