### ISSUE TITLE
[Map] DM-Anitt

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#525]
Hash: 42f76d7ae6a1d863bb813ff72ed2cd5165ad3587
Current name: DM-Anitt

Since this is exactly the same map as DM-Anitta and the author of that map is Chris Halford, then the author of this map is also Chris Halford

**Comment by shrimpza** [comment]
Flagged as deleted, since it's definitely the same but lacks the readme.
