### ISSUE TITLE
[Map] DM-Babylon][Arena

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#538]
Hash: 7f5cf6510977afeaf246a1e4059484b63e7e3f8c
Current name: DM-Babylon][Arena

According to the readme, the author's name is Stefan [S-Dot] Doetschel
He may also appear as simply S-Dot as that is the name on the screenshot.

Recommended no. of Players = 2-6

**Comment by shrimpza** [comment]
Updated, and added aliases for `Stefan [S-Dot] Dötschel`, `Stefan [S-Dot] Doetschel` and `S-Dot`.
