### ISSUE TITLE
[Map] DOM-DRMBarn

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#540]
Hash: 5027bb54a7bc84b1396dab9c4d7d0b69f1706aae
Current name: DOM-DRMBarn

According to the readme, the author is Dustin 'dremoan' Fair
so Dremoan is an alternative name for this author

Requires an alias file
1 Dustin (Dremoan) Fair
2 Dremoan
3 Dustin 'dremoan' Fair

**Comment by shrimpza** [comment]
Updated, added aliases.
