### ISSUE TITLE
[Mutator] Samurai

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#541]
Hash: 1a5ec9f8cca51a001e98306d1cbda00d32cf399c
Current name: Samurai

The author's name, according to the readme, is Gareth Tamplin

Note : all the 'mutators' are weapons.

**Comment by shrimpza** [comment]
Updated author.

I see the int file only lists the mutators, not the weapon classes, so they're not found.

Weapons in the int file would allow for weapon ordering, keybinds, etc, but I guess this author didn't add that.
