### ISSUE TITLE
[Map] DM-battledrome

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#546]
Hash: 5dc3c1641f6a9ac2495b606d041a9dc97c78ae2c
Current name: DM-battledrome

According to the readme, the authors are SnowTiger and Smiley
These are the same people as the authors of DM-Battledrome-A where in the readme they appeared as Smiley & SnowTiger.  Battledrome-A is an updated version of Battledrome

**Comment by shrimpza** [comment]
Updated and flagged as variation.
