### ISSUE TITLE
[Map] dm-bombardment

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#554]
Hash: d86c92522616d7b29842838febbf0ca7a785ac66
Current name: dm-bombardment

Oddly, there's no Packaged Files info for this one

**Comment by shrimpza** [comment]
Seems like the map file may be invalid (I haven't tried playing it), or there's a bug with the code which reads map data, since it can't interrogate the UNR file for information, so it's bombing.

**Comment by shrimpza** [comment]
OK so the map extracts with no read permissions for the owner, so it cannot be opened (by UT or the UA package reader) without manually assigning read permissions.

I'll leave this open for the moment, and will see if there's similar instances elsewhere, as it will require a workaround.

**Comment by OjitroC** [comment]
I think I have seen two or three similar instances - I have a feeling I didn't report them all.

**Comment by shrimpza** [comment]
Linked issue as a probably Linux packaging issue.
