### ISSUE TITLE
[Map] DM-BULL_PolarisSE

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#565]
Hash: 82381204093410bec353a521d7701f23236720ab
Current name: DM-BULL_PolarisSE

This is a map where the Author name under Map Information is truncated.  It appears as 	-={SDA}=  but hold the cursor over that and one sees what should be the full entry.

This is another BullDozer map.

**Comment by shrimpza** [comment]
Fixed by adding full name to aliases.
