### ISSUE TITLE
[Map] DMBallisticTest

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#570]
Hash: 04ca1d82ef5cbd377a0b3cbbdafb3f184ef69b25
Current name: DMBallisticTest

This isn't a DM map despite the prefix but it is a Ballistic Test map - I think it is to test the capability of weapons to penetrate a solid object and destroy wooden boxes behind what appears to be solid (rather than breakable) glass or perspex.  So an Enforcer won't penetrate the solid screen but Counter Strike weapons will.

**Comment by shrimpza** [comment]
I've set the gametype to Tests and Demos, seems appropriate given the description.
