### ISSUE TITLE
[Map] DM-(Chaos_Snake)SniperTest

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#571]
Hash: 1e27f8fd1d202c0f85c4d3e82c85fb445107025e
Current name: DM-(Chaos_Snake)SniperTest

The author is Chaos_Snake

The map is not a DM map despite the prefix but a Test or Demo map - it contains a number of different sniper rifles firing different kinds of projectiles (from rockets and flak to dispersion and shock projectiles) all made by Chaos_Snake.  The targets are a number of monsters (who are on a lower level and active, so the player can have a few minutes of combat whilst testing out the various sniper rifles).

**Comment by shrimpza** [comment]
Updated author and gametype
