### ISSUE TITLE
[Map] DM-Coagulate

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#583]
Hash: cc163f0680caee20fd93e5f93679d8d07ed94e60
Current name: DM-Coagulate

The author of this version isn't Epic Games.  The readme indicates that this map uses a PS2 version by Ken "DrunKenobi" Lynch as a base - no author is given for the revisions to produce this current version.

**Comment by shrimpza** [comment]
Updated to "Ken "DrunKenobi" Lynch"
