### ISSUE TITLE
[Map] DM-ColorBlind

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#586]
Hash: 85ddbbd6f1b426a9916890a2fb0859a69f0e2a38
Current name: DM-ColorBlind

Not really sure what this is beyond a room of colours - gametype is Botpack.UTIntro - there are four PlayerStarts and nothing else.

I suppose it could be used as a DM map but pretty pointess given the size and lack of anything in the room.  No idea if it could be used as an Intro map.

**Comment by shrimpza** [comment]
Changed to Tests and Demos
