### ISSUE TITLE
[Map] DM-Confined

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#587]
Hash: fd8dc6a0afbaeb856a328f84a890048572c826e1
Current name: DM-Confined

Not sure what the purpose of this 'map' is - it's one of those oddities.  One PlayerStart, a chair, a boulder, an impact hammer and 3 redeemers in a very small room - obviously can't be played as a DM map.

For what it is worth, the author's name in the readme is Kyle "dumbass" Allen
though it's impossible to tell if this is a joke or not.

**Comment by shrimpza** [comment]
Changed gametype to Tests and Demos.

Just left the author as-is :shrug:
