### ISSUE TITLE
[Map] dm-dancefloor

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#600]
Hash: 0128843c771d8239ad7caef31e4ee4ee7800ae31
Current name: dm-dancefloor

For some reason, this map has no Packaged Files info

**Comment by shrimpza** [comment]
Seems to be an issue similar to #554, where the file is zipped very weirdly, and cannot be read.

I don't have ready access to a Windows machine, so I'm not sure how these look there or if the maps are actually playable.

**Comment by shrimpza** [comment]
Linked issue
