### ISSUE TITLE
[Map] DM-DesertRaid_INF

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#610]
Hash: fe933b1e4573b34b7aa4693f830a0d85f47755a9
Current name: DM-DesertRaid_INF

The author of this map is, according to the readme,  Ryan 'CoffeyCan' Coffey

Player Count = readme suggests two teams of 3 or less (it being a map made for Infiltration UT with teams)

**Comment by NeonKnightOA** [comment]
I gave it a playercount of 4-6.
