### ISSUE TITLE
[Map] DM-Deworld!

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#611]
Hash: aedcc175796e80a47406e9649cd0cd014365c28d
Current name: DM-Deworld!

Another oddity - a small rectangular room entirely covered (except for the floor) in a Mountain Dew texture which is back-to-front - 8 playerstarts - nothing else.

So a DM map for up to 8 players - perhaps?

**Comment by NeonKnightOA** [comment]
I gave it a playercount of 2-4. The rule of thumb I use to deduce playercount is:

Max = totalPlayerStarts/2
Min = totalPlayerStarts/4
