### ISSUE TITLE
[Map] DM-DireKeep

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#614]
Hash: 065581e4b1956c01b2bd3313cbe0689e8a0e111e
Current name: DM-DireKeep

The author name given in the Map Info - .nz - is just the end bit of the author's email address.

From the readme in the author's other map DM-PrayForMojo][.unr (hash  806d6423a98fb276fef4fd79b12fd4df7eee0b08)
the author's name is Stilgar@xtra.co.nz - which could be a 'working' email address - possibly the name should just be given as  Stilgar?

**Comment by NeonKnightOA** [comment]
The e-mail address was present in the Author's field, so I just shortened to Stilgar.
