### ISSUE TITLE
[Map] DM-Dogtown

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#617]
Hash: edbe7c3fa828d8dd65b9bfefb043ae4e3f94bf27
Current name: DM-Dogtown

According to the readme and to the screenshot the author of this map is Judas_Sinn
In the screenshot is is simply Judas Sinn

Probably this author should cited as Author for the other Dogtown maps where the Author is currently given as 	An Urban Street Battle Map (which is obviously a description of the map)

**Comment by NeonKnightOA** [comment]
I've just given him Judas_Sinn. And yeah, the other maps will be fixed as well. Also tried to replace all instances of the error, but there are just too many variations of DogTown that one or two may have slipped.
