### ISSUE TITLE
[Map] DM-Dungeon

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#626]
Hash: cabb6402c747ac39788ca7ee99440ae04c99f848
Current name: DM-Dungeon

According to the readme, the author is  Smiley.Tiger
the full name includes this person's email address which or may not be still working but thought it best not to include it

Player Count = 2-8

**Comment by OjitroC** [comment]
Have now discovered that Smiley.Tiger is actually two people  Smiley & SnowTiger
Now remember having come across them before

**Comment by NeonKnightOA** [comment]
Adding the proper authors in the field, and said pair added to various.txt.
