### ISSUE TITLE
[Map] DM-EBD-Hammer][

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#632]
Hash: d825349b7331d00b1e99ab004f935611d0eaf0a7
Current name: DM-EBD-Hammer][

One would suppose this is a map by  evil_blue_dude  given the EBD prefix but no concrete evidence - I haven't played it or the other Hammer version to look for stylistic similarities

**Comment by NeonKnightOA** [comment]
I think he's indeed the author, the problem is that the unrealplayground forums aren't there anymore.

IICR this one of the maps from the Community Tribute Classic mappack. I remember the name from there.
