### ISSUE TITLE
[Map] DM-EnforcerRoom

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#637]
Hash: db0b0554e9f2cfb1c2e3efcef57d70c733f28fe6
Current name: DM-EnforcerRoom

From the readme, the creator of this map is PARANOiA SURViVOR

Description = a large room filled with enforcers and ammo clips with a shield belt in the middle

Player Count = not more than 4

**Comment by NeonKnightOA** [comment]
I'm giving it a playercount of 2-4.
