### ISSUE TITLE
[Map] DM-EXTRIM

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#641]
Hash: 43442581b42f83c30544ec829521aad7145819b9
Current name: DM-EXTRIM

There is a screenshot in the zip archive which hasn't been used as the image on the map page.

**Comment by shrimpza** [comment]
Fixed screenshot and other metadata: https://unrealarchive.org/maps/unreal-tournament/deathmatch/E/dm-extrim_43442581.html
