### ISSUE TITLE
[Map] DM-FoggyZone

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#656]
Hash: ba222637dece2b1d3bac79c975de17a5e0f7cdba
Current name: DM-FoggyZone

Player Count : the map has 11 PlayerStarts though given the size of the map 11 players would be chaotic - probably about half that number would be reasonable, especially as it is, indeed, totally foggy.  The current Player Count info is less than informative.

**Comment by NeonKnightOA** [comment]
I'll use the same scheme (min= 25% of playerstarts; max= 50% of playerstarts) to deduce playerstart: from a base of 10 playerstarts, 2-5.
