### ISSUE TITLE
[Map] DM-FoT-Erebus

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#658]
Hash: 9e5ff9aa46aab9e784424bcb1f9cf512590697d7
Current name: DM-FoT-Erebus

The author's name is Revelation

Need to remove the ( after Revelation here and in all the other instances where Revelation( occurs

**Comment by NeonKnightOA** [comment]
Looks like the UA uploader doesn't parse well the URLs.
Fixed.
