### ISSUE TITLE
[Map] DM-FSW-Hotel-FreakShow][

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#664]
Hash: ba0562fcaea190cbf39237268a43a5f87a23b7f5
Current name: DM-FSW-Hotel-FreakShow][

This author has other aliases which include his real name Michael Lalla

**Comment by OjitroC** [comment]
These include  Michael<(DxTrEm3Fx)>Lalla

**Comment by NeonKnightOA** [comment]
For this one I guess I'm going with an author file.
