### ISSUE TITLE
[Map] DmFreedom

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#665]
Hash: 9d33e49ad3917556a3f21be785cbfa20462e63c7
Current name: DmFreedom

This is an Unreal map.

Like a lot of Unreal maps, it can be played in UT as it uses no Unreal-specific actors.  It contains only Unreal weapons and pickups, which are swapped to UT ones when starting the map in UT.

It is, though, more properly classified as an Unreal map.

**Comment by NeonKnightOA** [comment]
Classified back as an Unreal map.
