### ISSUE TITLE
[Map] DM-Galandia

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#666]
Hash: 48c7b12ec99f19ec8bd23ceeb9f781c54878f0ad
Current name: DM-Galandia

This author is also known as Johan 'Eranek' Samuelsson

Johan 'IceCat' Samuelsson is an earlier name

May also use 
Eranek
IceCat

**Comment by NeonKnightOA** [comment]
Author alias file for this one.
