### ISSUE TITLE
[Map] DM-GMCMuseumB

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#670]
Hash: 1552c4a981095292d9a19899592a958d959004c1
Current name: DM-GMCMuseumB

In the readme for an identical version of this map, the author's name is   {CBGB}Asha'man, Chris Barnett

Whether this means Chris Barnett was also  {CBGB}Asha'man  or that a Chris Barnett original was modified by  {CBGB}Asha'man is unclear - possibly the former I would think as the map is copyright to Chris Barnett.

Player Count = 6-8

**Comment by shrimpza** [comment]
Updated author and player count.
