### ISSUE TITLE
[Map] Dm-HangingGardens

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#675]
Hash: 6cdd9953a9365bc7dc189d323e7137c806f23a45
Current name: Dm-HangingGardens

The author's name should just be 	Adam Sims "Oblivion_Soldier"
the rest is his email address

This author also uses the name  Adam "Obliviion_Soldier" Sims

**Comment by shrimpza** [comment]
Updated author to remove email address and be in line with what seem to be most of his other maps: "Adam Sims aka Oblivion_Soldier"
