### ISSUE TITLE
[Map] DM-Hell_Raisers_Caverns

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#677]
Hash: d8ccdb3932c77c0cf54fd00ab7ba0acfccfbb018
Current name: DM-Hell_Raisers_Caverns

From the readme, the author's name is Francois Lacombe

He also used the aliases  
Orion(Co30)
Mouse(Co30)

and these may appear in various combinations with  Francois Lacombe

**Comment by shrimpza** [comment]
Fixed with an aliases file for the author.
