### ISSUE TITLE
[Map] DM-INFERNO-FUNNEL

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#695]
Hash: 865b9c383715abce9b1350e2267c09f349eabbe9
Current name: DM-INFERNO-FUNNEL

For some reason, the author's name that appears under Map Information is truncated and the full name is given when holding the cursor over the name link - the name on the author tab to which the link goes is also truncated so -=Noda  shows instead of -=Noda=-

This happens quite a lot where the author name has special characters after alphabetical characters.

**Comment by shrimpza** [comment]
Looks like this was fixed via some other name fixes already

![image](https://user-images.githubusercontent.com/6191747/135556746-a512ea3b-cb21-40d1-9bf1-22771042de6d.png)
![image](https://user-images.githubusercontent.com/6191747/135556760-519ac874-46b1-4d0d-8ed7-cd97aeafbc43.png)
