### ISSUE TITLE
[Map] DM-IntoEternity

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#698]
Hash: 5daf13deb62f6a95f1ac868ab1ca7788181f16bc
Current name: DM-IntoEternity

From the readme, the author is  Thomas Schmiedel
rather than his (defunct?) website

**Comment by shrimpza** [comment]
Seems proper now according to the current version on the Archive, so probably an aliasing bug resolved this.

![image](https://user-images.githubusercontent.com/6191747/135556468-b936ba7c-7677-403c-bbb2-bfb008997c12.png)
