### ISSUE TITLE
[Map] DM-JBDevilfish

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#705]
Hash: 23d553c7aa8b124cb6d489425dab7a842a4c913f
Current name: DM-JBDevilfish

This is a Demo map for the JBDevilfish (and Squid) - four tanks each with two Devilfish or Squid in - one playerstart above each tank in a metal tank with a movable floor - move the floor and the player falls into the tank.  Bots can't trigger the floor.  

So not really a DM map.

**Comment by shrimpza** [comment]
Updated
