### ISSUE TITLE
[Map] dm-jumpspot_xlocdest_tute

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#709]
Hash: 20f01289cb574a20dcbfa8df6e70e2c95e0fbbe1
Current name: dm-jumpspot_xlocdest_tute

This is a Demo or tutorial map for mappers to learn how to do jumpspots, xloc combos and other 'stuff' - not a DM map

**Comment by shrimpza** [comment]
Updated
