### ISSUE TITLE
[Map] DM-jumpspot_xlocdest_tute

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#710]
Hash: 8f5ba1e3ba38465f6dfbfd447e8b83b44d948b2d
Current name: DM-jumpspot_xlocdest_tute

This is a Demo or tutorial map for mappers to learn how to do jumpspots, xloc combos and other 'stuff' - not a DM map

**Comment by shrimpza** [comment]
Updated
