### ISSUE TITLE
[Map] DM-JungleWarfare

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#711]
Hash: df388cd3fdf3c304aad10b999fec2d378415475a
Current name: DM-JungleWarfare

The author of this, and the other variant of JungleWarfare, is Morten(--M&J--)Vatndal
From the readme for one of them.

**Comment by shrimpza** [comment]
I've set it to "Morten 'MMV' Vatndal", since I've found a lot of other content for Morten Vatndal under that name.
