### ISSUE TITLE
[Map] DM-KATRAVERONE

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#713]
Hash: 276a6849bcd8d2733dddaed0257d412e5550189f
Current name: DM-KATRAVERONE

According to the readme, the author is  VPV

**Comment by shrimpza** [comment]
I'm going to leave this one as is, since the author name has been gathered from the actual map author field, and there's no other content attributed to "VPV", or "VirginPinkDildo", so it seems much of a muchness.
