### ISSUE TITLE
[Map] DM-!!![LaserPod]

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#717]
Hash: 6b1105c0fe6682eef872f7969813545ccbd63a2a
Current name: DM-!!![LaserPod]

The readme is signed, as it were, FUZ
This could be the name of the map's author
The web address doesn't seem to have any information that could identify the mapper.

**Comment by shrimpza** [comment]
Managed to find some maps on that side with author `[UT]Chaos`, so I'm going to alias ut99maps.wordpress.com to that.
