### ISSUE TITLE
[Map] dm-[LLTF]-LedgeDance

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#718]
Hash: 3779a281b6842055f20f1cf34eabab9b857d3e10
Current name: dm-[LLTF]-LedgeDance

According to the readme, the author is [LLTF]FoamyGal
who may also have used just FoamyGal

**Comment by shrimpza** [comment]
This person seems to have had trouble maintaining their clan allegiance, added all these aliases:

```
FoamyGal
[KFH]FoamyGal
Marc "FoamyGal" Buchbach
[TrufF]FoamyGal
[lltf]fOAMyGAL
[LLTF]FoamyGal
Foamygal (bored like hell at 6 am)
[CBCG]FoamyGal
[LLTF] FoamyGal
[KFH]FoamyGal for SCA
(CBCG)FoamyGal
```
