### ISSUE TITLE
[Map] DM-L'OkiArenaC][

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#719]
Hash: 2cb7d2dcb8f5c5954ce18f84a129955b5117a2c1
Current name: DM-L'OkiArenaC][

From the readme, the author name should be  L'Oki

Whether there should be joint authors is a moot point in this case - as the readme (looks like it was written by Dawn) credits Dawn, also know as Dawn Knight, for some help.  This may well apply to some of the other maps by L'Oki 

The readme gives the Player Count as 2-8

**Comment by shrimpza** [comment]
Done
