### ISSUE TITLE
[Map] DM-Ladder_Tutorial

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#722]
Hash: 3e9e24b8c1627221b85dceddf9c7870c0162ee1c
Current name: DM-Ladder_Tutorial

As the name suggests, and playing the map reveals, this is indeed a Demo or Tutorial map and NOT a DM map.

There's no text or explanation in the map but someone can look in the Editor to see how the ladder in the map is produced.

**Comment by shrimpza** [comment]
Updated
