### ISSUE TITLE
[Map] DM-LEGIO VII

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#726]
Hash: 8c8b7c6d95fc5d99fa4c4e9c94158215f1341196
Current name: DM-LEGIO VII

From the readme, the author is Ruben Garcia Lopez
the remainder is the town, etc in Spain where he lives, which probably shouldn't be part of the name
This author also uses the name  MAQUINA

**Comment by shrimpza** [comment]
Fixed
