### ISSUE TITLE
[Map] DM-(NYA)Trofa_City_West

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#742]
Hash: 73a2f1b2a681ddbe023703b410821066ee07913e
Current name: DM-(NYA)Trofa_City_West

Need to add Builded NYA-Mike 
or Builded By NYA-Mike
whichever is relevant to how the authors are 'grouped'

to the NYA Mike alias file

**Comment by shrimpza** [comment]
Fixed
