### ISSUE TITLE
[Map] CTF-Frogger

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#743]
Hash: e4a73dd5208efb4bea31ccdc0096b0fd5a075aed
Current name: CTF-Frogger

Probably this should be under Map Packs as the archive contains 2 maps.

**Comment by shrimpza** [comment]
I prefer to keep these as one, which is what has happened here by design.

It's basically distributed as one map, with variations.

Similar example would be maps with "DM-Map" and "DM-MapNight".
