### ISSUE TITLE
authors/eenocks_mh-barbie.html

### ISSUE THREAD

**Issue by SeriousBarbie** [unreal-archive/unreal-archive-data#747]
Haha, the author is detected as "MH-Barbie". In fact the map [MH-ExtremeCoreV2(SB)](https://unrealarchive.org/maps/unreal-tournament/monster-hunt/E/mh-extremecorev2sb_682cf94c.html) is a conversion of the Unreal 1 maps _ExtremeCore_ and _ExtremeGen_ to MonsterHunt.

Author: Eenocks
Modder: Barbie
(see also containing info file "MH-ExtremeCore(SB).htm")

**Comment by shrimpza** [comment]
It will now just show as `Eenocks/Barbie`.

Proper "Modded by" support may come one day later.
