### ISSUE TITLE
[Map] KOTH_Wilderness

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#755]
Hash: 83c8b304a7fcfc9a88a8d0e8bc17bf286b6b5d98
Current name: KOTH_Wilderness

Not a Single Player map but for ChaosUT KOTH - says the readme.  KOTH = Kng of the Hill - a specific gametype for Chaos and not the Unreal gametype.

**Comment by shrimpza** [comment]
Weird, the data indicates it is already set as a Chaos map, but it doesn't show up in the Chaos listing. Will come back to this one.

**Comment by shrimpza** [comment]
Aha. It was weirdly duplicated as both a KOTH and SP map, bu the SP one was taking preference.

Should be fixed now.
