### ISSUE TITLE
[Map] SP-Ruines

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#756]
Hash: a7ddbc3c6869904d5c8b9981b8bb8bb3b8e80570
Current name: SP-Ruines

This one is problematic in the sense that although it IS a Single Player map it is also more of a demo map - as the readme says "Its main purpose is to serve as an example for the SinglePlayer4UT mod" and moreover it is a SP map that will only work with that mod according to the readme.

The ideal player count = 1

**Comment by NeonKnightOA** [comment]
Sent to Tests and Demos.
