### ISSUE TITLE
[Mutator] Nephthys mod for Unreal1

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#760]
Hash: 985b622f6e9dc1f26685db1ff271ec4017058f71
Current name: Nephthys mod for Unreal1

As the name suggests this is for Unreal - the readme says it's compatible with "Unreal 224v, Unreal 225f, Unreal 226b (Gold), Unreal 226f, Deus Ex 1100 (1112fm)"

**Comment by shrimpza** [comment]
Fixed
