### ISSUE TITLE
[Map Pack] NiXmaps

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#762]
Hash: 3b4f548a2b549db31a44a9b5a59b9fcf15091c32
Current name: NiXmaps

There are lots of muliple entries for the same texture files - could save space here by reducing them to a single entry for each pack - possibly caused by the way the map packs are 'parsed' though I don't recalll seeing anything similar for other map packs?

**Comment by shrimpza** [comment]
Hmm, it looks like this is less a traditional map pack and rather a collection of individually packaged maps.

Still though, the files should indeed only be listed once.

**Comment by shrimpza** [comment]
Fixed all the duplicate files.
