### ISSUE TITLE
[Map] DM-JT-TrainingDay

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#783]
Hash: c8b1cca563d5f852c386351271e438ef1efe84a7
Current name: DM-JT-TrainingDay

Not a DM map despite the prefix - only one PlayerStart - it is a translocator or BT training map.

**Comment by NeonKnightOA** [comment]
As a matter of fact, it is a training map, but no gametype would recognize the TUT- prefix that Epic used in the latest Unreal games such as UC2 and UT4, so I just put the DM there.

**Comment by NeonKnightOA** [comment]
It was sent to Single Player.
