### ISSUE TITLE
Duplicated xml files

### ISSUE THREAD

**Issue by NeonKnightOA** [unreal-archive/unreal-archive-data#790]
There are some duplicate files in the repository. This makes working with the repo on non-case-sensitive systems such as Windows a nightmare. This is a list of them:

* content\Unreal Tournament 2004\Maps\Assault\O\3\1\67af5d\as-overlord2k4_[3167af5d].yml
* content\Unreal Tournament 2004\Skins\S\d\1\2f6a4a\selene_[d12f6a4a].yml
* content\Unreal Tournament\Maps\Capture The Flag\D\f\9\5e4c68\ctf-dwell_[f95e4c68].yml
* content\Unreal Tournament\Maps\DeathMatch\C\1\0\49a608\dm-cut_cerebro_[1049a608].yml
* content\Unreal Tournament\Maps\DeathMatch\C\3\b\c3e0c9\dm-cut_sinastar_[3bc3e0c9].yml
* content\Unreal Tournament\Maps\DeathMatch\C\7\f\060711\dm-cut_dali_v2_[7f060711].yml
* content\Unreal Tournament\Maps\DeathMatch\C\9\6\c86a73\dm-cut_dungeon_[96c86a73].yml
* content\Unreal Tournament\Maps\DeathMatch\D\6\8\55e035\dm-deck13_[6855e035].yml
* content\Unreal Tournament\Maps\DeathMatch\S\f\7\830c5c\dm-sithed_[f7830c5c].yml
* content\Unreal Tournament\Maps\Domination\C\0\5\f75ced\dom-cut_dungeon_[05f75ced].yml
* content\Unreal Tournament\Maps\Unknown\M\7\f\4f56bd\mm-duskfalls_[7f4f56bd].yml
* content\Unreal Tournament\Models\C\4\b\d80444\cdbtacademy_[4bd80444].yml
* content\Unreal Tournament\Mutators\A\5\1\9ecdcc\arenamatch120_[519ecdcc].yml
* content\Unreal Tournament\Mutators\E\0\5\acd7f7\eavydarkmatchiii_[05acd7f7].yml
* content\Unreal Tournament\Mutators\E\6\9\1ce1ab\eavyadjustskill_[691ce1ab].yml
* content\Unreal Tournament\Mutators\T\5\0\227995\technologbonuspack_[50227995].yml

**Comment by shrimpza** [comment]
Nice find, thanks.

I own cleanup process identified the same 16 files, so I guess that's all of them.

```
unreal-archive-data/content/Unreal Tournament 2004/Skins/S/d/1/2f6a4a/Selene_[d12f6a4a].yml
unreal-archive-data/content/Unreal Tournament/Mutators/T/5/0/227995/Technologbonuspack_[50227995].yml
unreal-archive-data/content/Unreal Tournament/Mutators/A/5/1/9ecdcc/Arenamatch120_[519ecdcc].yml
unreal-archive-data/content/Unreal Tournament/Maps/DeathMatch/C/7/f/060711/DM-CUT_Dali_v2_[7f060711].yml
unreal-archive-data/content/Unreal Tournament/Models/C/4/b/d80444/CDBTAcademy_[4bd80444].yml
unreal-archive-data/content/Unreal Tournament/Maps/DeathMatch/C/3/b/c3e0c9/DM-CUT_Sinastar_[3bc3e0c9].yml
unreal-archive-data/content/Unreal Tournament/Maps/Unknown/M/7/f/4f56bd/MM-DuskFalls_[7f4f56bd].yml
unreal-archive-data/content/Unreal Tournament/Maps/DeathMatch/C/9/6/c86a73/DM-CUT_Dungeon_[96c86a73].yml
unreal-archive-data/content/Unreal Tournament/Maps/DeathMatch/S/f/7/830c5c/DM-Sithed_[f7830c5c].yml
unreal-archive-data/content/Unreal Tournament/Maps/DeathMatch/D/6/8/55e035/DM-Deck13_[6855e035].yml
unreal-archive-data/content/Unreal Tournament/Mutators/E/6/9/1ce1ab/EavyAdjustSkill_[691ce1ab].yml
unreal-archive-data/content/Unreal Tournament/Mutators/E/0/5/acd7f7/EavyDarkmatchIII_[05acd7f7].yml
unreal-archive-data/content/Unreal Tournament/Maps/DeathMatch/C/1/0/49a608/DM-CUT_Cerebro_[1049a608].yml
unreal-archive-data/content/Unreal Tournament/Maps/Capture The Flag/D/f/9/5e4c68/CTF-Dwell_[f95e4c68].yml
unreal-archive-data/content/Unreal Tournament 2004/Maps/Assault/O/3/1/67af5d/AS-Overlord2k4_[3167af5d].yml
unreal-archive-data/content/Unreal Tournament/Maps/Domination/C/0/5/f75ced/DOM-CUT_Dungeon_[05f75ced].yml
```
