### ISSUE TITLE
[Map] CTF-TwinTrains

### ISSUE THREAD

**Issue by SeriousBuggie** [unreal-archive/unreal-archive-data#808]
Duplicate of https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/T/ctf-twintrains_fa239ed1.html

---
Hash: 19039fb71757b83cf1570c5b43c282e90b16a5af
Current name: CTF-TwinTrains

**Comment by shrimpza** [comment]
Flagged as variation of https://unrealarchive.org/maps/unreal-tournament/capture-the-flag/T/ctf-twintrains_fa239ed1.html
