### ISSUE TITLE
[Map] AS-UP_Manor

### ISSUE THREAD

**Issue by SeriousBuggie** [unreal-archive/unreal-archive-data#821]
Duplicate of https://unrealarchive.org/maps/unreal-tournament/assault/U/as-up_manor_92aa4c2c.html

---
URL: https://unrealarchive.org/maps/unreal-tournament/assault/U/as-up_manor_dc4f8b49.html
Hash: dc4f8b49834af005d397dfd45fad2ce1661c730c
Current name: AS-UP_Manor

**Comment by shrimpza** [comment]
Updated!
