### ISSUE TITLE
[Map] MH-Redemption

### ISSUE THREAD

**Issue by SeriousBuggie** [unreal-archive/unreal-archive-data#824]
Assault map. Not MH. No monsters at all. In fact this is just renamed AS file.

---
URL: https://unrealarchive.org/maps/unreal-tournament/monster-hunt/R/mh-redemption_51fe0d9f.html
Hash: 51fe0d9f98d83720b8b81d28789f0b0445466fb2
Current name: MH-Redemption

**Comment by shrimpza** [comment]
Flagged as variation of https://unrealarchive.org/maps/unreal-tournament/assault/R/as-redemption_1fdc581f.html.

Even the map hash is the same :sweat_smile:

**Comment by SeriousBuggie** [comment]
Yes. And exists real MH version of this map.
