### ISSUE TITLE
[GameType] Neo Cairo

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#827]
URL: https://unrealarchive.org/gametypes/unreal-tournament/N/neo-cairo/index.html
Hash: None
Current name: Neo Cairo

For further info on Neo Cairo see the manual that comes with the mod - this includes the story/setting for the mod, plus info on the weapons, vehicles and much else as well as a list of the NC/Team Orbit team.

**Comment by shrimpza** [comment]
Mod has been updated, and the URL changed.: https://unrealarchive.org/gametypes/unreal-tournament/N/neocairo/index.html
