### ISSUE TITLE
[Map] BLC-RattlesnakeBend

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#828]
URL: https://unrealarchive.org/maps/unreal-tournament/unknown/B/blc-rattlesnakebend_e7f9bfd7.html
Hash: e7f9bfd7242ecfd9818f046ded02f22e8ded1bc2
Current name: BLC-RattlesnakeBend

This map is for the Badlands mod (as the BLC prefix suggests) so it is not Unknown - almost all of those in the Uknown category are for known games types or are demos/test maps, as I set out in a post on UT99.org.

**Comment by shrimpza** [comment]
Fixed, added Unreal Badlands gametype.
