### ISSUE TITLE
[Map] MH-LiandriVillageHub

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#832]
URL: https://unrealarchive.org/maps/unreal-tournament/monster-hunt/L/mh-liandrivillagehub_235a7fd0.html
Hash: 235a7fd07949cd460687f6606e24232142ed2737
Current name: MH-LiandriVillageHub

As the name suggests, this is a Hub map (for players on servers to choose which map to play, enter a teleporter and be transported to that map) and not a playable MH map - it could be put in the Entries and Intros category though it is not the same as those.  Since the type of map it is is known it doesn't fit into the Unknown category.  It could stay where it is but the Players number could be changed to 0 or None and the Description altered to indicate it is a non-playable Hub map.

**Comment by NeonKnightOA** [comment]
Entries and Intros is meant to be for Flybys.

This one will be placed in Tests and Demos.
