### ISSUE TITLE
[Map] MH-Malus_Keep

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#833]
URL: https://unrealarchive.org/maps/unreal-tournament/monster-hunt/M/mh-malus_keep_cd7fb063.html
Hash: cd7fb063d03828373a523d4fe2f609d2e367ba6e
Current name: MH-Malus_Keep

This is not a playable MH map - it consists of a 'flight' through the Keep and looks to me like a Demo map for the maker's textures.  The flight ends in a dungeon with 'real' krall that kill the player - restarting the map results in the death of the player presumably because the start of the map is a 'void'.  There is a playable version of this I think but this isn't it.  Probably best placed in Demos?

**Comment by shrimpza** [comment]
Set to Tests and Demos
