### ISSUE TITLE
[Map] MH-[SP]ArmedAssault

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#834]
URL: https://unrealarchive.org/maps/unreal-tournament/monster-hunt/S/mh-sparmedassault_51cdee57.html
Hash: 51cdee5786d59ed84915513bfe20e1d5a7e4f903
Current name: MH-[SP]ArmedAssault

ALL the MH maps with the [SP] prefix are for Unreal and NOT for UT99.  Possibly some of them aren't played anyway because of missing files, available only from the Snipers' Paradise website.

**Comment by shrimpza** [comment]
Hmm, there are an awful lot of these :X

**Comment by shrimpza** [comment]
Added a variation of Monster Hunt for SP Monster Hunt so the files can be downloaded, and moved the maps to Unreal.

https://unrealarchive.org/gametypes/unreal-tournament/M/monster-hunt/sp-monster-hunt/index.html
