### ISSUE TITLE
[Map] MH-ServerReset

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#835]
URL: https://unrealarchive.org/maps/unreal-tournament/monster-hunt/S/mh-serverreset_24f14ba5.html
Hash: 24f14ba51df2622a730aca1afef9023444bc38dd
Current name: MH-ServerReset

As the map name indicates, this is not a playable MH map - it is not a map at all but a text announcement that the server has crashed or been reset and a Monster End to trigger a revote.

**Comment by NeonKnightOA** [comment]
Sending it to Tests and Demos.
