### ISSUE TITLE
[Map] MH-StuffStorage_noGame

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#836]
URL: https://unrealarchive.org/maps/unreal-tournament/monster-hunt/S/mh-stuffstorage_nogame_702ef06c.html
Hash: 702ef06c2a6ea2ea2ce028c189cc809ef3c7496f
Current name: MH-StuffStorage_noGame

Not a playable MH map but a Demo 'map' of several different autocannons and a Dizzy Skaarj monster - so should be under Demos and Tests.

**Comment by shrimpza** [comment]
Updated
