### ISSUE TITLE
[Map] MH-NOFF(ScriptsOnly)

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#840]
URL: https://unrealarchive.org/maps/unreal-tournament/monster-hunt/N/mh-noffscriptsonly_b7030f7a.html
Hash: b7030f7a714e25aa67abcf1f6ccf00bd52cb9dae
Current name: MH-NOFF(ScriptsOnly)

This is made by gopostal (Kelly/Jack Griffin) - it is not a playable MH map but a Demo map for the No Friendly Fire actor that stops monsters from attacking one another in all circumstances.

**Comment by shrimpza** [comment]
Moved to tests and demos
