### ISSUE TITLE
[Map] MH-GatewayCoop

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#841]
This is not a playable MH map but a Hub map - the Unreal map Gateway with a series of teleporters to other Unreal maps. 

---
URL: https://unrealarchive.org/maps/unreal-tournament/monster-hunt/G/mh-gatewaycoop_ca0bc17b.html
Hash: ca0bc17bb9ada0e0b305cf5e6eee58b98487b5db
Current name: MH-GatewayCoop

**Comment by NeonKnightOA** [comment]
Sent to Tests and Demos.

**Comment by NeonKnightOA** [comment]
Also fixed author name to prevent confusion.
