### ISSUE TITLE
[Map] MH-(dU)Giranbeta

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#845]
This is not a playable MH map - it is the base map for the later Giran Town project.  Giranbeta has all the buildings, etc though they are, to some extent, unfinished or unpolished but cotnains no sounds, pickups of any kind or monsters. So all the player can to do is wander around the map. 

---
URL: https://unrealarchive.org/maps/unreal-tournament/monster-hunt/D/mh-dugiranbeta_9ccd0bd5.html
Hash: 9ccd0bd5846f47a98d18ff2b8bd66702f9b67809
Current name: MH-(dU)Giranbeta

**Comment by NeonKnightOA** [comment]
Sent it to Tests and Demos, then.
