### ISSUE TITLE
[Map] MH-MOVERTUT

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#847]
Not a MH map but a tutorial map for a mover (not that it seemed to work for me!!).  So probably put under the Demos/Tests category?

---
URL: https://unrealarchive.org/maps/unreal-tournament/monster-hunt/M/mh-movertut_437580fc.html
Hash: 437580fc2a844cb9393cde6c8b1c53e5fcfe54fb
Current name: MH-MOVERTUT

**Comment by OjitroC** [comment]
Don't know why that is in bold - not deliberate.

**Comment by shrimpza** [comment]
Moved to tests and demos
