### ISSUE TITLE
[Map] MH-WPDemo

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#851]
Not a playable MH map - a test map for a monster waypoint to test bot reaction - my bot didn't seem to do what was required!  A Test/Demo map.

---
URL: https://unrealarchive.org/maps/unreal-tournament/monster-hunt/W/mh-wpdemo_522441d0.html
Hash: 522441d0ab264fb03ba81f0a680f453838cd8586
Current name: MH-WPDemo

**Comment by NeonKnightOA** [comment]
Sending it to Tests and Demos then.
