### ISSUE TITLE
[Map] MH-UKTown

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#853]
Not a MH map - no monsters - it has an AssaultInfo actor so possibly an AS version of the UK Town map that someone intended to convert to MH? Not sure how one would categorize this?

---
URL: https://unrealarchive.org/maps/unreal-tournament/monster-hunt/U/mh-uktown_01bd1f8e.html
Hash: 01bd1f8ee19fa7c6a7e096e164f415438a66f948
Current name: MH-UKTown

**Comment by NeonKnightOA** [comment]
Does it contain the rest of the Assault classes? FortStandard and so on...

For the moment I'm placing it on Tests and Demos until a decision is made.
