### ISSUE TITLE
[Map] MH-MissionMonsterImposible-AlfaTest

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#860]
The link from the MH Maps -> M is to this map - but it is missing a file (.umx).  The other version of this map has that missing fie and so it would probably be better to link directly to that one? 

---
URL: https://unrealarchive.org/maps/unreal-tournament/monster-hunt/M/mh-missionmonsterimposible-alfatest_3d6b2ad8.html
Hash: 3d6b2ad8ae8ea52186187100ce09e1e255c973fd
Current name: MH-MissionMonsterImposible-AlfaTest

**Comment by shrimpza** [comment]
Seems reasonable, I switched the variation around.
