### ISSUE TITLE
[Map] MH-UnNamed(NM)

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#862]
This appears to be an early version of KrallCellars - it lacks the upper level - it also lacks anything to 'fight' - plenty of playerstarts, some weapons, and a nicely designed and textured map but no monsters and no MonsterEnd. So nothing to do in it other than wander around for a bit.  Not a playable MH map in the full sense - possibly best categorised as a Test/Demo? 

---
URL: https://unrealarchive.org/maps/unreal-tournament/monster-hunt/U/mh-unnamednm_86392946.html
Hash: 86392946f382d1567b88ad916de00c591fb21c82
Current name: MH-UnNamed(NM)

**Comment by shrimpza** [comment]
Moved to demos category.
