### ISSUE TITLE
[Voice] Triada - Female One

### ISSUE THREAD

**Issue by Andrei-Kekov** [unreal-archive/unreal-archive-data#863]
Hi, I am Metagalaxian, the author and uploader of this mod. The automatically generated name of the mod is misleading - it should be "Russian Voicepack Bundle". Also the Info column says "4 voices included", but it's actually 20.

---
URL: https://unrealarchive.org/voices/unreal-tournament/T/triada-female-one_839ea47b.html
Hash: 839ea47b027eb4f03ba0a052d2f9f634dca45856
Current name: Triada - Female One

**Comment by shrimpza** [comment]
Ranamed to "Russian Voicepack Bundle".

Fixed missing voices.
