### ISSUE TITLE
[Map] MH-UM-Dogtown

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#870]
There's no Required Files list for this one?

---
URL: https://unrealarchive.org/maps/unreal-tournament/monster-hunt/U/mh-um-dogtown_11929d37.html
Hash: 11929d3760b304285879552ac66e6149119e8adb
Current name: MH-UM-Dogtown

**Comment by shrimpza** [comment]
Looks like some of these files may have corrupt packages or there's a bug in my package library. In this case specifically, it seems `M1.utx` can't be read correctly. Investigating.

**Comment by shrimpza** [comment]
Fixed for about 50 UT99 maps.

It also looks like some of these maps ship with a lot of dependencies which are not used...
