### ISSUE TITLE
[Map Pack] Ctfmaps

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#874]
For some reason, CTF map packs appears twice for Unreal - with the same one mappack.

---
URL: https://unrealarchive.org/mappacks/unreal/capture-the-flag/C/ctfmaps_08535464.html
Hash: 08535464cd707e08bd3099f45d052b5da9d8933b
Current name: Ctfmaps

**Comment by NeonKnightOA** [comment]
There's one Ctfmaps for Unreal, and it seems to be an Unreal version of the DE Bonus Pack. Nevertheless I've fixed it.
