### ISSUE TITLE
[Map] WhirlMap

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#877]
This is a Map Pack - it's a single player campaign called Last Escape from Na Pali and consists of four maps. 

---
URL: https://unrealarchive.org/maps/unreal/single-player/W/whirlmap_3ed87ab2.html
Hash: 3ed87ab2ce6071597d12c2c16500ff0c3e5b7045
Current name: WhirlMap

**Comment by NeonKnightOA** [comment]
Already fixed.
