### ISSUE TITLE
[Map] DM-Bases

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#880]
Are you sure this is for Unreal?  There doesn't appear to be anything Unreal specific in the map.  It is an odd map though - I suspect it was intended to be a CTF map going by the layout and the presence of a Red flag and Blue Flag in the opposing bases (though there are no FlagBases).  It runs fine in UT and uses the UT version of Botpack.  

There is a LadderInventory actor in the map - not sure why. 

---
URL: https://unrealarchive.org/maps/unreal/deathmatch/B/dm-bases_e2a8ea66.html
Hash: e2a8ea66b90cc42042c37ca92e2a8683424ffd9b
Current name: DM-Bases

**Comment by shrimpza** [comment]
This was likely automatically flagged as Unreal based on release date - likely when someone packaged it, they had their system time wrong. The package map's engine version is also 68, which means Unreal (UT seems to be 69+); although it's not unusual for some maps to be built for UT using Unreal's UnrealEd for some reason.

The dependency on Botpack seems to indicate its likely a UT map however, so updated.
