### ISSUE TITLE
[Map] DM-A-Sky City

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#884]
The author, according to the readme, is Adam Schumacher.

No. of recommended players = "as many as you have the balls to put in" (from the readme).

---
URL: https://unrealarchive.org/maps/unreal-tournament/deathmatch/A/dm-a-sky-city_736e711d.html
Hash: 736e711d392741fdb5f6f1b73341d0aa13eda114
Current name: DM-A-Sky City

**Comment by shrimpza** [comment]
Updated
