### ISSUE TITLE
[Map] DM-Temple

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#886]
This author is the same person as 	Pat-BadKarma-Fitzsimons 

---
URL: https://unrealarchive.org/maps/unreal-tournament/deathmatch/T/dm-temple_4cb3cf45.html
Hash: 4cb3cf45ac6218a4d56a549804f9ebd4dd5d1c71
Current name: DM-Temple

**Comment by shrimpza** [comment]
Added aliases:

BadKarma
Pat-BadKarma-Fitzsimons
Patrick Fitzsimons
