### ISSUE TITLE
[Map] DM-Unusual_place

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#887]
The map has four PlayerStarts, so the maximum number of players would be 4.

It is an unusual place - the map has no pickups of any kind, no weapons (and so no ammo), no health and no powerups. 

---
URL: https://unrealarchive.org/maps/unreal-tournament/deathmatch/U/dm-unusual_place_5a3be8bf.html
Hash: 5a3be8bf9912406427d203686fe30cef403cc78a
Current name: DM-Unusual_place

**Comment by shrimpza** [comment]
Updated player count to "Up to 4"
