### ISSUE TITLE
[Map] DM-MyFlat[LineARC]

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#889]
Actually BTPlusPlusv099_C.u isn't required to run the map - it works fine without it - looking in the Editor it is not in the map.  So the fact that BTPPUser.u is missing is only of consequence if someone should wish to run BTPlusPlus with the map (though since it seems to be mostly a BT mutator and this is a DM map, I don't see why anyone should wish to do so). 

---
URL: https://unrealarchive.org/maps/unreal-tournament/deathmatch/M/dm-myflatlinearc_f40fa9f8.html
Hash: f40fa9f8ab897a34bc253ed15f61a6d0b0e92a74
Current name: DM-MyFlat[LineARC]

**Comment by shrimpza** [comment]
That's a good point. Currently the dependency analyser looks at all files in the archive and checks for missing dependencies - but for maps, it should probably only evaluate things actually used/referenced by the map, so extra files like this case can be ignored.

**Comment by OjitroC** [comment]
Oh, I see - I had assumed that the dependency analyser did evaluate things used or referenced by a map - so I've not been looking at that really.  I have noticed that some archives  contain a large number of files and only a few are actually used in the map - from memory I think that the extra files tend to be textures.
