### ISSUE TITLE
[Map] DOM-AssaultCity

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#890]
This is a moot one - the original map is from the Jungle Warfare mod - this version is a conversion to DOM by (the infamous) Kaal979 - so the creator of the content in the archive is the latter, whilst the creators of the base map are the creators of the Jungle Warefare mod - in the readme for the mod they are called the Jungle Warfare Team and this would be a more accurate name for the author of the base map.  EIther way, Jungle Warfare is not the author - it's merely the name of a mod. 

Actually just looked at the JWF map and the author is FLachLayeR@yahoo.com - Kaal979 has changed this to Jungle Warfare in his DOM version. 

---
URL: https://unrealarchive.org/maps/unreal-tournament/domination/A/dom-assaultcity_cbb9bc96.html
Hash: cbb9bc965b486020f49e1691a03820dd5356cdd5
Current name: DOM-AssaultCity

**Comment by shrimpza** [comment]
Updated to "FLachLayeR / Conversion by Kaal979", since this seems to be the way most people credit conversions.

I want to do something in the future to flag conversions and maybe separate out original vs conversion authors more appropriately.

**Comment by OjitroC** [comment]
"I want to do something in the future to flag conversions and maybe separate out original vs conversion authors more appropriately."

That's a good idea and would more accurately reflect the actual situation - there's a lot of stuff like that out there and I'm not sure how the original authors feel about having their work altered but also about being credited with a conversion which they didn't do and may not like.  It also clarifies who's responsible for what particularly as regards technical errors in a map which may have been introduced by a conversion.
