### ISSUE TITLE
[Map] MH-MHA-Cursed_Pharaoh[Thunderbolt]

### ISSUE THREAD

**Issue by SeriousBarbie** [unreal-archive/unreal-archive-data#895]
The file link behind "Unreal Archive EU" has still URL-encoded brackets when downloaded:

`https://unreal-archive-files.eu-central-1.linodeobjects.com/Unreal%20Tournament/Maps/Monster%20Hunt/M/7/3/f2416d/MH-MHA-Cursed_Pharaoh%255BThunderbolt%255D.rar
`

---
URL: https://unrealarchive.org/maps/unreal-tournament/monster-hunt/M/mh-mha-cursed_pharaohthunderbolt_73f2416d.html
Hash: 73f2416d67055d3b00ca83e75e42c507be7cd44a
Current name: MH-MHA-Cursed_Pharaoh[Thunderbolt]
![URL-Encoded_brackets](https://user-images.githubusercontent.com/81397053/147366865-ee335679-15ce-4f81-9347-4ae849fb078c.jpg)

**Comment by NeonKnightOA** [comment]
Already fixed.
