### ISSUE TITLE
[Mutator] MHMapAdjuster

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#899]
The author of this mutator is gopostal (from the readme).

---
URL: https://unrealarchive.org/mutators/unreal-tournament/M/mhmapadjuster_d8fa76b5.html
Hash: d8fa76b5dbcc0862d92c496f43fb9df6a676e978
Current name: MHMapAdjuster

**Comment by shrimpza** [comment]
Updated
