### ISSUE TITLE
[Mutator] Relic: Disguise

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#900]
According to the readme, the author of this mutator is  Bog_Wraith 

---
URL: https://unrealarchive.org/mutators/unreal-tournament/R/relic-disguise_7aa0dbde.html
Hash: 7aa0dbde1748e4e0738c4cb721bba28a88ced097
Current name: Relic: Disguise

**Comment by NeonKnightOA** [comment]
Already fixed.
