### ISSUE TITLE
[Mutator] SPUnlimited Ammo

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#901]
This mutator is for Unreal going by the readme.

---
URL: https://unrealarchive.org/mutators/unreal-tournament/S/spunlimited-ammo_fe2f610d.html
Hash: fe2f610d1dfeb8239d51de59ed00af73e094a15f
Current name: SPUnlimited Ammo

**Comment by shrimpza** [comment]
Updated
