### ISSUE TITLE
[Mutator] .SuperSneakers

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#903]
According to the readme, the author of this mutator is ynohtnA
(real name Anthony Bowyer-Lowe)

---
URL: https://unrealarchive.org/mutators/unreal-tournament/S/supersneakers_5c231116.html
Hash: 5c2311168ba27c8cfb4b106f36e9d32e8c11ecfa
Current name: .SuperSneakers

**Comment by shrimpza** [comment]
Updated
