### ISSUE TITLE
[Mutator] Unreal: Enhanced

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#904]
According to the Readme, the author of this mutator is  UsAaR33 

---
URL: https://unrealarchive.org/mutators/unreal-tournament/U/unreal-enhanced_7a2be4aa.html
Hash: 7a2be4aa848deb8a009749ace447acd55bfb995b
Current name: Unreal: Enhanced

**Comment by shrimpza** [comment]
Updated
