### ISSUE TITLE
[Mutator] WrathRelics

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#906]
The author of these mutators is Wrath

There are 3 and not 6 mutators - the descriptions are duplicated and the count of 6 on the W page is wrong. 

---
URL: https://unrealarchive.org/mutators/unreal-tournament/W/wrathrelics_20f584b7.html
Hash: 20f584b76ac5bdd15d8a378793572e5bcd5e68af
Current name: WrathRelics

**Comment by shrimpza** [comment]
Updated
