### ISSUE TITLE
[Mutator] Wrelics

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#907]
The author of these mutators is Wrath

There are 2 mutators and not 4 mutators - the descriptions are duplicated and the count of 4 on the W page is wrong. 

---
URL: https://unrealarchive.org/mutators/unreal-tournament/W/wrelics_0cc64fd2.html
Hash: 0cc64fd29fe0497b921d24b50edc5a9f7872f547
Current name: Wrelics

**Comment by shrimpza** [comment]
Updated.

I suspect there may be 2 int files or duplicates in the int files.
