### ISSUE TITLE
[Mutator] Xanth - Realism

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#908]
Not entirely sure about this but the author's name is either Xanth or Xanth_UT - going by the readme and the email address therein.

---
URL: https://unrealarchive.org/mutators/unreal-tournament/X/xanth-realism_02e98b18.html
Hash: 02e98b187e9aab356c5630f74eafc91ac02c9469
Current name: Xanth - Realism

**Comment by shrimpza** [comment]
Updated
