### ISSUE TITLE
[Mutator] Zombies5 !!

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#910]
The author of this mutator is MrLoathsome

GoPostal (JackGriffin/Kelly) and Delacroix are also credited in the readme.

---
URL: https://unrealarchive.org/mutators/unreal-tournament/Z/zombies5-_285489e4.html
Hash: 285489e4ef4d270932a71e540059f5336079d11b
Current name: Zombies5 !!

**Comment by shrimpza** [comment]
Updated
