### ISSUE TITLE
[Mutator] TWT_Zombies!

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#911]
The author of this mutator is Third World Tech 

- hence TWT.  According to the readme, Third World Tech are

Mariano Trod: Idea, concepts, testing and 1 half painted texture!

Cristian Scandalo: Zombie in suit model, webcam mocap actor!

Ale Palmero: Coding, modeling and animation, webpage

---
URL: https://unrealarchive.org/mutators/unreal-tournament/T/twt_zombies_d6e5969e.html
Hash: d6e5969e10a73a73d7d11af29a51bafc20dc9b2d
Current name: TWT_Zombies!

**Comment by shrimpza** [comment]
Updated
