### ISSUE TITLE
[Mutator] Translate Redeemyourspace to eng

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#912]
The author of this mutator is Bob 
aka bobisunreal

Going by the readme this is for the Unreal version of RYS - no idea if it works with OldSkool in UT or with the other versions of RYS that are out there.
---
URL: https://unrealarchive.org/mutators/unreal-tournament/T/translate-redeemyourspace-to-eng_d9717a5b.html
Hash: d9717a5b250cd11cd6763e36723725918d88e91e
Current name: Translate Redeemyourspace to eng

**Comment by shrimpza** [comment]
Updated
