### ISSUE TITLE
[Mutator] TopReal

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#913]
The author of this mutator is Darkness (according to the readme)

The mutator requires Relics.u as some of the actors are subclassed from there - but I suppose everybody has that?

---
URL: https://unrealarchive.org/mutators/unreal-tournament/T/topreal_cd0bb7df.html
Hash: cd0bb7df5690cde27a473420783be13c8397c049
Current name: TopReal

**Comment by shrimpza** [comment]
Updated
