### ISSUE TITLE
[Map] DM-Imaginary[LineARC]

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#916]
A problem with the map rather than anything else but like the MH version (Sironex) it has some horrible BSP holes - don't get on the boats and don't go into any tunnels!! The result is falling out of the world.

---
URL: https://unrealarchive.org/maps/unreal-tournament/deathmatch/I/dm-imaginarylinearc_ed38c647.html
Hash: ed38c647286ced353c65841f79f4096f486d7577
Current name: DM-Imaginary[LineARC]

**Comment by shrimpza** [comment]
Linked as issue
