### ISSUE TITLE
[Mutator] Cuorig16 2

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#925]
From the info with the mutators, it looks like the author is kloc13

I've take that from the email address kloc13@canada.com

A description for the mutators would be "An IM Package for Cosmic Unreal" - taken from the info with the mutators.

---
URL: https://unrealarchive.org/mutators/unreal/C/cuorig16-2_8cb3049a.html
Hash: 8cb3049a3f8d23136d00d50ba2dfe9b07f2b6f71
Current name: Cuorig16 2

**Comment by NeonKnightOA** [comment]
Actual author is "Chris 'kloc Thirteen' Stewart". He created the \*Cosmic\* mutator.
