### ISSUE TITLE
[Mutator] ADR Weapons Pack 06

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#935]
Odd that for a weapons pack, Weapons = None in the Mutator Information.

From the info with the mutator there appear to be 13 weapons - I haven't tried this so can't verify it nor can I say if the weapons are much different to the UT and Unreal weapons the majority appear to be based on, going by the readme and .int file.

---
URL: https://unrealarchive.org/mutators/unreal-tournament/A/adr-weapons-pack-06_7483e80f.html
Hash: 7483e80f72121f430d31f04b698d731ced0923df
Current name: ADR Weapons Pack 06

**Comment by shrimpza** [comment]
Manually fixed
