### ISSUE TITLE
[Mutator] AllWeapons - Fully loaded!

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#941]
The author of this mutator is TheDane, according to the readme.

The readme says "This is just a rewrite of the original AllWeapons mutator made by: mason pairish"

---
URL: https://unrealarchive.org/mutators/unreal-tournament/A/allweapons-fully-loaded_40e2f2e1.html
Hash: 40e2f2e1c535ebd02b0daca809ef9cd7b419c491
Current name: AllWeapons - Fully loaded!

**Comment by NeonKnightOA** [comment]
I'll credit AllWeapons (the original) to mason pairish, and the rewriting to mason pairish and TheDane.
