### ISSUE TITLE
[Mutator] ArenaMatch

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#954]
The author is  Wormbo

---
URL: https://unrealarchive.org/mutators/unreal-tournament/A/arenamatch_ee2aaecd.html
Hash: ee2aaecda8618b1da20abde4cfef2155c13d6da3
Current name: ArenaMatch

**Comment by NeonKnightOA** [comment]
Already under fixing.

**Comment by shrimpza** [comment]
Change just merged
