### ISSUE TITLE
[Mutator] BiGiZ Monster Hunt Mutator V2

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#963]
From the info with the mutator, the author is   SRA BiGi 

---
URL: https://unrealarchive.org/mutators/unreal-tournament/B/bigiz-monster-hunt-mutator-v2_1370a7ef.html
Hash: 1370a7ef8ab8a3846203fdf959d41d8cba4ca318
Current name: BiGiZ Monster Hunt Mutator V2

**Comment by NeonKnightOA** [comment]
Already fixed.
