### ISSUE TITLE
[Mutator] BRespawn

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#980]
Author is complicated - it looks like this is a mutator produced by gopostal
In the code is the following note :
"//  Original mod done by spongebobut@yahoo.com | www.unrealriders.de code used with his permission
//  Also contains some work done by BobIsUnreal, thank you B
//  and from Nelsona, thank you Nels!
//  Code condensing and simplification for use in MH done by gopostal"
gopostal always credits contributors or those whose work he used - obviously up to you if you want to include spongebob, BobIsUnreal (has another name but can't remember what it is) and Nelsona (aka sektor211 in the author credits 

Description - "This mod allows you to keep your progress through long maps." (iparticularly aimed at MH maps - in essence, it places a respawn point in a map every 10 seconds so that, if killed, the player respawns at the latest respawn point and not, perhaps, at the beginning of a long map).

---
URL: https://unrealarchive.org/mutators/unreal-tournament/B/brespawn_83715994.html
Hash: 8371599480080608996af51cae066e6851e55ca6
Current name: BRespawn

**Comment by NeonKnightOA** [comment]
I'm crediting him by the moment.
