### ISSUE TITLE
[Mutator] BUFPack1 Weapons

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#985]
There's actually 6 weapons according to the .int file - Cheeselocator and IGRailgun have been missed for some reason?

The author is complicated - from the documentation and Wormbo's website, it looks like Cogworks were the author of the BUFPack but that Wormbo was a significant contributor - possibly credit both? 

---
URL: https://unrealarchive.org/mutators/unreal-tournament/B/bufpack1-weapons_321c8995.html
Hash: 321c89953857b7456022a0cc7bba696c0c9f2123
Current name: BUFPack1 Weapons

**Comment by NeonKnightOA** [comment]
I'll credit both of them.
