### ISSUE TITLE
[Mutator] ByesRidgeWeapons

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#988]
This mod includes 5 weapons and not None.

---
URL: https://unrealarchive.org/mutators/unreal-tournament/B/byesridgeweapons_7425259a.html
Hash: 7425259ad234e33dc61be31a34214ab8280a734b
Current name: ByesRidgeWeapons

**Comment by shrimpza** [comment]
Manually fixed
