### ISSUE TITLE
[Mutator] Capture CanAm

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#989]
The author of this mutator, according to the readme, are Cynical Modder and <lol>Tomcat

The readme says "This mod was coded by Cynical Modder and textured by <lol>Tomcat"

---
URL: https://unrealarchive.org/mutators/unreal-tournament/C/capture-canam_54ee35ab.html
Hash: 54ee35ab6249ec733c5393b7f5b27e70c9cd8951
Current name: Capture CanAm

**Comment by shrimpza** [comment]
Updated
