### ISSUE TITLE
[Mutator] ByesRidgeWeapons

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#990]
The weapons were made for (and come with) the MH map Rise of Evil - that map was made by VatcilliZeitchef so perhaps the mutator should be credited thus?

---
URL: https://unrealarchive.org/mutators/unreal-tournament/B/byesridgeweapons_7425259a.html
Hash: 7425259ad234e33dc61be31a34214ab8280a734b
Current name: ByesRidgeWeapons

**Comment by shrimpza** [comment]
Updated
