### ISSUE TITLE
[Mutator] ClimberArena

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#991]
The author of this mutator, according to the readme, is William 'Ntruder' Chenoweth

Possibly a better Description is "Climber2000 is a flexible grappling weapon for Unreal Tournament."?

---
URL: https://unrealarchive.org/mutators/unreal-tournament/C/climberarena_e0af0a53.html
Hash: e0af0a53e0084160f39555dca12fa0017d83848d
Current name: ClimberArena

**Comment by shrimpza** [comment]
Updated
