### ISSUE TITLE
[Mutator] Clones.u

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#992]
A more accurate Description of the mutator may be "when killed, players burst into tiny clones that rau around screaming and exploding"

The readme doesn't say who the author is though a clue is that the person made "SWWM and the Zanaveth Ultra Suite"

---
URL: https://unrealarchive.org/mutators/unreal-tournament/C/clonesu_33eb5235.html
Hash: 33eb5235a6457a77bde8d516e460e2a30765a159
Current name: Clones.u

**Comment by shrimpza** [comment]
Updated description, though left author, since I cannot locate either of those others.
