### ISSUE TITLE
[Mutator] Capture the Clover

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#994]
According to the readme, the authors of this mutator are Cynical Modder and <lol>Tomcat
Note : <lol>Tomcat is also know as Tomcat

---
URL: https://unrealarchive.org/mutators/unreal-tournament/C/capture-the-clover_f59f290c.html
Hash: f59f290c6d64e2f640bf750eba03cbeec0c4289f
Current name: Capture the Clover

**Comment by shrimpza** [comment]
Updated
