### ISSUE TITLE
[Mutator] Capture the Egg

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#995]
Another quirky CTF variant from Cynical Modder and <lol>Tomcat

---
URL: https://unrealarchive.org/mutators/unreal-tournament/C/capture-the-egg_f63c8bb1.html
Hash: f63c8bb183c16100f96fd8b0446c3c188d89ae1c
Current name: Capture the Egg

**Comment by shrimpza** [comment]
Updated
