### ISSUE TITLE
[Mutator] Closer

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#996]
According to the info with the mutator, the author is  David Frey aka Mastaba

The author's description in full is "This mutator gives instant rocket and grenade fire, and removes the ASMD combo. It also speeds up the rockets and decreases their damage. (Except for seeking rockets.)"

It is made for Unreal Tournament Demo - no idea if it works with the full UT99 version.

---
URL: https://unrealarchive.org/mutators/unreal-tournament/C/closer_85f689ba.html
Hash: 85f689ba5f8142bea1ac35e5da8d30b0e0c43465
Current name: Closer

**Comment by shrimpza** [comment]
Updated
