### ISSUE TITLE
[Mutator] Cluster Redeemer

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#997]
According to the info with the mutator the author is  unholy smoke

---
URL: https://unrealarchive.org/mutators/unreal-tournament/C/cluster-redeemer_cf8c2b5d.html
Hash: cf8c2b5d19f52e6796695397e00b1346ad5131a8
Current name: Cluster Redeemer

**Comment by shrimpza** [comment]
Updated
