### ISSUE TITLE
[Mutator] CoolWeapons

### ISSUE THREAD

**Issue by OjitroC** [unreal-archive/unreal-archive-data#999]
According to the readme, the author is  Martin "Pfhoenix" Actor

---
URL: https://unrealarchive.org/mutators/unreal-tournament/C/coolweapons_6be2aa6c.html
Hash: 6be2aa6c2ef861834b89e7673b762309a9edeebb
Current name: CoolWeapons

**Comment by shrimpza** [comment]
Updated
